Use Incognito token when performing Apollo requests in Incognito mode
neevaco/neeva-android pull request #1001
Opened 2022-09-26 05:12 UTC by dan-alcantara-neeva

* Introduce an `IncognitoApolloWrapper` that uses the `IncognitoSessionToken` when Apollo calls need to be made for the Incognito profile.

* Change `BaseApolloWrapper` so that it offers subclasses an opportunity to do something before performing a request.  `IncognitoApolloWrapper` uses it to check if the Incognito token is valid, requesting it if it isn't.

* Add tests for the `SessionToken` and `IncognitoApolloWrapper`.

* Change some logs so that they're not errors.

## Checklists

### How was this tested?
- [X] I tested this manually
- [X] I added automated tests
- [X] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes

### Manual test cases
Pre-req: Added logs that show what Incognito cookies are being used

#### See that the user gets an incognito token
1. Open the app
2. Open tab grid and switch to incognito
3. See that an incognito token is fetched and logged to the console
4. Navigate to neeva.com and confirm that the user sees the Incognito page

#### Confirm that incognito tokens are re-used after the app dies in the background:
0. Turn on "Don't keep activities"
1. Open the app
2. Open tab grid and switch to incognito
3. See that an incognito token is fetched and logged to the console
4. Navigate to neeva.com and confirm that the user sees the Incognito page
5. See that the same incognito token is used by reading the log
6. Background the app, which will kill the app in the background
7. Reopen the app
8. Watch the log and see the same Incognito token is re-used

## Issues addressed
* https://app.clickup.com/t/3chh6um

2022-09-29 18:04 UTC, dan-alcantara-neeva commented
@Kokobe Putting this back into draft so I can run some more tests

2022-09-29 19:20 UTC, dan-alcantara-neeva commented
@Kokobe Actually ready for review this time

2022-09-29 23:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/apollo/IncognitoApolloWrapper.kt
> +        return !userMustBeLoggedIn || incognitoSessionToken.isNotEmpty()
TODO(dan.alcantara): Double check `isNotEmpty()`

2022-09-30 00:01 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/WebLayerModel.kt
> +            val oldNeevaAuthToken = neevaUser.loginToken.getCurrentCookieValue()
rename loginCookie

2022-09-30 00:05 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/BrowserWrapperFactory.kt
> +            directories = directories,
Rearrange the arguments

2022-09-30 00:18 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
> +    abstract val cookieValue: String?
Rename to cachedCookieValue

2022-09-30 00:31 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/apollo/IncognitoApolloWrapperTest.kt
> +            apolloWrapper.prepareForOperation(userMustBeLoggedIn = false)
Add check to see if this is returning the right value

2022-09-30 00:32 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/apollo/IncognitoApolloWrapperTest.kt
> +        every { incognitoSessionToken.isEmpty() } returns false
remove

2022-09-30 00:34 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/apollo/IncognitoApolloWrapperTest.kt
> +    }
Add calls to check that requesting new token doesn't happen

2022-09-30 00:47 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/userdata/SessionTokenTest.kt
> +        initializeSessionToken(initialCookieValue = "")
Pre-set the cookie to see if it stays the same

2022-09-30 00:52 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/userdata/SessionTokenTest.kt
> +        every {
Delete, shouldn't be called

2022-09-30 01:20 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/userdata/SessionTokenTest.kt
> +        initializeSessionToken(initialCookieValue = "")
Can't set this or the cookie won't be requested

2022-10-03 18:30 UTC, dan-alcantara-neeva commented
Turning this back into a draft because the session cookies aren't wiping out as they should when you repeatedly log out and in.  Not sure if this is an existing problem or not.

2022-10-05 22:08 UTC, dan-alcantara-neeva commented
@Kokobe @yozuysal Actually, really, really ready for review with movies showing the test cases I was struggling with.  Will follow up this PR with more instrumentation tests that will try to make sure this works in an automated way.

2022-10-06 20:10 UTC, Kokobe commented on app/src/androidTest/java/com/neeva/app/LoginCookieInstrumentationTest.kt
> +
remove new line

2022-10-06 22:01 UTC, Kokobe requested changes
Initial comments

2022-10-06 22:15 UTC, Kokobe commented
Would be great to link: https://docs.google.com/document/d/1rRStjSXig6HfbaXPl4cXbJH_jGkRpTWdTIGsY7G9Gx0/edit#heading=h.sg0ob8ttl9ru

as a pointer to help with Review.

2022-10-06 23:26 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/LoginCookieInstrumentationTest.kt
> +    fun sessionToken_whenBrowserTokenUpdated_updatesCachedTokenAndFetchesUserInfo() {
That's what `loginToken.updateCookieManager` does: it directly changes the browser's cookie.  Would be kind of redundant to check, I think?

2022-10-06 23:27 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
> +            Log.e(TAG, "Failed to set $cookie in Browser because ded")
Er... removed 😅

2022-10-06 23:28 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivityViewModel.kt
> -        neevaUser.clearUserInfo()
It's in `RegularBrowserWrapper.kt`, during init:

```
        coroutineScope.launch(dispatchers.io) {
            neevaUser.loginToken.cachedValueFlow.collectLatest {
                if (neevaUser.isSignedOut()) {
                    neevaUser.clearUserInfo()
                } else {
                    // If Neeva's login cookie changes, we need to refetch the user's data.
                    neevaUser.fetch(authenticatedApolloWrapper, appContext)
                }
            }
        }
```

2022-10-06 23:29 UTC, Kokobe reviewed
More comments, but I'm still not done reviewing yet

2022-10-06 23:29 UTC, Kokobe commented on app/src/main/java/com/neeva/app/storage/TabScreenshotManager.kt
> -                    captureStack
Is the capture stack too annoying because this error keeps getting printed in logcat?

2022-10-06 23:29 UTC, Kokobe commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
> + * being the source of truth for the current cookie.
Not true for the `Login` Session cookie no? We are pulling its value from SharedPreferences

2022-10-06 23:30 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaConstants.kt
> +            isSessionToken = false
1. It's calling two different functions; `createPersistentNeevaCookieString` does something different in the `TestNeevaConstants` because OkHttp doesn't like creating cookies for 127.0.0.1.
2. If you do `by lazy`, then the compiler doesn't complain about the objects being created by calling functions on a subclass before initialization has completed.  When you build a subclass, it initializes the parent's objects first, so Android Studio and kotlin complain.

2022-10-06 23:30 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaConstants.kt
> +            isSessionToken = false
Ditto

2022-10-06 23:42 UTC, Kokobe commented on app/src/androidTest/java/com/neeva/app/LoginCookieInstrumentationTest.kt
> +    fun sessionToken_whenBrowserTokenUpdated_updatesCachedTokenAndFetchesUserInfo() {
It looks like that function sets the cookie using weblayer, but you aren't checking for success of that operation in this test file too. 

Like you could use the callback in `updateCookieManager` or check if it exists in weblayer's cookies. (I don't fully trust weblayer to do what it's supposed to anymore after learning about downloads, so I think its a good test for weblayer too)

2022-10-06 23:46 UTC, Kokobe commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
> +    private var weakBrowser: WeakReference<Browser> = WeakReference(null)
Put a comment on one way that the browser can die while SessionToken is also alive too?

2022-10-06 23:50 UTC, Kokobe commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
> +        // Sync the cookie back from the Browser.
Wording of the comment is a little confusing, would this work? 

"Updates the cached cookie from the browser"

2022-10-07 18:50 UTC, Kokobe commented on app/src/androidTest/java/com/neeva/app/LoginCookieInstrumentationTest.kt
>                  }
Don't forget to replace with `waitForUserInfoQuery()`

2022-10-10 18:40 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/apollo/AuthenticatedApolloWrapper.kt
> +        return !userMustBeLoggedIn || !loginToken.isEmpty()
Don't know if I agree in this particular case.  It's symmetric with the `!userMustBeLoggedIn` bit.

2022-10-10 18:41 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/apollo/AuthenticatedApolloWrapper.kt
> +    override suspend fun prepareForOperation(userMustBeLoggedIn: Boolean): Boolean {
Preview tokens aren't in yet; that's coming up in the next PR.  Trying to lay the groundwork for it in this PR.

2022-10-10 18:43 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaConstants.kt
>      val previewCookie: String = "httpd~preview"
Wanted to do this but didn't want to bloat the PR further.  Now that you've opened that door...

2022-10-10 18:45 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/sharedprefs/SharedPrefFolder.kt
> -        )
The bit you're missing is that we can't figure out the expiration of the token -- WebLayer doesn't give it to us.  We have to explicitly use the browser's cookie jar because WebLayer will stop returning it once the cookie has expired.

2022-10-10 18:46 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/storage/TabScreenshotManager.kt
> -                    captureStack
Annoying mainly because we can't really do anything about the log.  WebLayer fails to take screenshots in so many ways that are unactionable on our end, so letting us know just makes the log noisy.

2022-10-10 18:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
> + * being the source of truth for the current cookie.
Mostly true for the Login session cookie.  The changes in this PR specifically make it so that we tell the browser to update its cookie jar, which updates a flow that tells us to update the SharedPreference.

2022-10-10 18:51 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
> +        // Sync the cookie back from the Browser.
Went with:
`// Pull the cookie out of the Browser cookie jar and cache it in memory.`

2022-10-10 18:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                            neevaUser.loginToken.updateCookieManager(newValue = it) {
Not sure if a popup is warranted here: you usually want to let users know that something went wrong if there's something they could do again to fix the error.  If the browser fails to update the login cookie correctly, then I guess we'd have to tell them to log in again?

2022-10-10 19:03 UTC, Kokobe commented on app/src/main/java/com/neeva/app/sharedprefs/SharedPrefFolder.kt
> -        )
I think a good addition to the PR is if you added the implications/effects this has on how we use `Preview` and `Incognito` cookies - specifically this means everytime we use them, we have to check with the browser each time to make sure its not expired or to request a new one.

2022-10-10 19:38 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/LoginCookieInstrumentationTest.kt
> +    fun sessionToken_whenBrowserTokenUpdated_updatesCachedTokenAndFetchesUserInfo() {
Talked offline: added a log to `SessionToken` for all attempts to use `updateCookieManager`, but it's unlikely that this would ever fail because we're setting a cookie for `neeva.com` on `neeva.com`.

2022-10-10 21:27 UTC, Kokobe approved these changes

2022-10-11 01:00 UTC, merged