Update Share Space Link UI
neevaco/neeva-android pull request #1009
Opened 2022-09-27 23:43 UTC by Kokobe

Updates the Share Space Link UI to match the figma. 

## Checklists

### Pointers to help with review
* [Figma](https://www.figma.com/file/D3pbLY6ZP5YtCjTYqsGOKO/Android-Design-System?node-id=2070%3A33760) link
* See: https://neevaco.slack.com/archives/C01QW9Z7P3P/p1663799891561729

### How was this tested?
- [x] I tested this manually
- [x] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes

### Manual test cases
See screenshots below:

### Screenshots and screen recordings

<img width="1317" alt="Screen Shot 2022-09-27 at 4 42 53 PM" src="https://user-images.githubusercontent.com/20916043/192656518-e2a29922-1e72-427b-86b6-05854eefaf7a.png">
<img width="1293" alt="Screen Shot 2022-09-27 at 4 43 04 PM" src="https://user-images.githubusercontent.com/20916043/192656522-fa0b0dd5-44ce-4197-ba16-d6e3afa7860d.png">
<img width="1286" alt="Screen Shot 2022-09-27 at 4 43 14 PM" src="https://user-images.githubusercontent.com/20916043/192656523-40de7802-db5e-42ba-a1d0-68c29953a8e2.png">
<img width="1280" alt="Screen Shot 2022-09-27 at 4 43 18 PM" src="https://user-images.githubusercontent.com/20916043/192656524-fe036c1a-5823-44dd-a860-a332ddb57eb5.png">

2022-09-28 01:02 UTC, dan-alcantara-neeva requested changes
Spacing between your email box and permissions box looks off.

2022-09-28 01:02 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/spaces/share/ShareSpaceLinkUI.kt
> -            name = stringResource(id = R.string.facebook),
Is the facebook string used anywhere else?  Can you delete it?

2022-09-28 01:02 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/spaces/share/ShareSpaceLinkUI.kt
> +        horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.width(width = 56.dp)
Make 56.dp a `val` in this function instead of duping it.

2022-09-28 01:02 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/spaces/share/ShareSpaceLinkUI.kt
> +
Remove newline

2022-09-28 01:02 UTC, dan-alcantara-neeva commented on app/src/main/res/drawable/ic_share_icon.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Isn't there already a share icon in the Material icon library?

2022-09-30 06:40 UTC, Kokobe commented on app/src/main/res/drawable/ic_share_icon.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Yeah, I don't know why when we were using it, the circles were all filled in. I'll look into fixing this.

2022-09-30 06:48 UTC, Kokobe commented on app/src/main/res/drawable/ic_share_icon.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Wasn't using `Icons.Outlined.Share` lol

2022-10-03 18:22 UTC, dan-alcantara-neeva requested changes
Spacing between the email box and the permissions box doesn't match the spacing between the permissions box and the message box.  Can you fix that in a reasonable way?

2022-10-03 20:21 UTC, Kokobe commented
Spacing fix: 
![Uploading Screen Shot 2022-10-03 at 1.21.16 PM.png…]()

2022-10-03 20:29 UTC, dan-alcantara-neeva approved these changes

2022-10-04 21:01 UTC, merged