Add NeevaScope reddit indicator
neevaco/neeva-android pull request #1036
Opened 2022-10-11 20:54 UTC by yasminyin96

General description of what your PR does, written in a way that someone six
months from now could understand what you were doing when tracking down a bug
or attempting to add new functionality

* More details about the changes
* Even more details about the changes
* Yet more details about the changes

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2022-10-18 21:28 UTC, dan-alcantara-neeva commented
Can you confirm with UX that this is the right flow for the first time?  It's a little weird that we tell them to open NeevaScope with a popup and then make them hit "Got It" in the intro again.

2022-10-18 21:30 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/sharedprefs/SharedPrefFolder.kt
> +    object NeevaScope : SharedPrefFolder("NEEVASCOPE") {
Don't make another SharedPrefFolder.
1) Each of these SharedPreferences folders is saved as an XML file, which means that we add yet another file to read at startup.
2) This also means that we lose the old value of the SharedPref because it's in a different place.

2022-10-18 21:56 UTC, dan-alcantara-neeva requested changes
Took a first pass...

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopePromoModel.kt
> +class NeevaScopePromoModel(
Do you need another model for this?  This seems like it should live in the `NeevaScopeModel`.

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/toolbar/ToolbarButtons.kt
> +                    modifier = Modifier.size(Dimensions.NEEVASCOPE_TIP_SIZE),
This isn't a tip, right?  You should use an appropriately named constant, or just set this as `8.dp` because it's inherently different (a circle versus the tip of your popup).

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbarModel.kt
> +    abstract fun showNeevaScopeTooltip(): NeevaScopePromoType?
The function name doesn't make much sense: it sounds like a verb rather than a check.  Call it
`getNeevaScopePromoType` instead because it's more accurate.

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/IncognitoBrowserWrapper.kt
> +        bloomFilterManager = BloomFilterManager(
Do you really need different `BloomFilterManager`s?  Seems like you should just create a `@Singleton` in `NeevaAppModule` so that it can be shared by both the incognito and regular profile.  The `BloomFilterManager` doesn't record any data when it tries to check the bloom filter, right?

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeTooltip.kt
> +                delay(4000L)
1. Is this an arbitrary delay?  Where did it come from?
2. Use `TimeUnit.SECONDS.toMillis(4)` so it's obvious that you're waiting 4 seconds.

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/theme/Dimensions.kt
> +    val NEEVASCOPE_TIP_SIZE = 8.dp
This should just live in the file with the `NeevaScopeTooltip` composable after you remove the inappropriate use case.

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/sharedprefs/SharedPrefFolder.kt
> +            defaultValue = 5
Is 5 the correct limit?

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopePromoModel.kt
> +    fun getNeevaScopePromoType(uri: Uri): NeevaScopePromoType? {
Do you have a flag that will disable this feature (and the Bloom Filter download) entirely?  You shouldn't ever develop and add a bigger feature that could cause problems without gating it behind a feature flag.  Bonus points if this enable/kill switch is controllable from the backend, but we currently don't have support for that on the Android client.

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserBottomToolbar.kt
> +            if (showNeevaScopeTooltip == NeevaScopePromoType.TRY_NEEVASCOPE) {
Use a `when` for enums.

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +            val showNeevaScopeTooltip: NeevaScopePromoType? = remember {
How does this get updated?  AFAICT this will return a constant `NeevaScopePromoType?` that doesn't track anything.  Other places use a `Flow` and `collectAsState`.

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +                    if (showNeevaScopeTooltip == NeevaScopePromoType.TRY_NEEVASCOPE) {
Use a `when` for enums.

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterDownloadWorker.kt
> +        assert(reddit.checksumUrl.toString().endsWith(".json"))
Any idea why this check was backwards, and why it didn't crash when it originally landed?

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopePromoModel.kt
> +    val promoCache get() = _promoCache
This just returns another `MutableMap` because you didn't specify that it needs to be a regular `Map`, so the caller can still edit what it gets back.

2022-10-18 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopePromoModel.kt
> +
1. Take out the ?: part
2. Use a when to make it expllcit:

```
val filterResult: Boolean? = bloomFilterManager.contains(canonUrl.toString())
when (filterResult) {
    // The filter is still loading.
    null -> return

    true -> _promoCache[uri] = PromoState.hitFilter
    false -> _promoCache[uri] = PromoState.missFilter
}
```

2022-10-19 19:28 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/sharedprefs/SharedPrefFolder.kt
> +            defaultValue = 5
Found in cheatsheet weekly meeting note, Try neevascope promo is limited to 5 times

<img width="400" alt="Screen Shot 2022-10-19 at 11 55 08 AM" src="https://user-images.githubusercontent.com/104786010/196785565-19c707e2-abcd-480c-b4d6-2d497a9244bc.png">

2022-10-19 19:36 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterDownloadWorker.kt
> +        assert(reddit.checksumUrl.toString().endsWith(".json"))
Checksum file should be ended with `.json`, when I added the test for the downloading pipeline, I changed this by mistake. I will add one more test for this `DownloadWorker` to check that task is enqueued successfully.

2022-10-21 22:08 UTC, dan-alcantara-neeva requested changes

2022-10-21 22:08 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeTooltip.kt
> +            maxWidth = 240.dp
1. Why the diff between 240.dp and 220.dp?
2. Seems like these should be constants at the top of the file because you use them both twice.

2022-10-21 22:08 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeModel.kt
> +            }
add newline

2022-10-21 22:08 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +            val workerRequestId = SharedPrefFolder.App.DownloadRequestId.get(sharedPreferencesModel)
Make another function for all of this worker/downloading logic and call it from here.  It looks like it's all fairly well encapsulated

2022-10-21 22:08 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +                        NeevaScopePromoType.TRY_NEEVASCOPE -> {
Is this code basically the same as the other place except that you call `isLandscape = true`?  If so, can you refactor it out and call it from both places?

2022-10-24 21:31 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeTooltip.kt
> +            maxWidth = 240.dp
1. Based on [Figma](https://www.figma.com/file/SQpqqCk736DJWbXANK4K5w/Cheatsheet-%2F-NeevaScope?node-id=2317%3A14205), the content size, padding of the reddit tooltip and `Try NeevaScope!` tooltip are different.

> `Try NeevaScope` only has text with 180 width and 20 horizontal padding

> Reddit tooltip has text with 174 width, reddit icon with 32 width, 10 padding between them, and 12 horizontal padding

2022-10-26 18:33 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/sharedprefs/SharedPrefFolder.kt
> +            preferenceKey = "SHOW_TOOLTIP_COUNT",
`SHOW_NEEVASCOPE_TOOLTIP_COUNT`

2022-10-26 18:35 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeTooltip.kt
> +                showTooltip.value = false
Pull these two lines out into a lambda that gets called from here and on line 201?  Would make dismissal of the popup consistent in case you add other things that need to be done.

```
val dismissLambda = {
    showTooltip.value = false
    if (performPromoTransition != null) performPromoTransition()
}
```

2022-10-26 18:38 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserBottomToolbar.kt
> +        settingsDataModel.getToggleState(SettingsToggle.ENABLE_NEEVASCOPE_TOOLTIP).value
Guess you don't want to collect this State, right?  If you don't, then use instead
`getSettingsToggleValue`

2022-10-26 18:48 UTC, dan-alcantara-neeva requested changes

2022-10-26 18:48 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/BaseBrowserWrapper.kt
> +            if (settingsDataModel.getToggleState(SettingsToggle.ENABLE_NEEVASCOPE_TOOLTIP).value) {
Can avoid the return I think:

```
.map {
    if (settingsDataModel.getToggleState(SettingsToggle.ENABLE_NEEVASCOPE_TOOLTIP).value) {
        neevaScopeModel.updateUrl(it)
        neevaScopeModel.neevaScopeTooltipTypeFlow.value
    } else {
        null
    }
}
```

Otherwise, you could try:
```
return@map if (settingsDataModel.getToggleStateValue(SettingsToggle.ENABLE_NEEVASCOPE_TOOLTIP)) {
    neevaScopeModel.updateUrl(it)
    neevaScopeModel.neevaScopeTooltipTypeFlow.value
} else {
    null
}
```

2022-10-26 18:48 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        settingsDataModel.getToggleState(SettingsToggle.ENABLE_NEEVASCOPE_TOOLTIP).value
Is this reading the right shared pref?  Looks like you're downloading filters only if you're still showing the tooltips.

2022-10-26 18:58 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeModel.kt
> +    val urlFlow: StateFlow<Uri> = _urlFlow
newline

2022-10-26 18:58 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeModel.kt
> +    val promoCache: Map<Uri, RedditPromoState> get() = _promoCache
newline

2022-10-26 18:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeModel.kt
> +    val urlFlow: StateFlow<Uri> = _urlFlow
Also be consistent and use `get() = _urlFlow`?  Doesn't make a huge difference in this case because it's just exposing another field that doesn't change, but consistency is nice

2022-10-26 19:12 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/neevascope/NeevaScopeModelTest.kt
>      }
Can you add tests here for the new functions you're adding?

2022-10-27 18:07 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeModel.kt
> +                    SharedPrefFolder.App.NeevaScopeTooltipCount.get(sharedPreferencesModel) <= 0
Did this not fit in 100 chars?

2022-10-27 18:08 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        workManager.enqueue(OneTimeWorkRequestBuilder<BloomFilterDownloadWorker>().build())
Is this supposed to be here?  Looks like you're bypassing everything and just enqueuing the download.

2022-10-27 18:10 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/BaseBrowserWrapper.kt
> +        if (settingsDataModel.getSettingsToggleValue(SettingsToggle.ENABLE_NEEVASCOPE_TOOLTIP)) {
Why'd you move the code to here?  This only fires when the user switches tabs and not when the URL changes, so if the user navigates somewhere else on the same tab it won't fire.

2022-10-27 18:11 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        workManager.enqueue(OneTimeWorkRequestBuilder<BloomFilterDownloadWorker>().build())
Oops....I forgot to delete this

2022-10-27 18:28 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/BaseBrowserWrapper.kt
> +            if (settingsDataModel.getToggleState(SettingsToggle.ENABLE_NEEVASCOPE_TOOLTIP).value) {
You didn't actually need to store the flow in that case: you just need the app to do something whenever the active tab's URL changed.  You can do something like this:

```
init {
    coroutineScope.launch {
        activeTabModel.urlFlow.collectLatest {
            if (settingsDataModel.getToggleState(SettingsToggle.ENABLE_NEEVASCOPE_TOOLTIP).value) {
                neevaScopeModel.updateUrl(it)
                neevaScopeModel.neevaScopeTooltipTypeFlow.value
            }
        }
    }
}
```

2022-10-27 18:29 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/BaseBrowserWrapper.kt
> +        if (settingsDataModel.getSettingsToggleValue(SettingsToggle.ENABLE_NEEVASCOPE_TOOLTIP)) {
Saw your comment above; see if the code I posted works?

2022-10-28 18:28 UTC, dan-alcantara-neeva approved these changes

2022-10-28 20:27 UTC, merged