And/restyle settings
neevaco/neeva-android pull request #1075
Opened 2022-10-24 22:00 UTC by andjd

Updated Settings styling

* Changed section heading to use a line
    * Added "heavy" and no-text variants with previews
* Changed "ic_navigate_next" icon
* Changed font weight for headings in StackedText
* Hoisted modal state to top level in ClearBrowsingPane
    * Removed bespoke CLEAR_DATA_BUTTON SettingDataType and replaced it with a regular button
    * Added ability to define the buttonAction callback on SettingsRowData
* Added "isDangerousAction" and "isSuccessMessage" to SettingsRowData(currently used to color text red and teal)
* Removed SettingsButtonRow class and replaced its use with equivalent ClickableRow class.

I anticipate needing to update some screenshot tests.

## Checklists

### Pointers to help with review
* [Figma link](https://www.figma.com/file/D3pbLY6ZP5YtCjTYqsGOKO/Android-Design-System?node-id=1911%3A33669)

### How was this tested?
- [X] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [X ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

![image](https://user-images.githubusercontent.com/13681211/197636972-209bd852-5b0d-416f-b428-b312d8833746.png)
![image](https://user-images.githubusercontent.com/13681211/197637051-ebc9db4d-52ab-4abf-ac9a-5051ab41f900.png)
![image](https://user-images.githubusercontent.com/13681211/197637253-cf657e5a-0855-43bc-8cd1-ce4d5ffcc166.png)
![image](https://user-images.githubusercontent.com/13681211/197637275-9ab532f0-f699-4fcc-9ed5-094dbfce651d.png)

## Issues addressed
#941

2022-10-25 00:36 UTC, dan-alcantara-neeva commented
Huh.  Not sure why your CircleCI pipeline totally failed... @Kokobe/@yasminyin96  Do you remember if either of you had to do anything special on CircleCI's website before running tests?

2022-10-25 03:29 UTC, Kokobe commented
It's possible that Andrew set up the SSO incorrectly according to this: https://support.circleci.com/hc/en-us/articles/360043002793-Troubleshooting-CircleCI-Access-After-Enabling-Github-SSO

@andjd make sure you follow https://github.com/neevaco/neeva/wiki/Git-Setup 

Your SSH key settings should look something like this: 
<img width="1184" alt="Screen Shot 2022-10-24 at 8 28 32 PM" src="https://user-images.githubusercontent.com/20916043/197675719-af317700-9e15-40ef-a3da-0e04aeb669cb.png">

2022-10-25 03:33 UTC, Kokobe commented
According to that CircleCI support link, you might want to follow their steps and revoke the permissions and add the Neeva key again.

2022-10-25 17:43 UTC, dan-alcantara-neeva reviewed
Code seemed fine, but the screenshots in the PR didn't seem to register and the screenshot tests didn't finish running for some reason.  Try just running `scripts/pull-new-golden-screenshots.sh` locally using the emulator made with `scripts/create-emulator.sh` and then seeing if any diffs come out

2022-10-25 17:43 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/ClickableRow.kt
> +        endComposable = if (actionIconParams != null && actionIconParams.actionType != RowActionIconParams.ActionType.NONE) {
Maybe do this?

```
actionIconParams
    ?.takeUnless { it.actionType == RowActionIconParams.ActionType.NONE } 
    ?.let { { RowActionIconButton(it) } }
```

2022-10-25 20:04 UTC, andjd commented on app/src/main/java/com/neeva/app/settings/clearbrowsing/ClearBrowsingPane.kt
> +    SettingsPane(settingsController, ClearBrowsingPaneData(
Also fixed by ktlintFormat

2022-10-25 20:14 UTC, andjd commented on app/src/main/java/com/neeva/app/ui/widgets/ClickableRow.kt
> +        endComposable = if (actionIconParams != null && actionIconParams.actionType != RowActionIconParams.ActionType.NONE) {
Related Unrelated comment.

I tend to like importing enum values, so you can write this like:
`?.takeUnless { it.actionType == NONE }`

What's your thought here? it requires fighting the IDE a bit which is a downside.  It feels more readable to me, although that my be influenced by it being more like swift code.

2022-10-25 20:35 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/ClickableRow.kt
> +        endComposable = if (actionIconParams != null && actionIconParams.actionType != RowActionIconParams.ActionType.NONE) {
Depends on whether the enum type is clear from where it's being used... `NONE` seems a bit too generic in this case, but it still reads alright.  Will defer to you on that

2022-10-25 20:36 UTC, dan-alcantara-neeva commented
Screenshots in the PR description are still broken @andjd

2022-11-01 20:54 UTC, andjd reviewed
The last 4 commits were pulled in from main.

It is my habit to pull the latest version of main and git merge it into my feature branch.  This just ensures no merge conflicts.  Working on my previous codebase, it would not bring in these other commits. (I think because git merge will default to fast-forward if possible).

Looks like Github has a way to do this through their UI that works fine, so 👍

2022-11-01 22:30 UTC, Kokobe commented
Hey Andrew! For the PR description, make sure to set the screenshot image height to 300 or something. Otherwise it makes the whole thing less readable

2022-11-02 00:21 UTC, dan-alcantara-neeva commented
Looks like a bunch of tests are failing because the text on the feedback pages changed.  Also one of the tests doesn't apply anymore because the Welcome Center link is going away

2022-11-02 00:22 UTC, dan-alcantara-neeva commented
Padding on the "Share screenshot" part of Feedback also seems to have gone to 0 instead of whatever it needs to be

2022-11-02 00:24 UTC, Kokobe reviewed
Initial comments

2022-11-02 00:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/FullScreenDialogTopBar.kt
> +    button: Painter? = null,
Rename to `buttonPainter`

2022-11-02 00:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/FullScreenDialogTopBar.kt
> +                            enabled = isButtonEnabled
Nit: I think these can fit on one line + would look cleaner

2022-11-02 00:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/FullScreenDialogTopBar.kt
> +                        enabled = isButtonEnabled
Nit: I think these can fit on one line + would look cleaner

2022-11-02 00:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/FullScreenDialogTopBar.kt
> +                                maxLines = 1
Nit: I think these can fit on one line + would look cleaner

2022-11-02 00:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/SectionHeader.kt
> +
remove new line

2022-11-02 00:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/SectionHeader.kt
> +
Remove new line

2022-11-02 00:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/SectionHeader.kt
> +        ).padding(vertical = Dimensions.PADDING_SMALL)
Reformat to:
```
        modifier = Modifier
            .background(color = MaterialTheme.colorScheme.surface)
            .padding(vertical = Dimensions.PADDING_SMALL)
```

2022-11-02 00:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/SectionHeader.kt
> +@Preview("SectionHeader, LTR, 1x", locale = "en")
Change name to distinguish from your HeavySectionHeader Preview.

Also make sure to not use `SectionHeader` as the name for every one of the previews. It's an important practice so when in future PRs you can distinguish the different previews and what they are supposed to do. We usually screenshot the previews rendered and put them in the PR description.

2022-11-02 00:36 UTC, Kokobe reviewed
Second round of comments

2022-11-02 00:36 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/widgets/ClickableRow.kt
> +            ?.takeUnless { it.actionType == NONE }
Just use `takeIf { it.actionType != NONE }` 

The double negative can be confusing for future readers.

2022-11-02 00:36 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> + *
remove line 31-32

2022-11-02 00:36 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> +class ClickableStringBuilder(val baseStyle: SpanStyle, val linkStyle: SpanStyle) {
remove val for baseStyle because it is never used as a property

2022-11-02 00:36 UTC, Kokobe commented on app/src/main/java/com/neeva/app/feedback/FeedbackView.kt
> +                    PartiallyClickableText() {
() is not necessary here

2022-11-02 20:52 UTC, andjd commented on app/src/main/java/com/neeva/app/ui/widgets/ClickableRow.kt
> +            ?.takeUnless { it.actionType == NONE }
Not to nit, but the existing formulation isn't a double negative.  `it.actionType != none` is the negative formulation of that part of the expression.

But your point that `-if` is typically a lot easier to understand than `-unless` is noted.

2022-11-03 17:04 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +        // If the user isn't in the tab switcher when the app is brought back to the foreground,
You should be rebasing on top on main when you upload PRs to avoid mixing up the PRs getting reviewed

2022-11-03 23:15 UTC, dan-alcantara-neeva commented on app/src/main/res/values/strings.xml
> +    <string name="word_separator">\u0020</string>
Trying to concatenate words with spaces versus full sentences will mess up translations; we shouldn't be doing this

2022-11-03 23:56 UTC, dan-alcantara-neeva requested changes

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/res/values-en-rGB/strings.xml
> +    <string name="submit_feedback_screenshot">Share screenshot</string>
Why'd you change the key name?

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/feedback/FeedbackViewTest.kt
>              // Not super happy with this test because is actively loads the real Neeva website.
Can remove line 74 of the comment now; our instrumentation tests now hit up a web server running on the phone to prevent pinging the real website.

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/FullScreenDialogTopBar.kt
> +            if (onButtonPressed != null) {
Early exit if `onButtonPressed == null`, or use a when clause?

```
when {
    onButtonPressed == null -> return@whatever_the_lambda_is

    buttonPainter != null -> {
        ...
    }

    buttonTitle != null -> {
        ...
    }
}

```

Might be a little clearer.  Otherwise, make line 67 an `else if` instead of nesting the if into it.

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/FullScreenDialogTopBar.kt
> +@Preview("FullScreenDialogTopBar, 1x font scale", locale = "en")
Use `@PortraitPreviews` so that you don't have to manually define all of these.  We haven't fully converted all the other @Preview callsites yet.

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/clearbrowsing/ClearBrowsingPaneData.kt
> +            timeClearingOptionToggles + if (dataCleared) {
Is there a mock for this?  Seems like you should be throwing a temporary snackbar up instead of appending a row.

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/sharedcomposables/SettingsRow.kt
> +                isActionDangerous = rowData.isDangerousAction,
Keep the word ordering consistent?  `isActionDangerous` versus `isDangerousAction`

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/SectionHeader.kt
> +@Preview("SectionHeader_Heavy, LTR, 1x", locale = "en")
`@PortraitPreviews`

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/ClickableRow.kt
> +    onTapAction: (() -> Unit)? = null,
Add a `kdoc` to the function explaining the priority for the tap action

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/ClickableRow.kt
> +        onTapRowContentDescription = actionIconParams?.contentDescription,
Little weird that the `contentDescription` will be pulled from the `actionIconParams` even if you ignore its action.

WDYT about making another version of this composable that just has the old signature that unwraps the `RowActionIconParams`?  Would mean that you could pass `actionIconParams?.onTapAction` as `onTapAction`, explicitly pass a `contentDescription`, and explicitly pass in what the `endComposable` should be.

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/clearbrowsing/ClearBrowsingPane.kt
> +        ClearBrowsingDialog(
Is there a video attached to the PR showing the altered flows?

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/feedback/FeedbackView.kt
> +@SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
What's the reasoning behind suppressing this lint warning?  This particular one says that you're not using the padding that is being passed down by the `Scaffold`, which is necessary for avoiding content overlapping.   It looks like it's being used on line 127, though.

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> +    // Applies a sane defaults (underline and highlighted color)
`a sane defaults` -> `reasonable defaults`

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> +    defaultSeparator: String? = stringResource(id = R.string.word_separator),
We shouldn't be separating individual words when building out a string or translations will get screwed up.  Strings should be properly templatized so the translator can grok the whole thing and rearrange its parts if needed.

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> +        const val CLICKABLE = "Clickable"
`private const val ANNOTATION`?

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> +    fun toClickableText(modifier: Modifier) {
Should probably call this `build()` to match other `Builder` patterns

2022-11-03 23:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> +        val tag = (text to clickActions.size).hashCode().toString(32)
Took a bit to understand what you were doing here with these tags.  Given that you're passing in a string anyway, could you just use that as the key instead of hashing your index?  Not sure why you'd append the same strings with different actions.

2022-11-04 15:28 UTC, andjd commented on app/src/main/res/values-en-rGB/strings.xml
> +    <string name="submit_feedback_screenshot">Share screenshot</string>
String-length constraints on the linter. It was either shorten the resource name or go to an awkward multi-line function call in the code. 

This style of resource naming seems a little overly wordy to me, although I understand that avoiding conflicts is an important counter consideration.

2022-11-04 15:37 UTC, andjd commented on app/src/main/java/com/neeva/app/ui/FullScreenDialogTopBar.kt
> +            if (onButtonPressed != null) {
Early return is not possible here, since this is an expression in an argument to a function.  Personally, I think if ... else if is cleaner here for a few reasons.

First, order matters. since buttonTitle should still be set when there's the painter because it provides context descriptions.  This is likely to be less clear when we use a when block.

Second, if we used when, we'd need an else condition, which wouldn't be helpful. (Although maybe we'd want to throw if we get a button with a click action and no painter or title, since that would be confusing ...)

2022-11-04 16:52 UTC, andjd commented on app/src/main/java/com/neeva/app/settings/clearbrowsing/ClearBrowsingPaneData.kt
> +            timeClearingOptionToggles + if (dataCleared) {
The change here is because the timeClearingOptionToggles and the action button are one settings group.  They were previously put in two separate SettingsGroupData objects, but that added a thin line between them not present on the mockups.

Changing the button text to the green success message matched the existing app behavior, and the new mockups do not cover this situation.

I can change it to a snackbar if that's preferable.

2022-11-04 17:16 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/FullScreenDialogTopBar.kt
> +            if (onButtonPressed != null) {
`IllegalArgumentException`, maybe?  Kotlin `assert`s are a little odd in that they fire for both debug and release builds, but I can't imagine this check being overly painful if it's only fired when it gets composed.

2022-11-04 17:17 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/clearbrowsing/ClearBrowsingPaneData.kt
> +            timeClearingOptionToggles + if (dataCleared) {
Hrm, could you poke UX about the right behavior here?  We're already throwing up snackbars for when the user does something, so that pattern already exists.

2022-11-04 18:26 UTC, andjd commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> +    fun toClickableText(modifier: Modifier) {
I was mimicing the AnnotatedString.Builder here, which uses `toAnnotatedString()` and not `build()`  But I don't have a preference here.

I should note that unlike a pure Builder, this doesn't return an object, it creates a Composable node  🤷

2022-11-04 18:29 UTC, andjd commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> +        val tag = (text to clickActions.size).hashCode().toString(32)
This is an idiot proofing step.  It just ensures correct behavior in case you have the same highlighted text in multiple places.  E.g. "click **HERE** to read our terms, to win $10000 click **HERE**"

2022-11-04 18:57 UTC, andjd commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> +        val tag = (text to clickActions.size).hashCode().toString(32)
Extracted this to a private function and added a comment.

2022-11-07 19:30 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/widgets/ClickableRow.kt
> +            ?.takeUnless { it.actionType == NONE }
You're right haha, I should've also said my comment was a nit-pick 🙂

2022-11-07 20:17 UTC, Kokobe commented on app/src/main/java/com/neeva/app/feedback/FeedbackView.kt
> +@SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
What is the reason behind this? I tried deleting it and the build ran fine without it 🙂

2022-11-07 21:24 UTC, Kokobe reviewed
There are a lot of comments from @dan-alcantara-neeva that are not addressed, you should act on them or reply to them (this helps with documentation and tracking code down). 

Also you can resolve my styling comments if you did them

2022-11-07 21:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/SectionHeader.kt
> +@Preview("SectionHeader_Heavy, LTR, 1x", locale = "en")
Use PortraitPreviews!

2022-11-09 19:49 UTC, andjd commented on app/src/main/java/com/neeva/app/ui/widgets/ClickableRow.kt
> +        onTapRowContentDescription = actionIconParams?.contentDescription,
Fixed it and refactored the handful of uses of the old function to use the new, explicit, signature.

2022-11-09 22:03 UTC, andjd commented on app/src/main/res/values/strings.xml
> +    <string name="word_separator">\u0020</string>
Removed word_separator

2022-11-10 18:30 UTC, Kokobe requested changes
Mostly style nits. Make sure to do a quick scan through your PR before sending it on to review next time 🙂

2022-11-10 18:30 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/FullScreenDialogTopBar.kt
> +    onButtonPressed = null,
Make sure to go through your PR and remove the extra commas at the end for all the other places

2022-11-10 18:30 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/FullScreenDialogTopBar.kt
> +                    buttonTitle != null -> {
combine lines 111 and 112

2022-11-10 18:30 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/widgets/ClickableRow.kt
> + * TODO
Remove TODO?

2022-11-10 18:30 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> +     * Will apply the linkStyle if provided
Combine 103-104 to 1 line. Also use complete sentences in your kdocs in this file so its consistent with the codebase

2022-11-10 18:30 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/widgets/RowActionIcon.kt
> +fun RowActionIconButton(
Why did you recreate the same function above?

If you want to use it correctly, call the function like this:
`RowActionIconButton( RowActionIconParams(...) )`

2022-11-10 18:30 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +    <string name="sentence_separator">\u0020</string>
This doesn't need to be translated, so you should either remove this or put it in the `donottranslate.xml` file

2022-11-14 19:39 UTC, andjd commented on app/src/androidTest/java/com/neeva/app/feedback/FeedbackViewTest.kt
> -            // Not super happy with this test because is actively loads the real Neeva website.
No. I deleted this comment at Dan's suggestion.

2022-11-14 19:43 UTC, andjd commented on app/src/main/java/com/neeva/app/cardgrid/archived/ArchivedTabGrid.kt
> +                onTapAction = onShowArchiveAfterOptionDialog,
We can discuss more broadly, but I'm generally in favor of trailing commas.  The reason for this is that adding an argument keeps diffs simpler, as you don't have an extra changed line just to add a comma.

2022-11-14 19:44 UTC, andjd commented on app/src/main/java/com/neeva/app/cardgrid/archived/ArchivedTabGrid.kt
> +                onTapAction = onDeleteAllArchivedTabs,
See above.

2022-11-14 19:44 UTC, Kokobe commented on app/src/main/java/com/neeva/app/cardgrid/archived/ArchivedTabGrid.kt
> +                onTapAction = onShowArchiveAfterOptionDialog,
Good point, @dan-alcantara-neeva WDYT?

2022-11-14 19:53 UTC, andjd commented on app/src/main/res/values/strings.xml
> +    <string name="sentence_separator">\u0020</string>
"All languages use a space between sentences (or even words)" is one of those false assumptions about human language. Some south-east asian and Arabic scripts don't use spaces.

The DoNotTranslate list is more for branding and other words that we don't _want_ to translate.

2022-11-14 20:16 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +    <string name="sentence_separator">\u0020</string>
Ack!

2022-11-14 20:18 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/cardgrid/archived/ArchivedTabGrid.kt
> +                onTapAction = onShowArchiveAfterOptionDialog,
No strong preference here.  I've wanted to keep us aligned to the Kotlin style guide, which currently encourages trailing commas at the declaration site and leaves it up to our discretion for the callsite:
https://kotlinlang.org/docs/coding-conventions.html#trailing-commas

Andrew's reasoning seems solid, though, so we can try to adhere to that.

2022-11-14 20:19 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/feedback/FeedbackViewTest.kt
> +                click(position = percentOffset(x = 0.95f, y = 0.25f))
I suggested doing this because I couldn't think of a better way to do it (following a similar StackOverflow answer).  Tests will generally have to be updated whenever anything changes, anyway, so the added fragility of this doesn't seem too bad.

2022-11-14 21:17 UTC, dan-alcantara-neeva commented on app/src/main/res/values/strings.xml
> +    <string name="sentence_separator">\u0020</string>
+1 to both points.  `donottranslate.xml` is a convenience file so that we can group all the untranslatable strings in one place instead of interspersing `translatable=false` throughout the `strings.xml` file.  Ideally, we should have most of the debugging strings in there, but it looks like two crept in (`space_enable_invite` and `settings_neevascope`).

2022-11-14 21:22 UTC, andjd commented on app/src/main/java/com/neeva/app/ui/widgets/RowActionIcon.kt
> +fun RowActionIconButton(
I didn't refactor it entirely because that would have been beyond scope, but the way we are using RowActionIconParams is a little bit of a code smell.  

First, we were using it for things beyond the RowActionIconButton, which is problematic since it is somewhat unexpected, and couples code together that doesn't need to be.  To support this, we had added an ActionType of None so that we could use some elements of the RowActionIconParams ... when we didn't want to show an icon. I got rid of all those uses.  

Secondly, it leads to unnecessary coupling.  It is useful in the first place since it lets you pass a set of parameters down several levels in the view hierarchy, but then the elements that want to show an IconButton become coupled to that implementation since they pass the RowActionIconParams through them.  A more flexible architecture will accept a Composable function (e.g. `endComposable: @Composable () -> Unit`) instead of the `rowActionIconParams`, since then the Composable can be anything.  It also prevents the coupling we were seeing where the middle component, instead of just passing on the params, read them and applied them in unexpected ways.

Finally, it's nicer to have a signature where you supply the arguments directly instead of to a data class. It just makes the code a little simpler and more direct.  And, if you're not passing the object down through other components, you don't need it.

2022-11-14 21:25 UTC, andjd commented on app/src/main/res/values/strings.xml
> +    <string name="sentence_separator">\u0020</string>
"All languages use a single space character to separate sentences" is one of those assumptions about text that doesn't apply to every language.  I'm pretty sure it's true for languages we're targeting now, but doesn't apply to some Arabic scripts and south-east Asian languages.

2022-11-14 21:27 UTC, andjd commented on app/src/main/res/values/strings.xml
> +    <string name="sentence_separator">\u0020</string>
doNotTranslate applies to features we don't _want_ to localize, typically branding.  

You'll note that, ironically, there are a bunch of Hebrew translations of strings in the doNotTranslate file...

2022-11-14 21:28 UTC, dan-alcantara-neeva commented on app/src/main/res/values/strings.xml
> +    <string name="sentence_separator">\u0020</string>
Not really ironic.  We needed those fake strings for `@Preview`s so that we could make sure that they looked fine in RTL.

2022-11-14 21:32 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/widgets/RowActionIcon.kt
> +fun RowActionIconButton(
Sounds good... will you refactor this in the next PR?

2022-11-14 23:12 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/sharedcomposables/SettingsRow.kt
> +                        MaterialTheme.colorScheme.tertiary
Given that we're supposed to be using ephemeral snackbars, is this conditional (and the associated `isSuccessMessage` still necessary?

2022-11-14 23:12 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> +     * @param text
This isn't actually a param of your function

2022-11-14 23:12 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/PartiallyClickableText.kt
> + * callback lambda.  ClickableSpan can take either unstlyed [Text], which will have the linkStyle
You've misspelled `unstlyed -> unstyled` in a few places in this kdoc

2022-11-15 20:07 UTC, andjd commented on app/src/androidTest/java/com/neeva/app/feedback/FeedbackViewTest.kt
> +                click(position = percentOffset(x = 0.95f, y = 0.25f))
👍

Agree that there _should_ be a better way. But a quick search did not find one 😢

2022-11-15 20:11 UTC, andjd commented on app/src/main/java/com/neeva/app/settings/sharedcomposables/SettingsRow.kt
> +                    },
And un-needed if-else, branch too...

2022-11-17 16:12 UTC, andjd commented on app/src/main/java/com/neeva/app/ui/SectionHeader.kt
> +            thickness = if (heavy) 8.dp else 1.dp
Switched to use DeafultDivider or HeavyDivider here

2022-11-17 20:48 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/FullScreenDialogTopBar.kt
> +                    buttonTitle != null -> {
@andjd Missed a comment I think

2022-11-17 20:58 UTC, dan-alcantara-neeva reviewed
One comment, otherwise seems good to go.

2022-11-17 20:58 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/widgets/RowActionIcon.kt
> -            ActionType.REFINE -> context.getString(R.string.refine)
Can you make sure that the places that use these actions have their content descriptions set correctly now that you're deleting this?

2022-11-18 21:45 UTC, andjd commented
Readded a few content description cues, and found two where existing behavior doesn't have a content description ... Don't know if we want that.

2022-11-18 23:14 UTC, dan-alcantara-neeva commented
> Readded a few content description cues, and found two where existing behavior doesn't have a content description ... Don't know if we want that.

Just want to make sure that we've got parity before your PR.  We have a bunch of other a11y ones we should probably look into, already...

2022-11-18 23:14 UTC, dan-alcantara-neeva approved these changes

2022-11-21 16:40 UTC, Kokobe approved these changes

2022-11-21 21:27 UTC, merged