Add ad block onboarding screen + enable ad block by default
neevaco/neeva-android pull request #1079
Opened 2022-10-25 23:04 UTC by chung-lai

## Checklists

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

2022-10-25 23:19 UTC, chung-lai commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterPopoverModel.kt
> +    val onboardingPopoverVisible: MutableState<Boolean>
@dan-alcantara-neeva, doesn't feel right adding another popover visible property here but the new ad block onboarding popover pretty much use everything in this model. Any suggestion on how I should add this property?

2022-10-26 20:51 UTC, Kokobe commented on app/src/main/java/com/neeva/app/zeroquery/RegularProfileZeroQuery.kt
> +                        // border = BorderStroke(3.dp, MaterialTheme.colorScheme.primary),
Remove this comment?

2022-10-26 20:51 UTC, Kokobe commented on app/src/main/java/com/neeva/app/zeroquery/RegularProfileZeroQuery.kt
> +                            // ConstraintLayout {
remove comment

2022-10-26 21:01 UTC, Kokobe commented
According to https://neevaco.slack.com/archives/C01QW9Z7P3P/p1666747584970869 we should change "Cool. Thanks." to "Cool, thanks!"

2022-10-26 21:02 UTC, Kokobe commented
Respective iOS PR: https://github.com/neevaco/neeva-ios/pull/4536

2022-10-26 21:10 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +    // TODO(kobec): the offset does not work in landscape
Did you copy paste the same function from `ContentFilterPopover.kt`?

2022-10-26 21:13 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +    // TODO(kobec): the offset does not work in landscape
You can generalize that function in `ContentFilterPopover.kt` to take 
```
content: @Composable () -> Unit
```
as  a parameter. Then you can pass in a custom content like so:
```
// for ContentFilterPopover: 
ContentFilterPopover(
...,
content = {
  ContentFilterPopoverContent(
            contentFilterPopoverModel = contentFilterPopoverModel,
            modifier = modifier
        )
}
)

// for ContentFilterOnboardingPopover, reusing the same function ContentFilterPopover() but using a different content:
ContentFilterPopover(
...,
content = {
  ContentFilterOnboardingContent(
            contentFilterPopoverModel = contentFilterPopoverModel,
            modifier = modifier
        )
}
```

2022-10-26 21:16 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +                    }
Since you don't use the variable `iconModifier` anywhere else, you should just remove the variable and use this stuff on line 163

2022-10-26 21:18 UTC, Kokobe commented
Could you also link the Figma to where the design is?

2022-10-26 21:18 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +                        imageDescription = "remove",
Is this necessary?

2022-10-26 21:23 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +                val horizontalMiddleGuideline = createGuidelineFromStart(0.72f)
Did you get this 0.72f from com/neeva/app/contentfilter/ui/icon/TrackingProtectionButton.kt? 

Is the badge in the image below the same badge? 
<img width="166" alt="Screen Shot 2022-10-26 at 2 21 48 PM" src="https://user-images.githubusercontent.com/20916043/198140788-d1ee46fc-a1c6-4dcf-9dd2-61472c15c1bf.png">

It's weird that the code is the same but the badge number icon is in a different spot as 
<img width="22" alt="Screen Shot 2022-10-26 at 2 23 01 PM" src="https://user-images.githubusercontent.com/20916043/198141008-19346b71-11f7-4eed-9a6b-0e1b03a4fbed.png">

2022-10-26 21:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/zeroquery/RegularProfileZeroQuery.kt
> +                                modifier = iconModifier
`iconModifier` variable is only being used once, remove the variable and put the Modifier here

2022-10-26 21:35 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterPopoverModel.kt
> +        onboardingPopoverVisible.value = true
make sure that the other Popover is not visible too?

2022-10-26 21:36 UTC, Kokobe requested changes
Lmk if you need more clarification or need any help from me!

2022-10-26 21:50 UTC, chung-lai commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +                val horizontalMiddleGuideline = createGuidelineFromStart(0.72f)
yea, got the number from TrackingProtectionButton, thought it's for horizontal alignment. The vertical alignment is defined as `verticalMiddleGuideline`.

2022-10-26 21:51 UTC, chung-lai commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +                        imageDescription = "remove",
imageDescription? Thought it's for accessibility?

2022-10-26 22:31 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +                val horizontalMiddleGuideline = createGuidelineFromStart(0.72f)
Ah got it!

2022-10-26 22:32 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +                        imageDescription = "remove",
Ah so is there value in adding an `imageDescription` here? If yes, we should add a string in strings.xml and use it so it can get properly translated

2022-10-27 00:45 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +                        imageDescription = "remove",
But the answer is probably no right? Since its not a button

2022-10-27 04:15 UTC, chung-lai commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +                        imageDescription = "remove",
that's a good question, not entirely sure how accessibility work on image. @dan-alcantara-neeva, any insight?

2022-10-27 18:25 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +                        imageDescription = "remove",
Image descriptions get read out to the user during Talkback, so they'll need to be properly translated instead of hard-coded like this.  Can you double-check and make sure you're not landing any untranslatable strings in your PR?

2022-10-27 18:36 UTC, chung-lai commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +                        imageDescription = "remove",
sounds good. Will double check the strings.

2022-10-27 19:57 UTC, Kokobe commented
Are you sure the number badge is in the right spot? (just looking at the screenshots in the description)

It looks like it is more at the top right:
<img width="353" alt="Screen Shot 2022-10-27 at 12 56 57 PM" src="https://user-images.githubusercontent.com/20916043/198386027-8b84d5b6-efec-4754-8f0e-b8ebfe544f2e.png">

2022-10-27 20:18 UTC, chung-lai commented
> Are you sure the number badge is in the right spot? (just looking at the screenshots in the description)
> 
> It looks like it is more at the top right: <img alt="Screen Shot 2022-10-27 at 12 56 57 PM" width="353" src="https://user-images.githubusercontent.com/20916043/198386027-8b84d5b6-efec-4754-8f0e-b8ebfe544f2e.png">

ah good catch, the mock was updated to be more Android like :) Will update the screenshots.

2022-10-27 20:26 UTC, chung-lai commented
@Kokobe updated the screenshots, thanks!

2022-10-27 21:04 UTC, Kokobe requested changes
Going on a walk, but the `first_run_ad_block_dismiss` string should say "Cool, thanks!" not "Cool. Thanks!"

2022-10-27 21:07 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +    val sharedPreference = LocalSharedPreferencesModel.current
nit: name this `sharedPreferenceModel`

2022-10-27 23:33 UTC, Kokobe requested changes

2022-10-27 23:35 UTC, chung-lai commented on app/src/main/java/com/neeva/app/settings/SettingsDataModel.kt
> +                ContentFilterModel.BlockingStrength.TRACKER_REQUEST.name
@Kokobe, thinking to enable ad block only for new users. Will this change affect existing users?

2022-10-27 23:35 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +                        contentFilterPopoverModel.openOnboardingPopover()
Is this necessary? This function simply changes the MutableState values, but to get to line 228, those values have to already be set to the ones this function is setting them to, right?

2022-10-27 23:38 UTC, chung-lai commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +private fun ContentFilterOnboardingPopoverContent(
yes, looking into it :)

2022-10-27 23:38 UTC, Kokobe commented on app/src/main/java/com/neeva/app/settings/SettingsDataModel.kt
> +                ContentFilterModel.BlockingStrength.TRACKER_REQUEST.name
Great callout, this shouldn't affect existing users because you are only changing the default value parameter.

2022-10-27 23:40 UTC, chung-lai commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +                if (contentFilterPopoverModel.cookieNoticeBlocked.collectAsState().value ||
when we open the onboarding pop over, it will dismiss the existing shield stats pop over

2022-10-27 23:42 UTC, chung-lai commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +                        contentFilterPopoverModel.openOnboardingPopover()
This is required because you can disable tracking protection on the onboarding popover which both `easyListRuleBlocked` and `cookieNoticeBlocked` will become `false` and dismiss the screen if we don't set the `shouldShowOnboarding`

2022-10-28 00:00 UTC, Kokobe commented on app/src/main/java/com/neeva/app/settings/SettingsDataModel.kt
> +                ContentFilterModel.BlockingStrength.TRACKER_REQUEST.name
Nevermind, in an offline convo we saw that `getSharedPrefValue` does not set any values. So if a user never toggles a setting to `set` the preference, their value of the toggle won't be saved if this was pushed out. 

@dan-alcantara-neeva @andjd correct me if I'm wrong

2022-10-28 00:04 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/SettingsDataModel.kt
> +                ContentFilterModel.BlockingStrength.TRACKER_REQUEST.name
Yeah, `getSharedPrefValue` just returns the default value if the user has never tried setting it before.  If you change the default value, then it'll change the value for the people who haven't seen it before.

2022-10-28 00:21 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +                        contentFilterPopoverModel.openOnboardingPopover()
I'm still confused lol...

Line 228 would never run if 
`easyListRuleBlocked` = false
`cookieNoticeBlocked` = false
and `shouldShowOnboarding` = false

The thing that would let it run is if any of those are true, and `shouldShowOnboarding` will be true only when `openOnboardingPopover()` is called...

I think you need to move where you call this function `openOnboardingPopover()`

2022-10-28 00:22 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +                        contentFilterPopoverModel.openOnboardingPopover()
When do we show the OnboardingPopover? I can help point you where in the code to do that

2022-10-28 00:23 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +                if (contentFilterPopoverModel.cookieNoticeBlocked.collectAsState().value ||
awesome

2022-10-28 19:32 UTC, chung-lai commented
@hwiatneeva, added some screenshots for dark mode. You can find them in `Files`. Could you see if everything looks good to you? Thanks!

2022-10-28 19:51 UTC, chung-lai commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +                        contentFilterPopoverModel.openOnboardingPopover()
resolved this offline. thanks Kobe!

2022-10-28 19:52 UTC, chung-lai commented on app/src/main/java/com/neeva/app/settings/SettingsDataModel.kt
> +                ContentFilterModel.BlockingStrength.TRACKER_REQUEST.name
In an offline conversation, we will opt new users into strict mode during first run flow until we figure out how we should persist default values.

2022-10-28 20:13 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +}
newline

2022-10-28 20:14 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +            .widthIn(14.dp),
Is this `widthIn` necessary?  What's the name of the parameter you're passing in?  `widthIn` should be expecting two values (min and max)

2022-10-28 20:14 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/contentfilter/ui/icon/NumberBadge.kt
> +enum class BadgeSize(
Do these values work for previews with 2x font size?

2022-10-28 20:15 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +private val previewContentFilterCookieNoticeOnboardingPopoverModel =
make this lazy so that we're not creating it unless we're actually showing a preview

2022-10-28 20:15 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +private val previewContentFilterAdBlockOnboardingPopoverModel = PreviewContentFilterPopoverModel(
Ditto: make this using `lazy { }`

2022-10-28 20:15 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +@Composable
Can you add to see what it would look like with bigger font? It looks like the badge dimensions are hard coded

```
@Preview("ContentFilterDisableOnboardingContent 1x font scale", locale = "en")
@Preview("ContentFilterDisableOnboardingContent 2x font scale", locale = "en", fontScale = 2.0f)
@Preview("ContentFilterDisableOnboardingContent RTL, 1x font scale", locale = "he")
```

2022-10-28 20:15 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +@Composable
Remember to add that screenshot to the PR description!

2022-10-28 20:19 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +            if (contentFilterPopoverModel.cookieNoticeBlocked.collectAsState().value ||
Let's set a time on Monday to fix this, @dan-alcantara-neeva  pointed out we should make separate composable because whenever you call collectAsState() it redraws the whole `BrowserToolbar`. 

We can also pipe this into `BrowserToolBarModel` and expose showOnboardingPopover as a flow to the new popover composable we're going to make. 

Also 
```
val showAdBlockOnboarding = SharedPrefFolder.FirstRun.showAdBlockOnboarding
                        .getFlow(sharedPreference).collectAsState()
```
Can be included in the if() you have

2022-10-28 20:55 UTC, chung-lai commented on app/src/main/java/com/neeva/app/contentfilter/ui/icon/NumberBadge.kt
> +enum class BadgeSize(
I assume this is working or we want it resize too?

<img width="286" alt="Screen Shot 2022-10-28 at 1 55 16 PM" src="https://user-images.githubusercontent.com/87332578/198730804-44b300ea-696f-4c1e-9748-c4a60c5bd993.png">
<img width="269" alt="Screen Shot 2022-10-28 at 1 55 00 PM" src="https://user-images.githubusercontent.com/87332578/198730808-fd908d87-b134-4881-9e54-2b359a1120ce.png">

2022-10-28 20:56 UTC, chung-lai commented on app/src/main/java/com/neeva/app/contentfilter/ui/icon/NumberBadge.kt
> +enum class BadgeSize(
think @Kokobe has the same comment

2022-10-28 20:56 UTC, hwiatneeva commented
Thanks @chung-lai!

All looking good, with the following tweaks from my mock bugs & changes of mind: 

1. zero query banner:  let's use the color `on-primary-container` for both icon and all text
2. popover:  'Site appears...', let's bump it up to `body/medium` instead of 'small'
3. popover text colors:  heading to be `on-surface`, 'Neeva Shield' to be `on-surface`, and the 'Site appears..' to be `on-surface variant`
4. check and minus on shield: let's make the border color to match the bg `on-surface`
5. dark mode steady state shield counter text color: low contrast -- let's match the dark blue color, which is used for the button label
<img width="287" alt="image" src="https://user-images.githubusercontent.com/91506909/198730871-0b1a6b13-279c-4222-beea-71d8a92171a7.png">
<img width="225" alt="image" src="https://user-images.githubusercontent.com/91506909/198730895-dcdee684-794e-410c-91b1-c18d72e5484b.png">

2022-10-28 20:56 UTC, chung-lai commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +            .widthIn(14.dp),
doesn't look it's necessary. 🤔

2022-10-28 21:20 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterOnboardingPopover.kt
> +@Composable
@PortraitPreviews should do that for you: it's an annotation that adds more annotations (like the ones you listed)

2022-10-28 21:20 UTC, chung-lai commented
@dan-alcantara-neeva @Kokobe, let me get Hwi's feedback in and update preview to the PR description

2022-10-28 21:37 UTC, chung-lai commented
> Thanks @chung-lai!
> 
> All looking good, with the following tweaks from my mock bugs & changes of mind:
> 
> 1. zero query banner:  current blue is too bright, let's use the darker color `on-primary-container` for both icon and all text
> 2. popover:  'Site appears...', let's bump it up to `body/medium` instead of 'small'
> 3. popover text colors:  heading to be `on-surface`, 'Neeva Shield' to be `on-surface`, and the 'Site appears..' to be `on-surface variant`
> 4. check and minus on shield: let's make the border color to match the bg `on-surface` so it blends in better.
> 5. dark mode steady state shield counter text color: low contrast -- let's match the dark blue color, which is used for the button label
> 
> <img alt="image" width="287" src="https://user-images.githubusercontent.com/91506909/198730871-0b1a6b13-279c-4222-beea-71d8a92171a7.png">
> 
> <img alt="image" width="225" src="https://user-images.githubusercontent.com/91506909/198730895-dcdee684-794e-410c-91b1-c18d72e5484b.png">

Thanks @hwiatneeva. For the "Site appears..." text, it shares the same component as the Stats popover. So it will changes both places. That's ok with you?

<img width="361" alt="Screen Shot 2022-10-28 at 2 36 49 PM" src="https://user-images.githubusercontent.com/87332578/198737049-ef1d2e90-733a-4ce5-a90e-01d550f017da.png">

2022-10-28 21:59 UTC, dan-alcantara-neeva commented
If you're changing the toggle text size, you might collide with @andjd 's PR because (I think) he's also adjusted the font for those

2022-10-31 22:54 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +                            isLandscape = true
Is this from the rebase? It's weird this is part of the diff

2022-10-31 23:00 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +    val showRedditDot = remember { mutableStateOf(false) }
This change is suspicious too

2022-11-01 05:07 UTC, chung-lai commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +                            isLandscape = true
Think you are looking into the commit directly, you don't see any diff if you look at files. It's from resolving merge conflict so it should be all good.

2022-11-01 05:07 UTC, chung-lai commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserToolbar.kt
> +    val showRedditDot = remember { mutableStateOf(false) }
Think you are looking into the commit directly, you don't see any diff if you look at files. It's from resolving merge conflict so it should be all good.

2022-11-01 17:58 UTC, Kokobe approved these changes

2022-11-01 20:51 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterPopoverModel.kt
> +        SharedPrefFolder.FirstRun.didShowAdBlockOnboarding.set(sharedPreferenceModel, true)
Since the default to `didShowAdBlockOnboarding` is true, you're right that this makes it so that existing users won't see this.

However, for **new users**, they will never see this (unless they call `setAdBlockOnboardingPreference()`)

2022-11-01 20:53 UTC, chung-lai commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterPopoverModel.kt
> +        SharedPrefFolder.FirstRun.didShowAdBlockOnboarding.set(sharedPreferenceModel, true)
yes, **new users** will go through the first run flow and that will call `setAdBlocknboardingPreference()`

2022-11-01 20:55 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +    fun setAdBlockOnboardingPreference() {
I would rename this function or add a parameter to set the value to. The name is a bit misleading haha

2022-11-01 20:56 UTC, Kokobe commented on app/src/main/java/com/neeva/app/contentfilter/ui/popover/ContentFilterPopoverModel.kt
> +        SharedPrefFolder.FirstRun.didShowAdBlockOnboarding.set(sharedPreferenceModel, true)
Cool, thanks for clarifying! 🙂

2022-11-01 20:56 UTC, Kokobe approved these changes
lgtm % the function rename comment

2022-11-01 21:31 UTC, merged