Fix NeevaScope onboarding flow
neevaco/neeva-android pull request #1092
Opened 2022-11-02 22:05 UTC by yasminyin96

* Fix NeevaScope education screen:
     * change to full-screen sheet
     * add `X` button to dismiss the sheet
     * use `Let's try it!` for button on non-Neeva page and non SRP

* Both `Try NeevaScope` tooltip and reddit one will disappear after 4 seconds or by tapping

* Fix onboarding flow:
     * The tooltip is disabled by default
     * FLOW1: Neeva/SRP -> `NeevaScope` button -> `Got it!` button -> enable tooltip -> see NeevaScope content or tooltip shown 5 times -> finish onboarding and disable tooltip
     * FLOW2: non Neeva/SRP -> `NeevaScope` button -> `Let's try it` button -> NeevaScope content -> finish onboarding and disable tooltip
     * FLOW3: non Neeva/SRP -> `NeevaScope` button ->  `X` button or swipe down -> enable tooltip -> see NeevaScope content or tooltip shown 5 times -> finish onboarding and disable tooltip

## Checklists

### Pointers to help with review
* [Figma](https://www.figma.com/file/SQpqqCk736DJWbXANK4K5w/Cheatsheet-%2F-NeevaScope?node-id=2316%3A20746)
* [doc](https://paper.dropbox.com/doc/NeevaScope-Android-Tooltip--BsLfKYTH_gb5l6kY0HIe4XAeAQ-lrAFSOOoQmeXCAtu3caUf)
### How was this tested?
- [X] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [X] Existing automated tests cover all of my changes
- [X] I checked that `@Previews` still work in Android Studio

### Screenshots and screen recordings

https://user-images.githubusercontent.com/104786010/199609315-b98e07c9-dedc-4b5b-805e-ac98b22ef530.mov

https://user-images.githubusercontent.com/104786010/199609463-109464ab-a7cc-4567-9c3c-3ea375be1855.mov

https://user-images.githubusercontent.com/104786010/199609612-5af281f6-6ede-4e54-bdd2-24216f17a6b5.mov

<img width="500" alt="Screen Shot 2022-11-02 at 3 02 17 PM" src="https://user-images.githubusercontent.com/104786010/199611018-21a7eb6e-9cf8-47c7-8aa2-722144032176.png">

2022-11-03 17:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserBottomToolbar.kt
> +    val sharedPreference = LocalSharedPreferencesModel.current
"SharedPreferences" is a specific thing; call this `sharedPreferencesModel` to make it clearer

2022-11-07 23:24 UTC, Kokobe requested changes
Just some style nits

2022-11-07 23:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeInfoScreen.kt
> +    @StringRes buttonText: Int,
Style Nit: I think naming this `buttonTextId` helps differentiate it from other "buttonText" parameters that are actually strings instead of ints.

2022-11-07 23:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeInfoScreen.kt
> +        onClick = tapButton,
Style nit: Keep the parameter names consistent: instead of `tapButton` use `onClick`

2022-11-10 17:27 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserBottomToolbar.kt
> +                    SharedPrefFolder.App.ShowingNeevaScopeTooltip.set(sharedPreferencesModel, true)
Are you sure `ShowingNeevaScopeTooltip` is a UI state we should be storing in `SharedPreferences`? 🙂 It isn't something that needs to be persisted after the app dies.

If anything it should be a `StateFlow` in `NeevaScopeModel` where the State is named `ShowNeevaScopeTooltip`. 

This condition in PopupModel.kt:
```
// val canShowPromo:
!SharedPrefFolder.App.ShowingNeevaScopeTooltip.get(sharedPreferencesModel) &&
```
can be moved upwards to `BrowserToolbarModelImpl` and changed to:

```
getNeevaScopeModel().ShowNeevaScopeTooltip.value == true
```

2022-11-10 17:27 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserBottomToolbar.kt
> +                    SharedPrefFolder.App.ShowingNeevaScopeTooltip.set(sharedPreferencesModel, true)
It actually could be just a variable because it looks like no compose UI is going to call `showNeevaScopeTooltip.value`. 

You can decide how this variable can be updated, I recommend piping it through `BrowserToolbarImpl` since it already has a reference to `NeevaScopeModel` but you might know a better way?

2022-11-10 17:27 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/PopupModel.kt
> +    val canShowPromo: Boolean = bottomSheetDialogState.value == null &&
I'm pretty sure this needs to be a `get()` variable or a function. You want the value to be updated whenever some other code calls `canShowPromo`. Otherwise it's just a static value that only gets initialized during the Hilt init

2022-11-10 17:28 UTC, Kokobe requested changes
Lmk if you need any help

2022-11-11 19:33 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/ui/PopupModel.kt
> +    val canShowPromo: Boolean = bottomSheetDialogState.value == null &&
What if we only want to update it when app starts? `canShowPromo` is to check whether a promo can be shown during the current session(from the app starts to the app dies). Only when no promo has been shown during the session, `canShowPromo` will be true. (ref: [doc](https://paper.dropbox.com/doc/NeevaScope-Android-Tooltip--BsvCxZmT1xTL3iyb0SrPSijfAg-lrAFSOOoQmeXCAtu3caUf#:uid=486812739765822488961975&h2=Implementation-details))

2022-11-11 21:12 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/PopupModel.kt
> +    val canShowPromo: Boolean = bottomSheetDialogState.value == null &&
Ah got it! Yeah this is good then

2022-11-14 19:59 UTC, dan-alcantara-neeva commented
Was this one good to review again @yasminyin96?

2022-11-14 21:02 UTC, yasminyin96 commented
> Was this one good to review again @yasminyin96?

Yes

2022-11-14 22:37 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/BaseBrowserWrapper.kt
> +            MutableStateFlow(SharedPrefFolder.App.SeenNeevaScopeIntro.get(sharedPreferencesModel))
Having a little bit of trouble parsing this.  It looks like you're trying to create a `MutableStateFlow` and initializing it with the current value of the `SeenNeevaScopeIntro` `SharedPreference`, then manually editing it and keeping the `SharedPreference` in sync.

I think you want to do this instead:

```
val seenNeevaScopeIntro by SeenNeevaScopeIntro.getFlow(sharedPreferencesModel).collectAsState()
```

That way you're collecting the Flow directly.  On line 1146 where you're setting both the value of the `MutableStateFlow` and the `SeenNeevaScopeIntro` `SharedPreference`, you could just directly set the `SharedPreference` and the `Flow` should automatically update.

2022-11-14 22:37 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserBottomToolbar.kt
> +    val sharedPreferencesModel = LocalSharedPreferencesModel.current
Is this used anywhere?

2022-11-14 22:40 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/browsing/toolbar/BrowserBottomToolbar.kt
> +    val sharedPreferencesModel = LocalSharedPreferencesModel.current
Not used, I will delete this line as well as the line in BrowserToolbar.

2022-11-15 18:38 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/browsing/BaseBrowserWrapper.kt
> +        }
I added these lines(1113-1115) here because if the user clicks on the `X` button instead of `Let' try it` button on non-Neeva page, we don't want to update the `SeenNeevaScopeIntro` immediately. If `SeenNeevaScopeIntro` immediately becomes true, the sheet will direct to the loading and result screen before the sheet dismissing.

2022-11-15 18:41 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/ui/PopupModel.kt
> +        SharedPrefFolder.FirstRun.didShowAdBlockOnboarding.get(sharedPreferencesModel)
@dan-alcantara-neeva I found that `didShowAdBlockOnboarding` will be true by default and set to false for the first run. Is it possible to get the value of `didShowAdBlockOnboarding` after the first run when the app starts?

2022-11-15 19:12 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/PopupModel.kt
> +        SharedPrefFolder.FirstRun.didShowAdBlockOnboarding.get(sharedPreferencesModel)
You'll want to sync with @chung-lai about that.  I think it's because of how the code doesn't set the value when it gets checked, so he had to be creative to avoid showing existing users the ad block promo.

2022-11-15 19:14 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/browsing/BaseBrowserWrapper.kt
> +        }
Got it.

2022-11-15 22:15 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/PopupModel.kt
> +        SharedPrefFolder.FirstRun.didShowAdBlockOnboarding.get(sharedPreferencesModel)
If that's the case, is your question resolved, or did you still need to work around that?

2022-11-15 22:18 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/ui/PopupModel.kt
> +        SharedPrefFolder.FirstRun.didShowAdBlockOnboarding.get(sharedPreferencesModel)
Yes, it's resolved, and pushed the new commit with comment about this.

2022-11-15 22:31 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/NeevaScopeModel.kt
> +            updateQuery(currentUrl.toString(), activeTabModel.titleFlow.value)
Instead of passing the whole model, just pass in the `titleFlow.value` and whether the user `isOnNeevaSearch`

2022-11-15 22:35 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/PopupModel.kt
> +        SharedPrefFolder.FirstRun.didShowAdBlockOnboarding.get(sharedPreferencesModel)
While you're there, can you rename that `val didShowAdBlockOnboarding = SharedPrefKey(` to be properly capitalized like every other key?  `val DidShowAdBlockOnboarding = SharedPrefKey(`

2022-11-16 19:16 UTC, dan-alcantara-neeva approved these changes

2022-11-16 19:32 UTC, Kokobe approved these changes

2022-11-16 20:11 UTC, merged