Kobe/add billing support wifi check
neevaco/neeva-android pull request #1098
Opened 2022-11-09 09:16 UTC by Kokobe

General description of what your PR does, written in a way that someone six
months from now could understand what you were doing when tracking down a bug
or attempting to add new functionality

* More details about the changes
* Even more details about the changes
* Yet more details about the changes

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2022-11-11 20:00 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/NeevaBillingClient.kt
> +        billingClient.startConnection(object : BillingClientStateListener {
Great suggestion!

2022-11-11 23:16 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/NetworkHandler.kt
> +class NetworkHandler(appContext: Context) : ConnectivityManager.NetworkCallback() {
Ah so in `NeevaAppModules.kt`, you'll see a lot of classes that follow this pattern of being dependent on `Context`. While it is important to often not have classes reference `Context` (because if the context dies because of an activity change or something, it'll lead to a memory leak), the context being passed into this class is an `AppContext`.

The lifecycle of this Context is based on the application. So if the only way for this Context to die is if the whole application dies (which makes it memory leak safe).

2022-11-14 03:19 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/NetworkHandler.kt
> +    fun whenConnectedToInternet(onConnected: () -> Unit) {
Ah yeah you're right -- it does run on the main thread. Since `startConnection()` is being called from the `lifecycleScope` which is bound to the Dispathcers.Main one: 
<img width="623" alt="Screen Shot 2022-11-13 at 7 18 15 PM" src="https://user-images.githubusercontent.com/20916043/201567953-ebed93e1-0afa-49a1-9ad3-61b40f8b545e.png">

I've added a `coroutineScope.launch(dispatchers.io) {` here to make sure it isn't blocking.

2022-11-14 03:29 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/NetworkHandler.kt
> +    private var tasksToRunWhenConnected: MutableMap<String, () -> Unit> = mutableMapOf()
Because the internet connection could go out at any line, I don't want to clear the whole list each time `onCapabilitiesChanged()` is called. Instead, I have each `task` check if it is connected to the internet and remove itself from the map after it finishes. Removing a task from the map takes O(1) time + it makes it easy/clean to self remove itself from the map imo

2022-11-14 03:37 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/NetworkHandler.kt
> +    private var tasksToRunWhenConnected: MutableMap<String, () -> Unit> = mutableMapOf()
I feel like my code already minimizes the chance of a race condition, but maybe I don't understand your comment enough? 

My code does handle retries (it doesn't check if the task was successful though) by doing that extra internet check and I'm not sure what you mean in your latter half of comment in the parenthesis

2022-11-14 03:39 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/NetworkHandler.kt
> +    fun whenConnectedToInternet(onConnected: () -> Unit) {
`runWhenConnectionActive` is a better name 🙂 thanks!

2022-11-15 20:00 UTC, andjd reviewed
None of your code is wrong, but I have a handful of suggestions.

2022-11-15 20:26 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/NetworkHandler.kt
> +            val tasksIterator = tasksToRunWhenConnected.iterator()
Ah so that iterator is there so that concurrent threads can mutate the `tasksToRunWhenConnected` `List` at the same time... I see that I'm not having the threads remove the tasks anymore so you're totally right thank you for catching that 🙂

2022-11-15 20:36 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/NetworkHandler.kt
> +            val tasksIterator = tasksToRunWhenConnected.iterator()
Ended up using: 
```
if (capabilities.hasCapability(NET_CAPABILITY_VALIDATED)) {
            tasksToRunWhenConnected = tasksToRunWhenConnected.filter { networkHandlerTask ->
                if(!isConnectedToInternet()) return@filter true
                networkHandlerTask.task.invoke()
                networkHandlerTask.runEveryTime
            } as MutableList<NetworkHandlerTask>
        }
```

2022-11-15 20:49 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/NeevaBillingClientSetup.kt
> +                "A good internet connection does not fix the Billing Client Connection error."
How does: "Multiple internet connection restarts does not fix the Billing Client Connection error." sound?

2022-11-15 20:58 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/NeevaBillingClientSetup.kt
> +class NeevaBillingClientSetup(
I should actually rename `NeevaBillingClient` to `BillingClientWrapper` (will do in a future PR) and I can rename `NeevaBillingClientSetup` to `BillingClientManager` (in this PR)

2022-11-15 20:59 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/NeevaBillingClientSetup.kt
> +        val docsUrl = "https://developer.android.com/reference/com/android/billingclient/api/" +
I feel like since it's only used here, I should leave it here

2022-11-16 07:17 UTC, Kokobe commented
[Slack discussion](https://neevaco.slack.com/archives/C02RYG8LY8H/p1668581328849149): Why I chose not to use WorkManager

2022-11-16 16:54 UTC, andjd requested changes

2022-11-16 16:54 UTC, andjd commented on app/src/main/java/com/neeva/app/billing/BillingClientWrapper.kt
> +        }
You also need to modify the establishConnection function, since that function is currently where the networkManager.runWhenConnectionActive() is invoked.

2022-11-17 07:35 UTC, Kokobe commented
Closing because NetworkHandler is not needed for `BillingClient`. We should be solving `queryPurchases` or `BillingClient` connection errors by simply retrying them when they fail (with Exponential Backoff) instead of guessing that the problem is lack of internet connection. 

`NetworkHandler` may be useful for other Apollo Operations such as fetch for user profile data or spaces data.

2022-11-17 07:35 UTC, closed without merging