Billing: Set up launch billing flow prototype (behind a flag)
neevaco/neeva-android pull request #1103
Opened 2022-11-11 19:47 UTC by Kokobe

Uses the debug `DEBUG_ENABLE_BILLING` flag to decide whether to show the `BILLING_FLOW` screen.  

* Prototyping the payment to subscriptions. 

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2022-11-23 00:20 UTC, dan-alcantara-neeva requested changes
Going to need to reconsider how this should work, I think.  Especially because the call to purchase a subscription is going to depend on these other two calls working

2022-11-25 08:28 UTC, Kokobe commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
>          if (settingsDataModel.getSettingsToggleValue(SettingsToggle.DEBUG_ENABLE_BILLING)) {
That's okay, I'll add a popup to tell you to restart the app when using this toggle.

2022-11-25 08:33 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        onBillingClientReady()
Changed the name to `fetchProductsAndPurchases()`

2022-11-25 08:37 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        onBillingClientReady()
Maybe I can make the `startBillingConnection()` to be one of the jobs in the job queue. That way, fetchProductsAndPurchases will wait for the connection to be valid before doing its fetch tasks

2022-11-25 08:46 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +    private val jobQueue: Queue<BillingClientJob> = LinkedList()
Hmmmm I'm using the `private val isProcessingJob = AtomicBoolean(false)` line to manually avoid that exception. Is there another way you suggest on dealing with this?

2022-11-25 08:48 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +            job.invokeOnCompletion {
Very cool!!!

2022-11-27 06:44 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientWrapper.kt
> +            coroutineScope.launch(dispatchers.io) {
So what suspendCoroutine actually puts you in is a: `crossinline block: (Continuation<T>) -> Unit`

Since this isn't a `suspend` parameter, I can't add a `delay()` unless I launch another coroutine inside of it.

2022-11-27 06:47 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        queueJobWithRetry(
If one of the tasks fails, our behavior should be to not allow the user to purchase a subscription using Google Play (aka. never show the purchase screen -- which will be done in a future PR)

2022-11-27 06:51 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        queueJobWithRetry(
I've made it so that `onBillingSetupFinished()` does not call `fetchProductsAndPurchases()`. This avoids calls triggering a requeue of a call that already happened. 

Now the flow from `onCreate` is:

```
Queue = [
fetchPurchases(),
fetchProductDetails()
]

Whenever one of these operations fail, the billingClient will be restarted up to a max of 3 times 
with exponential backoff. 

The first time is guaranteed to fail, which will set up the billingClient and then re-run the operation.
```

2022-11-27 06:58 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        queueJobWithRetry(
`fetchPurchases` and `fetchProductDetails` will only be requeued in `onResume()`. If the task already exists in the job queue, it will not be queued.

2022-11-28 17:50 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +            job.invokeOnCompletion {
I've enforced the queue behavior by doing a `private val jobQueueFlow: MutableSharedFlow<Queue<BillingClientJob>> = MutableStateFlow(jobQueue)`

Is that right?

2022-11-28 18:36 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientWrapper.kt
> +            coroutineScope.launch(dispatchers.io) {
Why don't you just put the delay outside of that `suspendCoroutine` block, then?  You don't care when it fires -- only that it waits 1 second before doing it.  `retryConnection` is already a suspend function, too.

2022-11-29 22:53 UTC, dan-alcantara-neeva requested changes

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/BillingScreen.kt
> +                        it.hasMonthlyPremiumPlan.collectAsState(false).value -> "monthly premium"
1. You're using `collectAsState` weirdly here; you should be collecting them as state above line 37 and checking their values in your `when` block.
2. Are these string constants or just your debugging output?

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/BillingScreen.kt
> +                        Text("Monthly Plan")
Is this real UI or just debugging?  You should be putting strings in the `strings.xml` file if it's the former.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/BillingScreen.kt
> +            Column(Modifier.fillMaxSize()) {
Should this be scrollable?

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/BillingScreen.kt
> +        Box(Modifier.fillMaxSize()) {
I think the `Surface` already acts like a `Box` so you can move the modifier to the `Surface` and remove the `Box`.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +                        retries = 0
You never set this back to 0 unless a job succeeds, but you only allow a job to run if `retries <= MAX_RETRIES`.  This means that you'll never try to fire off any of your jobs until the app dies and restarts.  You should figure out an opportunity to reset it without the app dying (like `onResume`).

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +                    var success = job()
Everything in here about running and retrying the job should be part of the `processJob`  function and not the `queueJob` function.  `BillingClientJob` should just hold a reference to `job`, which would then get used elsewhere.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                purchase.products.contains(BillingSubscriptionPlanTags.ANNUAL_PREMIUM_PLAN)
MONTHLY, not ANNUAL.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        val eligibleOffers = emptyList<ProductDetails.SubscriptionOfferDetails>().toMutableList()
Can you just create a `MutableList` directly?  Creating an `emptyList` and then converting it into a `MutableList` is an unnecessary step

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +     * Calculates the lowest priced offer amongst all eligible offers.
lowest-priced

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        if (offerDetails.isNotEmpty()) {
The `if` is redundant because the `for` loop won't do anything if `offerDetails` is empty.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        purchases: List<Purchase>?,
existingPurchases?

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                for (price in offer.pricingPhases.pricingPhaseList) {
Can you use `minBy` instead?

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        // TODO(kobec): add obfuscatedUserID != null as a condition
Is this a required TODO?  What happens if you haven't accounted for it?

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            if (billingParams != null) {
Should this just live inside of the `?.let` block above?  You don't use the `billingParams` anywhere except this call

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +                    // If the BillingClient's last connection is cached, it is possible that this
Move line 41 next to line 47 to keep your comment block together?

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +            billingClient?.queryPurchasesAsync(params) { billingResult, purchaseList ->
Can `queryPurchasesAsync` return null?  If not, do a null check on `billingClient` before trying to use it and move your block on line 55 up to here so it's a clear error condition that causes an early exit.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +            for (purchase in purchases) {
`purchases.forEach` to stay kotlin-y.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +        purchase?.let {
Early exit if `purchase is null`.  Allowing a `null` `purchase` as an argument is weird, though.  Should you do `purchases.filterNotNull()` and make sure this is not null, instead?

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +                billingClientController.getBillingClient()?.acknowledgePurchase(
Early exit if the `billingClient` is null.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +            billingClient
1. Can `billingClient` change or become null before the `suspendCoroutine` code block fires?  I'm guessing yes if you try to retry a call, so you should move retrieval of `billingClient` to line 34.
2. early exit if `billingClient` is not null.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientWrapper.kt
> +    suspend fun retryConnection(delayTime: Long): Boolean {
1. You can't guarantee that this will be called by only one place, meaning that you could have a new coroutine terminating a `billingClient` used by another coroutine that's already running.  You should mark this as `@NonThreadSafe`
2. Mark relevant functions as `internal` to avoid other callers making unexpected calls.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientWrapper.kt
> +        delay(delayTime)
Don't pass the `delayTime` into here; use that value where you call `retryConnection`.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientWrapper.kt
> +        return suspendCoroutine { continuation ->
Your `suspendCoroutine` block will never call `continuation.resume` if `billingClient` is null

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        if (billingResult == null || billingResult.responseCode != BillingResponseCode.OK) {
```
if (billingResult?.responseCode != BillingResponseCode.OK)
```

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +                activeJobSet.add(uniqueJobName)
`add` returns a boolean saying whether or not the item was added.  You can use that and avoid the `contains`.

2022-11-29 22:53 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        if (settingsDataModel.getToggleState(SettingsToggle.DEBUG_ENABLE_BILLING).value) {
Early exit if your toggle isn't set correctly.

2022-11-30 19:20 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/BillingScreen.kt
> +        Box(Modifier.fillMaxSize()) {
`Box` is actually needed so I can put the close button the TopEnd

2022-11-30 19:21 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/BillingScreen.kt
> +            Column(Modifier.fillMaxSize()) {
Yes, but that work I will do in a future PR where I actually implement the Billing Design

2022-11-30 19:22 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/BillingScreen.kt
> +                        it.hasMonthlyPremiumPlan.collectAsState(false).value -> "monthly premium"
This is just debugging output. I'll add as a comment to this file that all of this is behind a flag + just a prototype

2022-11-30 19:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/BillingScreen.kt
> +                        Text("Monthly Plan")
These are all debugging

2022-11-30 20:10 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        // TODO(kobec): add obfuscatedUserID != null as a condition
It's required because the back-end needs to map a purchaseToken with a userID. Currently only works on carl's server so thats why I removed the condition for now

2022-12-01 17:56 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +            billingClient?.queryPurchasesAsync(params) { billingResult, purchaseList ->
queryPurchasesAsync does not return anything (`void`), but I'll move the early exit condition higher so its clear

2022-12-01 19:36 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +            billingClient
Moved it into the suspendCoroutine!

+ Early exited

2022-12-01 19:50 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientWrapper.kt
> +    suspend fun retryConnection(delayTime: Long): Boolean {
Had to mark the class as `@NotThreadSafe`

2022-12-01 21:06 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/BillingScreen.kt
> +        Box(Modifier.fillMaxSize()) {
You already have a BoxScope, don't you?  Look at the definition of Surface

2022-12-01 21:07 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/BillingScreen.kt
> +        Box(Modifier.fillMaxSize()) {
Unless it doesn't pass it down so that you can't set the alignment

2022-12-01 21:10 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        }
Add `distinctUntilChanged` here and on line 33?  Avoids the same boolean getting sent out twice

2022-12-01 21:14 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +            billingClientController.getBillingClient()?.acknowledgePurchase(
reuse the `billingClient` from line 95

2022-12-01 21:18 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +            jobQueueFlow.emit(BillingClientJob(uniqueJobName = uniqueJobName, job = job))
Can you just put this in the synchronized block?  You're already early exiting in the opposite case, so you might as well just put the call there.
```
            synchronized(activeJobSet) {
                val hasBeenAdded = activeJobSet.add(uniqueJobName)
                if (!hasBeenAdded) {
                    jobQueueFlow.emit(BillingClientJob(uniqueJobName = uniqueJobName, job = job))
                }
            }
```

2022-12-01 21:24 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                { it },
Can you just use `it.offerToken`?

2022-12-01 21:26 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        coroutineScope.launch(dispatchers.io) {
Move this to `init { }` so you have no chance of missing anything from the Flow and so you can use `replay=0, extraBufferCapacity=2`.

2022-12-01 22:23 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +            jobQueueFlow.emit(BillingClientJob(uniqueJobName = uniqueJobName, job = job))
I cannot because I get this error:
<img width="943" alt="Screen Shot 2022-12-01 at 2 22 58 PM" src="https://user-images.githubusercontent.com/20916043/205171723-1ec2d034-abc8-49bb-b863-4d72d7bba54a.png">

2022-12-01 22:30 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        coroutineScope.launch(dispatchers.io) {
My current MutableSharedFlow defined as:
```
private val jobQueueFlow: MutableSharedFlow<BillingClientJob> = MutableSharedFlow(
        replay = 0,
        extraBufferCapacity = 2
    )
```

But according to https://stackoverflow.com/questions/71309128/mutablesharedflow-difference-between-replay-and-extrabuffercapacity and the docs, it seems that doing replay=0 and extraBufferCapacity=2 is equivalent, no?

2022-12-01 22:31 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        coroutineScope.launch(dispatchers.io) {
I'm going to have to change it to extraBufferCapacity = 3 since I introduced a new job (`acknowledgePurchase`) that can be queued up

2022-12-01 22:33 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        coroutineScope.launch(dispatchers.io) {
It's not equivalent; read the answer (and the comments for the answer) more closely.  `replay` is the number of things that will be replayed to subscribers that started collecting later than the items were added to the queue.  This means that another subscriber will get those `replay` number of items again.  `extraBufferCapacity` is the number of additional items to store that don't get replayed.

2022-12-01 22:36 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        coroutineScope.launch(dispatchers.io) {
Ah but in this case, where there is only 1 subscriber in the `init`, it is the same thing. Thanks for helping me understand that

2022-12-01 22:43 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/BillingScreen.kt
> +        Box(Modifier.fillMaxSize()) {
<img width="338" alt="Screen Shot 2022-12-01 at 2 43 15 PM" src="https://user-images.githubusercontent.com/20916043/205174621-0c501392-9939-4e82-a107-629ba8e8886f.png">

Yeah unlike Box's parameters that pass down `BoxScope` in the content composable lambda, Surface does not :(

2022-12-02 19:23 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +                if (!hasBeenAdded) {
Something looks wonky here; I think you were supposed to move the emit line into here instead of just negating the boolean?

2022-12-02 19:26 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        coroutineScope.launch(dispatchers.io) {
This is called after every attempt to fetch the user, which means that you're allowing this coroutine to fire multiple times in parallel.  Is that intentional, or do you want this job to be done only once?

2022-12-02 20:00 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/billing/BillingClientControllerTest.kt
> +        verify(exactly = 2) { testJobMock.job1() }
Add a `verify(exactly = 1) { ... }` counterpart after line 165

2022-12-02 23:00 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +                if (!hasBeenAdded) {
I was wrong the first time, but the current logic you see here is right.

2022-12-02 23:08 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        coroutineScope.launch(dispatchers.io) {
It is possible for this coroutine to fire multiple apollo calls at once if the `onUserSignedIn()` function is spammed. 

Currently, it is only being called in NeevaUser's fetch() which is only called when the login cookie is valid (Every login or app startup). 

I think that is okay... but if not, I can add state via `SharedPreference`, but managing that can be a separate PR

2022-12-03 00:18 UTC, dan-alcantara-neeva approved these changes

2022-12-03 00:48 UTC, merged