Setup Welcome Flow Architecture + Welcome Screen Design
neevaco/neeva-android pull request #1135
Opened 2022-12-07 04:07 UTC by Kokobe

Sets up Welcome Flow Architecture by introducing a `WelcomeFlowContainer` that has a header and content. If the content + header is too large for the screen, the whole container needs to be scrollable. 

* Implemented the designs one Welcome Screen, but no functionality has been implemented yet. 
* All of this is behind a dev settings (see video) 
* Adding Screenshot tests in a future PR (aka. once I confirm UI with Hwi) 

## Checklists

### Pointers to help with review
* Figma: https://www.figma.com/file/dylvDPB69JG9U1rzZ3HQ52/Android-Premium?node-id=132%3A5081&t=YNBvJGQZ9Bcae59J-0

### How was this tested?
- [x] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [x] I checked that `@Previews` still work in Android Studio

### Screenshots and screen recordings

https://user-images.githubusercontent.com/20916043/206304063-59b7abbf-c482-4d15-994e-5941fa887143.mp4

<img width="1276" alt="Screen Shot 2022-12-07 at 2 07 27 PM" src="https://user-images.githubusercontent.com/20916043/206307091-d1865a26-2fea-4a8f-9828-dd84dc8857fb.png">
<img width="1278" alt="Screen Shot 2022-12-07 at 2 07 35 PM" src="https://user-images.githubusercontent.com/20916043/206307093-6574e25b-18cb-42ad-9e54-3e7ab6b23fa2.png">

2022-12-07 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +    systemUiController.setStatusBarColor(ColorPalette.Brand.Blue, darkIcons = false)
1. If you scroll down, the color won't match anymore, either.  Is there a function in `systemUiController` that `setStatusBarColor` that detects what color is underneath it?
2. Use a `DisposableEffect` to set it back to the correct color once the Composable leaves the Composition automatically.

2022-12-07 22:14 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +    DisposableEffect(true) {
Move line 47 into here?  I believe that the lambda passed into the `DisposableEffect` runs when it's composed, then only the `onDispose` part gets run when it gets removed from the Composition.

2022-12-07 22:14 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                Pair(0.95f, MaterialTheme.colorScheme.background)
Change to 0.05f to make a hard break between the Blue and Background colors.  Avoids a situation where 90% of the surface has a gradient that is visible when the Column it contains is shorter.

2022-12-07 22:14 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                    shape = RoundedCornerShape(topStart = 24.dp, topEnd = 24.dp),
Can you add 24.dp as a `RADIUS_HUGE` to `Dimensions.kt`?

2022-12-07 22:14 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                        .wrapContentHeight()
Is the `wrapContentHeight` modifier still necessary?  Feels like that should be implicit...

2022-12-07 22:14 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                    bottom.linkTo(parent.bottom, margin = 24.dp)
`PADDING_HUGE`?

2022-12-07 22:14 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +        Spacer(Modifier.height(58.dp))
You sure about this 58.dp?  Any time I see a weird number like this, I'd want to confirm with the designer that this is intentional and not a side-effect of wanting some part of the dialog to be centered or something.  Same with the 18.dp, 10.dp, etc

2022-12-07 22:14 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +                top.linkTo(titleRef.bottom)
Do you need to link this bottom to the bottom of the parent?

2022-12-07 22:46 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +    DisposableEffect(true) {
Ah I can't move line 49 into the DisposableEffect lambda because that lambda is not a `@Composable`.

2022-12-07 22:48 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                        .wrapContentHeight()
You're right, it is implicit

2022-12-07 23:00 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +        Spacer(Modifier.height(58.dp))
I was accounting for the vertical padding I applied. I removed it and used 82.dp instead as the spacer:

<img width="426" alt="Screen Shot 2022-12-07 at 2 59 57 PM" src="https://user-images.githubusercontent.com/20916043/206315370-18f64843-70c9-4d3b-849e-7e441942163b.png">

2022-12-07 23:09 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +        Spacer(Modifier.height(58.dp))
82.dp is even weirder lol.  Can you ask Hwi if that value is intentional, or if there's some rule she's following to result in the 82.dp value?

2022-12-07 23:11 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +                top.linkTo(titleRef.bottom)
<img width="317" alt="Screen Shot 2022-12-07 at 3 10 14 PM" src="https://user-images.githubusercontent.com/20916043/206316951-dc67ea1d-d222-4a75-9edf-a6c5b52d1afd.png">

The mocks say that the check mark should be the top of the composable, and the "Private" text is centered in relation to the check. So no need to link this to the bottom of the parent

2022-12-07 23:11 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +                start.linkTo(check.end, margin = Dimensions.PADDING_LARGE)
Nope -- that would center it between the check.end and parent.end.

2022-12-07 23:13 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +    <string name="welcomeflow_initial_header">Search and browse,\nfree from corporate influence</string>
Using '\n` in the strings.xml file seem to work fine for the other translations though?

2022-12-07 23:13 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +    <string name="welcomeflow_initial_header">Search and browse,\nfree from corporate influence</string>
But you bring up a good point

2022-12-07 23:30 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +    <string name="welcomeflow_initial_header">Search and browse,\nfree from corporate influence</string>
Okay I have implemented a better way to do this

2022-12-08 00:48 UTC, dan-alcantara-neeva commented on app/src/main/res/values/strings.xml
> +    <string name="welcomeflow_initial_header">Search and browse,\nfree from corporate influence</string>
Yeah, other translations can handle `\n`, but I don't want to get into a situation where we end up showing 

```
recherchez et
naviguez,
à l'abri de
l'influence de
l'entreprise
```

because the sentence phrases don't fit on one line like you want.  Might be fine, but might look weird

2022-12-08 00:52 UTC, dan-alcantara-neeva requested changes

2022-12-08 00:52 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                brush = Brush.verticalGradient(
Leave a comment about why this hack is necessary.  Looks weird without the context of our Slack convo.

2022-12-08 00:52 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                if (headerText.contains("\n")) {
Ehh... I'd rather have it look weird in the translations than put a hack in like this.  Breaking it into two pieces means that it won't respect the font's line spacing, either.

2022-12-08 00:52 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +        Spacer(Modifier.height(82.dp))
1. Same question about asking Hwi where this value came from.
2. Send her the @Previews and ask if they look good.

2022-12-08 01:18 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +        Spacer(Modifier.height(58.dp))
@hwiatneeva Thoughts?

2022-12-08 01:23 UTC, hwiatneeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +        Spacer(Modifier.height(58.dp))
It's measured (grouped) from the checkmark to the top edge: 80!

2022-12-08 22:54 UTC, dan-alcantara-neeva approved these changes

2022-12-09 01:55 UTC, merged