Add Welcome Flow Functionality for Welcome Screen
neevaco/neeva-android pull request #1140
Opened 2022-12-09 08:19 UTC by Kokobe

Adds functionality for each clickable element in the `WelcomeScreen`. 

## Checklists

### Pointers to help with review
* Figma: https://www.figma.com/file/dylvDPB69JG9U1rzZ3HQ52/Android-Premium?node-id=132%3A5081&t=38oad62CWbI7kqVv-0

### How was this tested?
- [x] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [x] I checked that `@Previews` still work in Android Studio

### Manual test cases
Tapped on everything in the Welcome Screen. See recording

### Screenshots and screen recordings

2022-12-13 18:33 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/PreviewContainer.kt
> +        LocalSettingsDataModel provides previewSettingsDataModel,
Alphabetize

2022-12-13 18:38 UTC, dan-alcantara-neeva requested changes

2022-12-13 18:38 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/NeevaUser.kt
> +                    it.job()
You should remove each job as you go instead of clearing the whole thing.  That way, if this somehow breaks, you're not going to end up with old tasks getting re-run in the queue.  You can do that by making a copy of the `jobsToRun` and iterating on that, them removing each entry from the original as you go.

2022-12-13 18:38 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/NeevaUser.kt
> +
Are we guaranteed that on call to `fetch()` will not in parallel with another call to `fetch()`?

2022-12-13 18:38 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/NeevaUser.kt
> +    override fun queueOnSignIn(uniqueJobName: String, job: () -> Unit) {
Is this a fork of the other pattern you were doing before?

2022-12-13 18:38 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                                navigateToPlans = { Timber.tag("KOBE").e("Navigated to plans") },
Remove log

2022-12-13 18:38 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> + * UNFINISHED COMPOSABLE. I've only wrote the skeleton, but will be unable to confirm if it works
This is where you actually should add a TODO instead of calling it an unfinished composable.

2022-12-14 09:39 UTC, Kokobe commented on app/src/main/java/com/neeva/app/userdata/NeevaUser.kt
> +
I could make a `mutex` to ensure this doesn't happen, but this means: 

* If I login with User A
* then immediately sign out 
* and then login with User B,
*  if the fetch() from User A is still running, it will only incorrectly load User A's data.

2022-12-14 18:40 UTC, dan-alcantara-neeva approved these changes

2022-12-14 18:40 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/NeevaUser.kt
> +                    onSignedInJob.job()
nit: Maybe don't call the field `job()` too.

2022-12-15 02:42 UTC, merged