Implement Welcome Flow Create Account Designs
neevaco/neeva-android pull request #1160
Opened 2022-12-17 09:53 UTC by Kokobe

Implements the Create Account Screens. 

* Forks the buttons from FirstRun and repurposes them.
* Functionality happening in the next PR.

## Checklists

### Pointers to help with review
* https://www.figma.com/file/dylvDPB69JG9U1rzZ3HQ52/Android-Premium?node-id=7%3A1207&t=3IcJbiz1fpC8ytsS-0

### How was this tested?
- [x] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [x] I checked that `@Previews` still work in Android Studio

### Screenshots and screen recordings

2022-12-19 18:39 UTC, dan-alcantara-neeva requested changes

2022-12-19 18:39 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/SharedComposables.kt
> +    Button(
Isn't there `TextButton` that has the style that you want (just blue on white)?  Then you don't have to hard-code these colors.

2022-12-19 18:39 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                    modifier = Modifier.width(89.dp)
80 I can deal with, but this 89 is super specific.  Confirm that it's an intentional value with @hwiatneeva and that the number in the Figma isn't calculated by a rule being applied (like centered within the container).

2022-12-19 18:39 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/LoginButtons.kt
> +        LoginButton(
This is basically an `OutlinedButton`, isn't it?  https://m3.material.io/components/buttons/guidelines

2022-12-19 18:39 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/LoginButtons.kt
> +    when (provider) {
Maybe pull the `return stringResource` up to the `when`?  Then you don't have to keep repeating it.

```
return stringResource(
    when (provider) {
        NeevaUser.SSOProvider.MICROSOFT -> {
            if (signup) {
                R.string.sign_up_with_microsoft
            } else {
                R.string.sign_in_with_microsoft
            }
        }

        NeevaUser.SSOProvider.GOOGLE -> {
          ...
    }
}
```

2022-12-19 18:39 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/SSOProviderButtonIcon.kt
> +    when (ssoProvider) {
Is there any difference between these cases?  Might as well combine all three provider types.

2022-12-19 18:39 UTC, dan-alcantara-neeva commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_with_email">Sign up with Email</string>
Make sure that `Email` is supposed to be capitalized.  We lowercase it on our privacy policy and login screens (Please enter your email address), the error says "You already have an account with this email address", etc.

2022-12-19 19:27 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                    modifier = Modifier.width(89.dp)
<img width="492" alt="Screen Shot 2022-12-19 at 11 25 48 AM" src="https://user-images.githubusercontent.com/20916043/208504168-7d2c53c5-9407-483c-be3c-87fac137f278.png">

Hwi is out this week, but the designs (https://www.figma.com/file/dylvDPB69JG9U1rzZ3HQ52/Android-Premium?node-id=524%3A3564&t=I4tngfbUKr8DsB7M-0) say 89.17 😅 

There aren't any rules or special container centering/sizing

2022-12-19 19:31 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/LoginButtons.kt
> +        LoginButton(
Yes, but I'm trying to reuse the same code for the Google sign-in button, which just uses a different button coloring style:

<img width="581" alt="Screen Shot 2022-12-19 at 11 31 40 AM" src="https://user-images.githubusercontent.com/20916043/208505131-06321853-0bb5-4f0f-a9b9-ba667876f1c3.png">

2022-12-19 19:35 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/SSOProviderButtonIcon.kt
> +    when (ssoProvider) {
Ah one uses an `Image` and the other uses an `Icon`

2022-12-19 19:37 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_with_email">Sign up with Email</string>
<img width="617" alt="Screen Shot 2022-12-19 at 11 37 30 AM" src="https://user-images.githubusercontent.com/20916043/208506176-a15bdb7f-e6f5-431d-8467-b1684ea1a582.png">

2022-12-20 19:33 UTC, dan-alcantara-neeva commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_with_email">Sign up with Email</string>
Yeah, I know what the mocks say.  Is this a mistake in the mocks?

2022-12-20 19:37 UTC, dan-alcantara-neeva commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_with_email">Sign up with Email</string>
Lowercase the e, based on iOS.  Don't want to have to deal with updating Smartling translations if we can correct the mistake now.

2022-12-20 19:40 UTC, dan-alcantara-neeva approved these changes

2022-12-20 22:21 UTC, merged

2022-12-21 03:28 UTC, hwiatneeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                    modifier = Modifier.width(89.dp)
Sorry here 100x20

![neeva-wordmark-100x20](https://user-images.githubusercontent.com/91506909/208813890-42f79052-81e4-409d-8856-70ffc00e624e.svg)

2022-12-21 03:30 UTC, hwiatneeva commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_with_email">Sign up with Email</string>
Yes sorry -- 'e'!