Welcome Flow: Implement Login Flow
neevaco/neeva-android pull request #1161
Opened 2022-12-19 05:06 UTC by Kokobe

General description of what your PR does, written in a way that someone six
months from now could understand what you were doing when tracking down a bug
or attempting to add new functionality

* More details about the changes
* Even more details about the changes
* Yet more details about the changes

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2023-01-03 18:07 UTC, dan-alcantara-neeva requested changes
Still reviewing, but a first batch of comments to start with.

2023-01-03 18:11 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                                // Send the user to a URL created by appending the [finalPath] to
I think you're still supposed to send the user to the `finalPath` after they log in.

2023-01-03 18:12 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                                if (firstRunModel.shouldLogFirstLogin()) {
Do we have equivalent logs or should this be pulled out?

2023-01-03 18:34 UTC, dan-alcantara-neeva reviewed
Pass 2 while I'm looking at strings

2023-01-03 18:34 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/CreateAccountScreen.kt
> +        if (
What happens if neither of these is true?  Nothing happens when the button is clicked?

2023-01-03 18:34 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +    private val SEND_USER_TO_BROWSER_KEY = "sendUserToBrowserOnResume"
1. This should be a const in the companion object.
2. Add comments saying these are supposed to be part of the Intent?

2023-01-03 18:34 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +    private val SUBSCRIPTION_TAG_KEY: String = "selectedSubscriptionPlanTag"
Ditto.

2023-01-03 18:34 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +        if (screenToReturnTo.isEmpty() || screenToReturnTo == Destinations.WELCOME.name) {
Make this thing a `when(screenToReturnTo)` .

2023-01-03 18:34 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +        val FinishWelcomeFlowOnLoginReturn = "FINISHED_WELCOME_FLOW"
const val, all caps underscored

2023-01-03 19:08 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/LaunchLoginFlow.kt
> +            neevaUser.queueOnSignIn(uniqueJobName = "Welcome Flow: onSuccessfulSignIn") {
Should this logic live in a `Model` somewhere instead of a UI `@Composable`?

2023-01-03 19:12 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/RegularBrowserWrapper.kt
> +        // TODO(kobec): use part of the initializeCookieManager() here to set cookie in Browser from SharedPref value
Ah this is an old TODO, this already happens because in MainActivity, the loginToken value is updated/set and the browser cookie jar is updated/set (see `handleLoginIntentIfExists()`).

2023-01-03 19:44 UTC, Kokobe commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +        val newIntent = Intent(this@MainActivity, activityClass).setAction(Intent.ACTION_MAIN)
AFAIK the login intent that opens our app originates from the Neeva login website, which would require the Back-end to be modify the URI string to store new params in.

2023-01-03 19:48 UTC, Kokobe commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +        val newIntent = Intent(this@MainActivity, activityClass).setAction(Intent.ACTION_MAIN)
The problem I'm trying to solve is how to return to the client back to a certain `Activity` and `Screen` after Login. The specific `Activity` and `Screen` is decided by the client and where the login was triggered from. 

For example: 
- login from the WelcomeFlow in FirstRun should return you to the WelcomeFlowActivity PLANS screen.

As I wrote this I realize that all logins reroute to the WelcomeFlowActivity and the `screen` is decided by the logged in UserInfo.

2023-01-03 20:01 UTC, Kokobe commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +        val newIntent = Intent(this@MainActivity, activityClass).setAction(Intent.ACTION_MAIN)
It doesn't sound necessary to me to pass the `client data` (activity + screen to return to after login) to the Neeva website and then have the website send an Intent opening our app containing the right screen and activity to open... because:
* it requires back-end rewiring
* if I keep this Activity/Screen logic on the client, I can ensure that the Activity/Screen I want to return to definitely exists.
* The Activity/Screen to open is dependent on the information only found on the Client-side (Default Browser, Plans selection, if the user can purchase a subscription on this Android device, if the user already has premium)

2023-01-03 20:03 UTC, Kokobe commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +        val newIntent = Intent(this@MainActivity, activityClass).setAction(Intent.ACTION_MAIN)
I'll go the hard-coded enum route

2023-01-03 21:02 UTC, Kokobe commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +        val newIntent = Intent(this@MainActivity, activityClass).setAction(Intent.ACTION_MAIN)
After looking into the hard-coded enum route, I don't think it is needed. 

In` MainActivity.kt`, I use `handleLoginIntentIfExists()` to return false when something is off and I want to just normally launch `NeevaActivity`:
```
// in handleLoginIntentIfExists():
val activityClass = getActivityClassToOpen(activityNameToReturnTo)

if (activityClass == null || screenToReturnTo.isEmpty()) {
    return false
}
```
I return null in getActivityClassToOpen() if the sharedPreference value doesn't match the names of WelcomeFlowActivity or NeevaActivity (aka. if we renamed either class to a name that doesn't match the sharedPref, this function would return null)

This snippet will return false if the SharedPref values are outdated which delegates our launching logic to opening the regular NeevaActivity.

2023-01-03 21:03 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +        val newIntent = Intent(this@MainActivity, activityClass).setAction(Intent.ACTION_MAIN)
Yeah, wasn't suggesting passing the client navigation state to the backend.  Was thinking that for other use cases, we'd want to use Intents to pass data around instead of using these SharedPreferences.  If we didn't have to go out to the single-tabbed Activity in some cases or Intent out to the native google login pathway, I imagine we could have avoided most of this...

2023-01-03 21:33 UTC, Kokobe commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                            val screenToReturnTo = firstRunModel.getScreenToReturnAfterLogin()
I've added a function in MainActivity to confirm that the a given screen matches a corresponding Activity `getScreenToOpen()`

2023-01-03 21:48 UTC, Kokobe commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                                if (firstRunModel.shouldLogFirstLogin()) {
Yeah you're right this should be pulled out

2023-01-03 21:51 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/CreateAccountScreen.kt
> +        if (
Great callout. It should navigate to the default browser -- fixed this!

2023-01-03 22:10 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +        val FinishWelcomeFlowOnLoginReturn = "FINISHED_WELCOME_FLOW"
I've changed this to be one of the Destinations Enum to be more consistent with the screen names. It doesn't actually have a composable screen linked to it, it's just used as a constant string

2023-01-03 22:16 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/LaunchLoginFlow.kt
> +            neevaUser.queueOnSignIn(uniqueJobName = "Welcome Flow: onSuccessfulSignIn") {
The core benefit here would be organization right? 

I can do that

2023-01-03 22:19 UTC, Kokobe commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                                firstRunModel.clearDestinationsToReturnAfterLogin()
If the SharedPreference values are outdated, I clear it in MainActivity.kt

If they are done with the SharedPref values, in `onNewIntent()` in NeevaActivity.kt and WelcomeFlowActivity.kt , this function will be called. 

I think those are all the cases where I should be clearing them. You'll see the update in my next commit!

2023-01-03 23:04 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/LaunchLoginFlow.kt
> +            neevaUser.queueOnSignIn(uniqueJobName = "Welcome Flow: onSuccessfulSignIn") {
Oh so because of `rememberLauncherForActivityResult`, I can't call this in a normal function in a Model (that function would have to have a `@Composable` tag on top of it anyways. 

I think keeping it the current way is actually cleaner though.

2023-01-04 00:21 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/LaunchLoginFlow.kt
> +            neevaUser.queueOnSignIn(uniqueJobName = "Welcome Flow: onSuccessfulSignIn") {
Nevermind, going to move this logic to FirstRunModel

2023-01-04 01:19 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/CreateAccountScreen.kt
> +        if (
After testing on release, I realize that it's okay if neither of those conditions are true. The user will already be routed to either Settings or the SetDefaultBrowser screen. 

The Google Play Subscription Bottom sheet should only pop up if the user selected a non-free Subscription option.

2023-01-04 18:41 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/LaunchLoginFlow.kt
> +            neevaUser.queueOnSignIn(uniqueJobName = "Welcome Flow: onSuccessfulSignIn") {
Composables actually have a `rememberCoroutineScope` function that you can use.  It and its jobs would, however, get canceled as soon as the Composable leaves the screen.

2023-01-04 18:43 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            Timber.e("Unable to launch Purchase Flow because product details is null.")
Missed a comment @Kokobe

2023-01-04 18:43 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +        neevaUser.queueOnSignIn(uniqueJobName = "Welcome Flow: onSuccessfulSignIn") {
Does this hard-coded string const get used anywhere else?

2023-01-04 18:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +                coroutineScope.launch(dispatchers.main) {
Does it make sense to pull this `coroutineScope.launch` out?

2023-01-04 18:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/NeevaUser.kt
> +        jobsToRun.removeIf { it.uniqueJobName == uniqueJobName }
This is a change of behavior, right?  This means that the job will always get removed and put to the back of the queue.  Is that OK?

2023-01-04 18:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/CreateAccountScreen.kt
> +    val (activityToReturnTo, screenToReturnTo) =
You should be using the ActivityReturnParams here instead of continuing to use your Pair

2023-01-04 18:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/CreateAccountScreen.kt
> +        if (setDefaultAndroidBrowserManager.isNeevaTheDefaultBrowser()) {
Should this logic and the previous lambda be moved, like into `FirstRunModel`?

2023-01-04 18:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +        firstRunModel.clearDestinationsToReturnAfterLogin()
You should do this immediately after `getScreenToReturnToAfterLogin` so that if the app crashes in between the two lines, the user won't get stuck in a crashloop when the SharedPref is read again.

2023-01-04 18:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/LaunchLoginFlow.kt
> +    ) { }
Is there nothing to do when the `ActivityResult` comes back?

2023-01-04 18:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/LaunchLoginFlow.kt
> +fun LaunchLoginFlow(
This is a Composable that returns something and doesn't draw anything; I think Android Studio warnings would tell you that it should be lowercased.  Can you check?

2023-01-04 18:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
>              // https://github.com/neevaco/neeva-android/issues/1043
This entire comment should go to the callsite and not here.  You're intentionally calling this function somewhere else and the comment doesn't make sense in that situation.

2023-01-04 20:09 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +        neevaUser.queueOnSignIn(uniqueJobName = "Welcome Flow: onSuccessfulSignIn") {
Nope, it's just a job name (not UI to be translated)

2023-01-04 20:11 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +        neevaUser.queueOnSignIn(uniqueJobName = "Welcome Flow: onSuccessfulSignIn") {
Not the reason I was asking: if you had to use this string somewhere else to (say) check if a job was enqueued, then I would have asked for it to get put into a `const val` somewhere.

2023-01-04 20:13 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/CreateAccountScreen.kt
> +        if (setDefaultAndroidBrowserManager.isNeevaTheDefaultBrowser()) {
I feel like having the navigation logic in the UI is actually cleaner than storing it in the model. It makes it more intuitive and straight forward what the navigation behavior is going to be at this particular screen

I also think this is no different than passing a navigateToSettings() lambda and using it when a button is pressed or an screen state has occurred. WDYT?

2023-01-04 20:15 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/CreateAccountScreen.kt
> +        if (setDefaultAndroidBrowserManager.isNeevaTheDefaultBrowser()) {
Otherwise all of this logic (which is unique per screen) is going to be stuck into a Model and (not going to get reused as well).

2023-01-04 20:21 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/LaunchLoginFlow.kt
> +    ) { }
Originally I had a `neevaUser.queueOnSignIn()` queue a job, but I realized that creates a race condition in which:
the ActivityResult comes back but the `NeevaUser` data has already been fetched and signed in (so the job queued will never happen). 


Since I already have `neevaUser.queueOnSignIn()`, I don't really have anything to do when ActivityResult comes back

2023-01-04 20:22 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/LaunchLoginFlow.kt
> +fun LaunchLoginFlow(
Ah you were right, I changed it

2023-01-04 21:33 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/LaunchLoginFlow.kt
> +            neevaUser.queueOnSignIn(uniqueJobName = "Welcome Flow: onSuccessfulSignIn") {
Ah yeah so the rememberCoroutineScope wouldn't be useful since the screen might change due to the app getting refreshed because of OS memory prioritization

2023-01-04 21:38 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            Timber.e("Unable to launch Purchase Flow because product details is null.")
Ideally the `buy` function wouldn't be called if the product details == null. 

The Purchase Subscription screen which will trigger the buy function will only be showed if the product details != null. I think that's enough gating to make sure this doesn't happen? My Timber log here was mainly just defensive coding for the developer in case they were trying to use this without checking `productDetails`

2023-01-04 21:40 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +                coroutineScope.launch(dispatchers.main) {
Yeah

2023-01-04 21:50 UTC, Kokobe commented on app/src/main/java/com/neeva/app/userdata/NeevaUser.kt
> +        jobsToRun.removeIf { it.uniqueJobName == uniqueJobName }
Yeah that's fine. I don't want an old job to be running in the queue because:

If the user launches the flow and then decides not to login and then they decide to login again but with different parameters (like a different subscription plan choice), the old job would stay in the queue and the new job with the right parameters would be ignored. 

HOWEVER, I do realize now that this job would still get executed if they decided to not login in until later... which means navigation to the WelcomeFlowActivity can happen while in NeevaActivity which will crash the app

2023-01-04 22:00 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/createaccount/CreateAccountScreen.kt
> +        if (setDefaultAndroidBrowserManager.isNeevaTheDefaultBrowser()) {
Going to put the logic in FirstRunModel in a follow-up PR!

2023-01-04 22:49 UTC, dan-alcantara-neeva approved these changes

2023-01-05 04:10 UTC, merged