Welcome Flow: Navigation Refactoring + more Login Support
neevaco/neeva-android pull request #1177
Opened 2023-01-05 07:03 UTC by Kokobe

* [Refactor some navigation logic to live in FirstRunModel](https://github.com/neevaco/neeva-android/commit/fd7d205de3fd97653eaed16eb4744b403241fbe5)
* [Add LoginFlowNavModel to keep back stack shallow](https://github.com/neevaco/neeva-android/commit/976567d53f3317cc61455b8c8255af85cfcff20f)
* [Add support for where app navigation leads after a login](https://github.com/neevaco/neeva-android/commit/57df4269f8257266ae7e81551c858b68b50b18b4)

How login works in this PR:
* In the very First Run of the app, the login buttons will set the `activityToReturnToAfterLogin` to be `WelcomeFlowActivity` and the `screenToReturnToAfterLogin` to be `SET_DEFAULT_BROWSER` (or `FINISH_WELCOME_FLOW` if the default browser is already set to Neeva before launching FirstRun -- edge case)
* If the login is triggered from Settings or the Browser, the `activityToReturnToAfterLogin` will be `NeevaActivity` and the screen will be respectively the Settings or Browser screen.
* 
* The login will happen in the `SingleTabActivity` which will then start an Intent back to the Neeva app once logged in.
* MainActivity will catch this intent, update the cookie jar and cached cookie with the new login cookie, and then open the specified activity based on `activityToReturnToAfterLogin` stored in `SharedPreferences`. 
* The `NeevaActivity` and `WelcomeFlowActivity` both have functions to process this cookie and open the right `screen` based on the `screenToReturnToAfterLogin` stored in `SharedPreferences`. 

## Checklists

### Pointers to help with review
* https://www.figma.com/file/dylvDPB69JG9U1rzZ3HQ52/Android-Premium?node-id=0%3A1&t=i9BOuz5zR0S5EZxX-0

### How was this tested?
- [x] I tested this manually on `debug`
- [x] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [x] I checked that `@Previews` still work in Android Studio

### Manual test cases
Login from Settings
Login from Spaces prompt
Login from FirstRun 

### Screenshots and screen recordings
Login from Settings
TBD
Login from Spaces prompt
TBD
Login from FirstRun 
TBD

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2023-01-05 17:15 UTC, dan-alcantara-neeva commented
LMK when all the TBDs in your PR description are ready and the tests are passing

2023-01-06 21:09 UTC, dan-alcantara-neeva requested changes

2023-01-06 21:09 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +
remove newline

2023-01-06 21:09 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
>                      LoginCallbackIntentParams.fromLoginCallbackIntent(intent)?.let { params ->
How much of this code is shared with the one in MainActivity?  Is this code going to be necessary once your flag is flipped on?

2023-01-06 21:09 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/appnav/AppNavModelImpl.kt
> +    override fun showSettings() = show(AppNavDestination.SETTINGS) {
This part of the code is for simple function redirects without any logic; move your changed functions down below into a new section

2023-01-06 21:09 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            tag == null ||
Can you describe what you think this conditional is doing?  The conditions all seem to poorly interact with each other because you're using `||` instead of `&&`.

2023-01-06 21:11 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +        if (firstRunModel.shouldLogFirstLogin()) {
Forgot to send this one yesterday; ignore

2023-01-06 23:24 UTC, Kokobe commented on app/src/main/AndroidManifest.xml
> +            android:noHistory="true"
Ah I don't know why I'm getting the same behavior with noHistory=true be included or excluded... I'll delete it, for some reason I saw that when you pressed the back button after logging in, it would lead you back to the SingleTabActivity.

This is no longer the case, i'll delete the noHistory thing

2023-01-06 23:25 UTC, Kokobe commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +            // TODO(kobec): when FirstRunActivity is removed, the comment below won't make sense
Basically, I'm predicting that the comment might not make sense when FirstRunActivity is removed. The TODO is there for me to remember to think about it... is that okay?

2023-01-06 23:41 UTC, Kokobe commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
>                      LoginCallbackIntentParams.fromLoginCallbackIntent(intent)?.let { params ->
The cookie updating is actually shared between MainActivity and NeevaActivity. Currently kept it that way because the one in MainActivity only works for the new WelcomeFlow. 

You are absolutely right that I should add a TODO to clean up this code when FirstRunActivity is deleted.

2023-01-06 23:50 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            tag == null ||
Ah the tag == null is unnecessary. All i really need to check is:
tag != BillingSubscriptionPlanTags.MONTHLY_PREMIUM_PLAN &&
            tag != BillingSubscriptionPlanTags.ANNUAL_PREMIUM_PLAN

The || should've been an &&... thank you for catching that

2023-01-06 23:51 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            tag == null ||
Basically: we shouldn't allow the user to buy a subscription if it isn't the MONTHLY or ANNUAL tag.

2023-01-06 23:53 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientWrapper.kt
> +        return suspendCancellableCoroutine { continuation ->
I was actually getting this error from the billing connection stuff: 

<img width="1155" alt="Screen Shot 2023-01-05 at 1 50 41 PM" src="https://user-images.githubusercontent.com/20916043/211118604-45129632-7efc-4a16-bc9a-c7bc6f93fd5c.png">


Which means that I called `continuation.resume()` on a continuation that is no longer active. This happens because there are 2 callback functions (one of them is unreliable but may still fire `onBillingServiceDisconnected()`) that call `continuation.resume()`

2023-01-06 23:54 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientWrapper.kt
> +        return suspendCancellableCoroutine { continuation ->
Had to change the `suspendCoroutine` to `suspendCancellableCoroutine` because only the latter offers the ability to check if a continuation is active.

2023-01-06 23:55 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +
I think the string file looks better when the strings are separated by a newline though

<img width="832" alt="Screen Shot 2023-01-06 at 3 55 39 PM" src="https://user-images.githubusercontent.com/20916043/211118828-2edc7268-061e-44e5-8902-1b1ec97f67bd.png">

2023-01-06 23:56 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +
oh there's weird invisible spaces

2023-01-06 23:57 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +            // TODO(kobec): when FirstRunActivity is removed, the comment below won't make sense
Try to be clear about what you're landing as a note when you land it in case someone else has to pick it up; I've had to clean up other people's TODOs relatively often in the past

2023-01-07 00:03 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +            // TODO(kobec): when FirstRunActivity is removed, the comment below won't make sense
Also "Since this is will be the normal way to launch the app." doesn't make a lot of sense...

2023-01-07 00:04 UTC, dan-alcantara-neeva approved these changes
Fix your TODO comment, but otherwise lgtm

2023-01-07 01:00 UTC, Kokobe commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +            // TODO(kobec): when FirstRunActivity is removed, the comment below won't make sense
Going to work on this in the very next pr (this weekend). deleted the TODOs

2023-01-07 01:54 UTC, merged