Use WelcomeFlow for all Login paths
neevaco/neeva-android pull request #1184
Opened 2023-01-08 17:43 UTC by Kokobe

Uses `WelcomeFlowActivity` for login from Settings and `SpacesIntro` and FirstRun. Release users will not see the Plans screen in this flow because billing is disabled by default.

## Checklists

### Pointers to help with review
* https://www.figma.com/file/dylvDPB69JG9U1rzZ3HQ52/Android-Premium?node-id=0%3A1&t=1NHhtmFIyibxIQlO-0
* Discussion on SpacesIntro sign-in/sign-up behavior: https://neevaco.slack.com/archives/C03PQUPJJDP/p1672957695253199

### How was this tested?
- [x] I tested this manually on `debug`
- [x] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [x] I checked that `@Previews` still work in Android Studio

### Manual test cases
Sign-in from FirstRun -> success + shows no Plans
Sign-up from FirstRun -> success + shows no Plans

Sign-in from Settings -> Shows Plans (when Billing enabled)
Sign-in from SpacesIntro -> does not show Plans (when Billing enabled)
Sign-up from SpacesIntro -> show Plans (when Billing enabled)

### Screenshots and screen recordings
Sign-in from FirstRun -> success + shows no Plans
Sign-up from FirstRun -> success + shows no Plans

Sign-in from Settings -> Shows Plans (when Billing enabled)
Sign-in from SpacesIntro -> does not show Plans (when Billing enabled)
Sign-up from SpacesIntro -> show Plans (when Billing enabled)

2023-01-10 18:32 UTC, dan-alcantara-neeva requested changes

2023-01-10 18:32 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/firstrun/WebSignInFlowTest.kt
> +        (androidComposeRule as AndroidComposeTestRule<TestRule, NeevaActivity>).apply {
lol well that's one way to work around that.  For future reference, when you're doing one of these casts in production app code, you should be using `as?` to see if the cast is actually valid.  Otherwise it's just like doing an `!!` on a nullable thing and hoping it's correct.

2023-01-10 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +        startDestination = when {
Add a comment to describe how each of these destinations make sense given the conditional.  I'm not following why `billingEnabled` is the condition that sends you to the plans or the account creation screen...  Would also help to clarify what `signInOnly` means.

2023-01-10 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            // No valid screens to return to, so do nothing.
Can you clarify what "doing nothing" means here?

2023-01-10 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +        setupFirstScreen()
Calling `setupFirstScreen` after `onNewIntent` is weird.  `onNewIntent` is called after the app has already been opened, so it's not really the first screen anymore.

2023-01-10 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/PlansScreen.kt
> +    if (selectedTabIndex > subscriptionPlans.size || selectedTabIndex < 0) {
Use `.coerceIn` to force it in bounds, instead.

2023-01-10 20:53 UTC, Kokobe commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +                // Tell the user something went wrong and that they couldn't be
The only exception where I would load the neeva home page is if a sign-in failed or you sign in from the browser (both of which I'll double check that it will work)

2023-01-10 21:20 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +                // Tell the user something went wrong and that they couldn't be
That's what the API says: load the final path after you finish login.  Final path is almost always the home page.

2023-01-10 21:21 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +                // Tell the user something went wrong and that they couldn't be
In the case where the user started trying to log in from a search result page, then the final path _should_ be the search result page, but the app wasn't set up that way.

2023-01-10 23:03 UTC, Kokobe commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +                // Tell the user something went wrong and that they couldn't be
Offline conversation: decided that changing the behavior of how `finalPath` interacts with what we open up in the tab was:

1. Out of scope of Premium Subscriptions
2. Can muck with the API and how the back-end operates
3. Handling the 10% of users who don't know that the website they want to save to Spaces is in a different tab is an edge case

2023-01-10 23:15 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +        startDestination = when {
Will rehash in the code comments too:

`billingEnabled` is a boolean variable that is dependent on whether the user is able to purchase Premium or not. If they can't purchase Premium then they shouldn't be shown the `Plans` screen. (also reflected in the figma). I'll change the name of this variable to `isPremiumPurchaseAvailable`

the signInOnly variable determines if a user wants to use this activity only for signing in.

2023-01-10 23:17 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            // No valid screens to return to, so do nothing.
Updated the comment to:
There are no valid screens to return to, so no manual setting of which screen to start on is needed.

2023-01-10 23:18 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +        setupFirstScreen()
I'm basically just trying to change the starting screen of this activity. I'll rename it to that

2023-01-10 23:45 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                // Don't automatically show the Browser
// Set onLoadStarted to an empty lambda so that the tab is opened by the user is sent to the correct screen.

2023-01-10 23:46 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                // Logging if we are the default browser when a user views a URL with this app.
// Logs if the app is set as the system's default browser when we are asked to handle a VIEW Intent.

2023-01-10 23:48 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            canPurchasePremium && signInOnly == false -> Destinations.PLANS.name
How does `sign up` correspond to your `signInOnly` field?  I still think it's named in a confusing way

2023-01-10 23:48 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                Destinations
1. Formatting is weird.
2. If you have to break a new line like this, add braces

2023-01-10 23:51 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                                navigateToSetDefaultBrowser =
Indentation is weird; just use braces and call the function normally

2023-01-10 23:52 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                                isSignedOut = !neevaUser.isSignedOut(),
This conditional looks backwards?  Why are you negating it?

2023-01-10 23:52 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                                welcomeFlowNavModel::showCreateAccountWithOther,
Use braces instead of `::` notation

2023-01-10 23:56 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                                isSignedOut = !neevaUser.isSignedOut(),
Agh that was a typo, thanks for catching that

2023-01-11 00:00 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            canPurchasePremium && signInOnly == false -> Destinations.PLANS.name
Ah you can either start the WelcomeFlowActivity as signing up or signing-in. Mutually exclusive XOR, but I see how it is confusing. I'll make separate variables based on signInOnly:

```
val usingActivityForSignUp = !signInOnly == false
val usingActivityForSignIn = signInOnly
```

2023-01-11 01:28 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            canPurchasePremium && signInOnly == false -> Destinations.PLANS.name
Don't those two fields evaluate to the same value?

2023-01-11 01:34 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            canPurchasePremium && usingActivityForSignUp -> Destinations.PLANS.name
Combine these two under the `usingActivityForSignup` check:

```
usingActivityForSignUp -> {
    if (canPurchasePremium) {
        Destinations.PLANS.name
    } else {
        Destinations.CREATE_ACCOUNT_WITH_GOOGLE.name
    }
}
```

2023-01-11 01:35 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            canPurchasePremium && signInOnly == false -> Destinations.PLANS.name
SignUp means:
- Show Plans
- Show Sign Up screen
- Show set default browser if they chose a non-free Plan

2023-01-11 03:37 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> -                loginToken.isNotEmpty() -> false
@dan-alcantara-neeva anticipating your possible concern with this:

Since you are able to login from the WelcomeFlowActivity (which is now the new FirstRun) but not finish the WelcomeFlowActivity, you can get into a state where `finishWelcomeFlow()` is never called but `firstRunModel.mustShowFirstRun()` returns `false`. 

An example path of how to get here was:
1. Start the Neeva app for the first time
2. Neeva App: Opens Welcome Screen
3. Press "I have an account button"
4.  Neeva App: Open Sign-in Screen and Sign in
5.  Neeva App: redirects you to the Set Default Browser Screen
6. (at this point, firstRunModel.mustShowFirstRun() is wrongly returning false because the loginToken is not empty)
7.  Press back all the way to the Sign in Screen 
8. Sign in again
9. Neeva App: Brings you to ZeroQuery because after a sign-in & mustShowFirstRun() == false (we actually expect it to open the Set Default Browser Screen. 

The definition of `mustShowFirstRun()` needed to be changed because you can now login in FirstRun.

2023-01-11 20:17 UTC, dan-alcantara-neeva requested changes

2023-01-11 20:17 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/logging/ClientLogger.kt
> +        if (loginToken.isNotEmpty() && !FirstRunModel.mustShowFirstRun(sharedPreferencesModel)) {
Talked over Zoom, but I think this conditional is also wrong.

* `addPendingLog` is a call we make to queue up logs to send when the user has finished first run.  We actively avoid sending anything until we're sure they've had a chance to say that they're OK with us sending logs, which means that they've gotten through the first screen of the flow.

* Because of the way SharedPreferences are _not_ set when we try to read them, we can't be certain that older users have seen first run or not.  We used "the user is signed in" as a substitute signal for that.

* This conditional is backwards from what it used to do, which means that we won't be sending any logs at all if the user has signed in && have completed first run, and will instead be sending logs (possibly without permission) in every other situation.

2023-01-11 20:17 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +    private var initialLoginParams = mutableStateOf<LoginReturnParams?>(null)
1. `mutableState` is a Compose thing.
2. Do you need a `mutableState` that is observable?  You seem to be using it as a boolean var everywhere.

2023-01-12 01:22 UTC, Kokobe commented on app/src/main/java/com/neeva/app/logging/ClientLogger.kt
> +        if (loginToken.isNotEmpty() && !FirstRunModel.mustShowFirstRun(sharedPreferencesModel)) {
Made a fix for this in `MainActivity`. See `startUpWithoutLogin()`. 

When you open the app without a login intent, it will run the following conditional which decides which activity to open:

```
val activityClass = if (loginToken.isEmpty() && firstRunModel.mustShowFirstRun()) {
            WelcomeFlowActivity::class.java
        } else {
            firstRunModel.setFirstRunDone()
            NeevaActivity::class.java
        }
```

2023-01-12 01:23 UTC, Kokobe commented on app/src/main/java/com/neeva/app/logging/ClientLogger.kt
> +        if (loginToken.isNotEmpty() && !FirstRunModel.mustShowFirstRun(sharedPreferencesModel)) {
Any user that is already logged in will skip the WelcomeFlowActivity and have the sharedPref set that FirstRun is done. 

Users that are NOT logged in but have `FirstRunDone` == false, will see the WelcomeFlowActivity... and eventually have the FirstRunDone set to true in their shared preferences.

2023-01-12 01:26 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +    private var initialLoginParams = mutableStateOf<LoginReturnParams?>(null)
I need `mutableState` to cause the composables that use `initialLoginParams` (see `CreateAccountScreen`) to recompose and change what screen/activity to return to after login.

The reason we need a recomposition is if an old WelcomeFlowActivity is reused, the CreateAccountScreen screen Compose is showing is also old and has the incorrect `initialLoginParams` value. When that value changes (due to a `onNewIntent()` call), the UI will correctly recompose with the right loginReturnParams

2023-01-12 01:28 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +    private var initialLoginParams = mutableStateOf<LoginReturnParams?>(null)
Though it might not be a problem anymore because we set the WelcomeFlowActivity to `android:excludeFromRecents="true"`. This is more just "defensive coding" to protect for old state messing with the current state.

2023-01-12 01:34 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +    private fun startUpWithoutLogin() {
`startUpWithoutLogin` sounds like you're trying to start the app up without logging in.  That codepath would also be triggered if you were logged in already, or if there was no login intent.

2023-01-12 01:34 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +        removeSingleTabActivityFromRecents()
Explain why you're doing this here.

2023-01-12 01:35 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +        } catch (e: java.lang.Exception) {
Be more descriptive, or don't log it at all.  Also, you might be importing the wrong `Exception` class.

2023-01-12 01:35 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +            // TODO(kobec not yusuf):  mktEmailOutput https://github.com/neevaco/neeva-ios/blob/a714a70058dcedf4b5d019f8f097326c7bbc9894/Shared/NeevaConstants.swift#L270-L288
File issue or track it

2023-01-12 01:36 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +            context.applicationContext,
Say that you're doing this to force the `SingleTabActivity` to show up in its own task, and why that's important.

2023-01-12 01:37 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
> +                // To actually tell the browser cookie jar is up to date, we have to ask the
tell if the

2023-01-12 01:37 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
> +                if (isBrowserAlive && currentCookieValue != cachedValue) {
Feels like this should be an or instead... what gets passed in for `onFailure`?

2023-01-12 01:39 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
>              clientLogger = clientLogger
Can you move `setDefaultAndroidBrowserManager = blah blah` earlier?  I don't think you actually need to hold off on putting it this low, and you might again get into a scenario it isn't set on time.

2023-01-12 18:52 UTC, Kokobe commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +    private fun startUpWithoutLogin() {
How does `startUpWithoutLoginIntent` sound?

2023-01-12 18:55 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +            // TODO(kobec not yusuf):  mktEmailOutput https://github.com/neevaco/neeva-ios/blob/a714a70058dcedf4b5d019f8f097326c7bbc9894/Shared/NeevaConstants.swift#L270-L288
I'll do it in the next commit actually

2023-01-12 19:41 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +            context.applicationContext,
Do you remember why it is important anymore? 

I originally thought it was so that `onNewIntent()` will be called whenever we launch a `SingleTabActivity`, but it has the same exact behavior (both call onNewIntent() appropriately) with or without the application context.

2023-01-12 19:42 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +            context.applicationContext,
Yeah, we changed the AndroidManifest to force that behavior instead.  It's up to you to keep it or not

2023-01-12 19:55 UTC, Kokobe commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
> +                if (isBrowserAlive && currentCookieValue != cachedValue) {
Ah i assumed that if the browser wasn't alive then the cookie can't have possibly been set. 

Totally wrong, I should just check the current cookie value

2023-01-12 19:56 UTC, Kokobe commented on app/src/main/java/com/neeva/app/userdata/SessionToken.kt
> +                if (isBrowserAlive && currentCookieValue != cachedValue) {
onFailure() is just the code that says `popupModel.showSnackbar(getString(R.string.error_generic))`

2023-01-12 22:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/appnav/AppNavModel.kt
> +    fun showWelcomeFlow(loginReturnParams: LoginReturnParams, signInOnly: Boolean)
Clarify what `signInOnly` means here so that callers don't accidentally assume that it means something else.

2023-01-12 22:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/defaultbrowser/SetDefaultAndroidBrowserManager.kt
> +    abstract fun requestToBeDefaultBrowser(callback: (Boolean) -> Unit)
Can you name the boolean in this callback?

2023-01-12 22:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/defaultbrowser/SetDefaultAndroidBrowserPane.kt
> +    onActivityResultCallback: (Boolean) -> Unit,
name the boolean if possible

2023-01-12 22:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/PlansScreen.kt
> +    val onBackToUse = if (showBackButton) {
This API is a little weird... can you pass `onBack` down to `PlansScreen` and then tell it whether or not `showBackButton` is true or false?

2023-01-12 22:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                            LaunchedEffect(true) {
newline above

2023-01-12 22:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                                welcomeFlowNavModel::showCreateAccountWithGoogle,
use braces to avoid the wonky indentation

2023-01-12 22:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                if (this::navHost.isInitialized) {
Why do you need the `this::` in so many places?

2023-01-12 22:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +    private fun getOnContinueInPlansScreen(): () -> Unit = {
What's with the equals sign in this function definition?

2023-01-12 22:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +            when {
1. Was this code duplicated somewhere else? 
2. Pass in a single lambda that calls the correct function instead of passing in all the lambdas and pushing the logic down here

2023-01-12 23:11 UTC, Kokobe commented on app/src/main/java/com/neeva/app/appnav/AppNavModel.kt
> +    fun showWelcomeFlow(loginReturnParams: LoginReturnParams, signInOnly: Boolean)
Okay, but will remove the comment in the next PR 

Follow-up PR is going to do add a `Purpose` where it should be clear what we are doing with `showWelcomeFlow()` : https://github.com/neevaco/neeva-android/blob/939b3a1c9edaf18b2c485589120287f102eaf717/app/src/main/java/com/neeva/app/appnav/AppNavModel.kt

2023-01-12 23:20 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                if (this::navHost.isInitialized) {
The only way to safely check if a `lateinit` has been initialized is to use `this::[variable name].isInitialized`

see: https://stackoverflow.com/questions/37618738/how-to-check-if-a-lateinit-variable-has-been-initialized

2023-01-12 23:21 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +    private fun getOnContinueInPlansScreen(): () -> Unit = {
Bad syntax by me

2023-01-12 23:29 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +            when {
Agh great advice! thank you

2023-01-12 23:35 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/widgets/texts/EmailPromoCheckbox.kt
> +        firstRunModel.mktEmailOptOutState.value = !firstRunModel.mktEmailOptOutState.value
This code should be in the model itself.  You're pulling the value of a boolean out and then setting it back in the same place

2023-01-12 23:37 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                                onBack = if (!firstRunModel.mustShowFirstRun()) {
Maybe use `takeIf`?  Don't know if it's more or less readable

2023-01-12 23:38 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            isPremiumPurchaseAvailable() -> welcomeFlowNavModel.showPlans()
Be stylistically consistent with `onContinueInPlansScreen`: Use brackets and code blocks

2023-01-12 23:49 UTC, dan-alcantara-neeva approved these changes

2023-01-13 05:29 UTC, merged