Kobe/premium fix buy
neevaco/neeva-android pull request #1192
Opened 2023-01-13 08:37 UTC by Kokobe

General description of what your PR does, written in a way that someone six
months from now could understand what you were doing when tracking down a bug
or attempting to add new functionality

* More details about the changes
* Even more details about the changes
* Yet more details about the changes

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2023-01-13 18:10 UTC, dan-alcantara-neeva commented
The bottom sheet on top of the set default browser screen looks a little odd; can you send these videos to UX and confirm that these look OK?

2023-01-13 18:32 UTC, dan-alcantara-neeva requested changes

2023-01-13 18:32 UTC, dan-alcantara-neeva commented on app/src/main/res/values/donottranslate.xml
> +    <string name="settings_debug_launch_welcome_flow">Launch welcome flow and simulate FirstRun</string>
First Run is two words in a sentence

2023-01-13 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/userdata/NeevaUser.kt
> +            job()
This means that you're bypassing the queue and starting your job immediately, allowing two unique jobs to be started for the same thing.  Why'd you switch?

2023-01-13 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/appnav/AppNavModelImpl.kt
> +                ACTIVITY_TO_RETURN_TO_AFTER_WELCOMEFLOW_KEY,
Be consistent; "welcome flow" is two words on line 213 and one line here.

2023-01-13 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/appnav/AppNavModelImpl.kt
> +        loginReturnParams: LoginReturnParams?,
Why is this allowed to be null now?  Just for your debug case?  What happens if production code calls this with a null value now that that is allowed?

2023-01-13 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +        val selectedSubscriptionTag = subscriptionManager.selectedSubscriptionTagState.value
Intents are inherently unsafe: anyone can fire one with any payload and we'll process it the same way unless we guard against it.  That means that someone could craft an Intent with a subscription tag and we'll presumably show the billing flow to ask them to fulfill that.  Can you store that anywhere else, like a SharedPreference?

2023-01-13 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        val offers = productDetailsFlow.value
one line

2023-01-13 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
>          // TODO(kobec): add obfuscatedUserID != null &&
What does this TODO mean and when were you expecting to complete it?

2023-01-13 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        // TODO(kobec): clear this when you finish welcome flow and make sure it doesn't trigger
Why is this just a TODO?  Can you put it in this PR?

2023-01-13 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +    // TODO(kobec): Remove this
What does this mean?

2023-01-13 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            // TODO: remove this when we figure out how we persist default values for new users
Still applicable?  You filed an issue about actually setting default values for the sharedprefs when reading them, right?

2023-01-13 18:41 UTC, Kokobe commented on app/src/main/java/com/neeva/app/MainActivity.kt
> +        val selectedSubscriptionTag = subscriptionManager.selectedSubscriptionTagState.value
Great callout

2023-01-13 18:42 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
>          // TODO(kobec): add obfuscatedUserID != null &&
This is for back-end collaboration... I'll make an issue

2023-01-13 18:43 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +    // TODO(kobec): Remove this
Ah I meant to do that last night, I'll do it today. Basically this parameter isn't being used in the file so I'll remove it

2023-01-13 21:18 UTC, Kokobe commented on app/src/main/res/values/donottranslate.xml
> +    <string name="settings_debug_launch_welcome_flow">Launch welcome flow and simulate FirstRun</string>
Changing it to "Simulate FirstRun"

2023-01-13 22:04 UTC, Kokobe commented on app/src/main/java/com/neeva/app/userdata/NeevaUser.kt
> +            job()
Ah you're right, there's a race condition here.

I didn't want a situation where job queueing happens in this order:
1. User signs in 
2. queueOnSignIn(someJob())
3. someJob() is never run because jobs are only run when the userInfo changes

2023-01-13 22:05 UTC, Kokobe commented on app/src/main/java/com/neeva/app/userdata/NeevaUser.kt
> +            job()
I'll add a mutex to fix the race condition

2023-01-13 22:19 UTC, Kokobe commented
> The bottom sheet on top of the set default browser screen looks a little odd; can you send these videos to UX and confirm that these look OK?

I don't think there's anything we can do about the top bar since its a native Google UI?

2023-01-13 22:22 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            // TODO: remove this when we figure out how we persist default values for new users
I thought I did, but I couldn't find any issues with "SharedPreference" in them. Filed one here: https://github.com/neevaco/neeva-android/issues/1196

2023-01-13 22:24 UTC, Kokobe commented on app/src/main/java/com/neeva/app/appnav/AppNavModelImpl.kt
> +        loginReturnParams: LoginReturnParams?,
Yeah it is just for my debug case... you're right, I'll make a separate function just for debug

2023-01-13 23:42 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        // TODO(kobec): clear this when you finish welcome flow and make sure it doesn't trigger
Outdated TODO!

2023-01-14 04:57 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
>          // TODO(kobec): add obfuscatedUserID != null &&
https://github.com/neevaco/neeva-android/issues/1198

2023-01-14 18:08 UTC, dan-alcantara-neeva requested changes

2023-01-14 18:08 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                        clearSelectedSubscriptionTag()
1. You read this tag in two places but clear it in only one (not where you set up the LoginReturnParams).  Is that sufficient?
2. This will only clear the tag if the user has successfully signed in, which means that if the user fails to be signed in, the tag will stay there until that happens.  So, if the user leaves the app at some point during the flow and comes back, we'll see that there's a SharedPreference set and then show this dialog again.  Can't this cause the user to see a dialog at the wrong time, like if they bailed out of the Welcome Flow at some point, then signed in at some point later?

2023-01-14 18:08 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            selectedSubscriptionPlanTag = subscriptionManager.getSelectedSubscriptionTag(),
Do you still use this?

2023-01-14 18:09 UTC, dan-alcantara-neeva commented
> > The bottom sheet on top of the set default browser screen looks a little odd; can you send these videos to UX and confirm that these look OK?
> 
> I don't think there's anything we can do about the top bar since its a native Google UI?

Not the top bar; it's just a bottom sheet that is part of Google's API.  I was wondering if it'd make sense to show a different background than the set default browser screen.

2023-01-15 00:59 UTC, Kokobe commented
> > > The bottom sheet on top of the set default browser screen looks a little odd; can you send these videos to UX and confirm that these look OK?
> > 
> > 
> > I don't think there's anything we can do about the top bar since its a native Google UI?
> 
> Not the top bar; it's just a bottom sheet that is part of Google's API. I was wondering if it'd make sense to show a different background than the set default browser screen.

No the top bar is being blanked out is part of Google's UI, check out this Billing Flow from Evernote:

https://user-images.githubusercontent.com/20916043/212503713-0b5cc04f-2384-45cf-9aae-436db6d77903.mp4

2023-01-15 01:05 UTC, hwiatneeva commented
> > > > The bottom sheet on top of the set default browser screen looks a little odd; can you send these videos to UX and confirm that these look OK?
> > > 
> > > 
> > > I don't think there's anything we can do about the top bar since its a native Google UI?
> > 
> > 
> > Not the top bar; it's just a bottom sheet that is part of Google's API. I was wondering if it'd make sense to show a different background than the set default browser screen.
> 
> No the top bar is being blanked out is part of Google's UI, check out this Billing Flow from Evernote:
> 
>  20230114-165814.mp4

@Kokobe @dan-alcantara-neeva 

I recommend we show the default browser UI underneath the billing bottomsheet (lmk if i'm responding to a wrong point...).

There's no ideal page underneath. if we squeeze in an idea, we could show the plans page without the signin link at the bottom, assuming a failure case instead of navigating to the DB.... -- just a nice-to-have for a small case of, oh i changed my mind to choose other plan...). But proceeding to DB, and catch such cases in later e.g. via banner / setting is also a viable path. I recommend the latter, not the former at all.

2023-01-15 01:12 UTC, Kokobe commented
Will make the navigation changes + the billing flow callback happen in a new PR

2023-01-15 01:18 UTC, hwiatneeva commented
Looked all videos + saw the first 3 screens (no billing) on the device light & dark:  LGTM from design. Thanks @Kokobe & @dan-alcantara-neeva !!!!!!!!!!!!!!!!!!!!

2023-01-15 01:43 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                        clearSelectedSubscriptionTag()
1. I think it makes sense to only clear the tag when `buy()` has been called (which only pulls up that Google Billing Bottom Sheet). 

The reason I did that was because when you switch between Activities, that buy() needs to be requeued but using the new Activity. The way I know there needs to be a buy() that gets requeued is through this tag stored in SharedPreferences.
(Though this logic will change now since Hwi suggested we keep all the billing flow stuff in the WelcomeFlowActivity). 

2. You're totally right, that could happen. 

The solution is to clear the selectedSubscriptionTag on app start-up, will do that now

2023-01-15 02:08 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                        clearSelectedSubscriptionTag()
But... there isn't a solid way to know when that happens because `onDestroy` doesn't always get called.

2023-01-15 02:13 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                        clearSelectedSubscriptionTag()
I take back my comment, I will only let the Billing Flow happen within the `WelcomeFlowActivity` and follow Hwi's feedback in this PR. 

That way, if a user opens up the app in NeevaActivity, we have 2 things keeping the BillingFlow from popping up:
1. the weak reference to WelcomeFlowActivity will return null and the buy function cannot happen
2. NeevaActivity will no longer be `queueBuyPremiumOnSignInIfSelected()` when processing a `ACTION_SHOW_SCREEN_AFTER_LOGIN` intent

2023-01-15 08:10 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +            selectedSubscriptionPlanTag = subscriptionManager.getSelectedSubscriptionTag(),
Now I do :-)

2023-01-15 09:08 UTC, Kokobe commented
Updated the videos in the PR description

2023-01-17 19:25 UTC, dan-alcantara-neeva approved these changes

2023-01-17 20:44 UTC, merged