Kobe/premium fix long load
neevaco/neeva-android pull request #1199
Opened 2023-01-14 20:49 UTC by Kokobe

General description of what your PR does, written in a way that someone six
months from now could understand what you were doing when tracking down a bug
or attempting to add new functionality

* More details about the changes
* Even more details about the changes
* Yet more details about the changes

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Fixes #1198

2023-01-17 21:52 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/userdata/NeevaUserTest.kt
> +            billingClientController = billingClientController,
Unnecessary comma changes; revert all of these to make the PR cleaner

2023-01-17 21:56 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +    var onLetsGo = { }
Can you just use a regular if statement here instead of this funky `?.let` block?

2023-01-17 21:58 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/SettingsController.kt
> +                when (canPurchasePremium) {
This is just an if statement.

2023-01-17 22:01 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                                onContinueInWelcomeScreen = onContinueInWelcomeScreen(),
This function name and invocation are misleading: you're calling a function to create another function that is actually called when the user hits the button.  Instead of doing that, can you just call the function like you used to and make that do the correct checks?

2023-01-17 22:01 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +    private fun onContinueInWelcomeScreen(): (() -> Unit)? {
Why is this a Composable?

2023-01-17 22:02 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            if (!settingsDataModel.getSettingsToggleValue(SettingsToggle.DEBUG_ENABLE_BILLING))
Always put braces when it ends up on multiple lines

2023-01-17 22:03 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                Log.v(
Timber, not Log.

2023-01-17 22:06 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +    private fun onContinueInWelcomeScreen(): (() -> Unit)? {
I wanted to make the WelcomeScreenComposable re-compose itself whenever the `isBillingAvailableFlow` changed see: `val isBillingAvailable = subscriptionManager.isBillingAvailableFlow.collectAsState().value`

I can pull that out though and make this function not a Composable

2023-01-17 22:06 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +                    if (shouldAssumeFailureForNow) {
What is `shouldAssumeFailureForNow` supposed to mean?  Add it to the kdoc.

2023-01-17 22:08 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +    private fun onContinueInWelcomeScreen(): (() -> Unit)? {
It's a fragile link, regardless.  If you want to force something somewhere else to recompose when necessary, make the Composable have the logic for knowing when to trigger it -- not a callback that a button on that screen displays.

2023-01-17 22:09 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                Log.v(
But Timber doesn't work on release builds? I guess I can look into it and add it to the growing scope of Premium

2023-01-17 22:09 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +    var onLetsGo = { }
Good point lol

2023-01-17 22:10 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            isPremiumPurchaseAvailableFlow.collect {
Do you need this to stay alive after the first `it != null` condition is hit?  Can you make the job terminate itself so that it's not just constantly running?  There should be operators other than `collect` that would help you do that...

2023-01-17 22:11 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        coroutineScope.launch(dispatchers.io) {
You've introduced a Job that will run whenever `buy` is called.  Can you guarantee that `buy()` will only called once?  If not, you will end up with two Jobs running in parallel.

2023-01-17 22:11 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        val TAG = "SubscriptionManager"
No more tags; we're using Timber.

2023-01-17 22:14 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +    var onLetsGo = { }
Behavior is more of a UX question.  If the user is offline when they start the app, will this button ever be enabled?

2023-01-17 22:16 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                                onContinueInWelcomeScreen = onContinueInWelcomeScreen(),
I need to pass in a `isBillingAvailable` here because `onContinueInWelcomeScreen` depends on that variable. I'll rename the function to: `getOnContinueInWelcomeScreen()`

2023-01-17 22:20 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            if (!settingsDataModel.getSettingsToggleValue(SettingsToggle.DEBUG_ENABLE_BILLING))
This if statement is only 1 line, but I'll put braces around it anyways and add a log here

2023-01-17 22:21 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            if (!settingsDataModel.getSettingsToggleValue(SettingsToggle.DEBUG_ENABLE_BILLING))
If the return ends up on the next line, you have to add braces.

2023-01-17 22:33 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            isPremiumPurchaseAvailableFlow.collect {
Is calling `this@launch.cancel()` after `onResult(it)` happens an adequate way to do this? 

It will cancel the job created by `launch`, which will end the collecting when the `it != null` condition is hit

2023-01-17 22:35 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            isPremiumPurchaseAvailableFlow.collect {
Is there a `single` or something similar?  Might need to combine it with a filter

2023-01-17 22:39 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +    var onLetsGo = { }
Yes this button will be enabled in 1.3 seconds because of my `ATTEMPTS_TO_ASSUME_FAILURE` in `BillingClientController`.

Basically, if we the fetch ProductDetails job fails twice, we tell the the UI to assume the job failed and allow the user to move on to the next screen (not PLANS related). This doesn't mean we stop trying to fetch it (it's still happening with exponential backoff), but we allow the user to continue on. 

You can see this in my "FirstRun billing disabled" video in the PR description

2023-01-17 22:41 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +    var onLetsGo = { }
Are you just making the button do nothing by removing the onClick?  Can you properly mark the button as disabled so that it doesn't stay blue and look clickable?

2023-01-17 22:43 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +                    if (shouldAssumeFailureForNow) {
I've added documentation in `BillingClientController`'s `ATTEMPTS_TO_ASSUME_FAILURE` constant which is where the variable originates and is ultimately passed onto `FetchProductDetailsManager` and `FetchPurchasesManager`

2023-01-17 22:49 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            isPremiumPurchaseAvailableFlow.collect {
From what I'm reading it seems that `single` is still a `collect` that is constantly running. Why is single better? 

<img width="689" alt="Screen Shot 2023-01-17 at 2 48 57 PM" src="https://user-images.githubusercontent.com/20916043/213029195-19706dc3-7e0b-4a46-80e7-079673092599.png">

2023-01-17 22:50 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                Log.v(
We shouldn't be mixing and matching Timber and Log usage; we should be sticking with a single framework for logging our messages.  If Timber isn't good enough for what we need, we should rip it back out.

2023-01-17 23:48 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        val TAG = "SubscriptionManager"
Timber is still not working on release

2023-01-18 00:28 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                    )
ktlint moved this parenthesis here?

2023-01-18 00:29 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                Log.v(
Talked offline; it's fine to use Log for now because Timber isn't doing what we need in release builds.  Will revisit once the rest of the flow is in place.

2023-01-18 00:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                        onResult(true)
Still need this Job to be canceled so that it doesn't keep firing your callback

2023-01-18 06:13 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt
> +    var onLetsGo = { }
Lol! No but it wasn't clear since that logic was happening a level lower... I can move it up

2023-01-18 09:12 UTC, Kokobe commented
Updated the videos @dan-alcantara-neeva

2023-01-18 18:51 UTC, dan-alcantara-neeva requested changes

2023-01-18 18:51 UTC, dan-alcantara-neeva commented on app/src/main/res/values/strings.xml
> +    <string name="welcomeflow_loading">Loading</string>
Just make this a generic string called "loading" so that we can reuse it.

2023-01-18 18:51 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/appnav/ActivityStarter.kt
> +            options = ActivityOptionsCompat.makeCustomAnimation(
Just put this on one line; we can't even name what each argument is because it's a Java call.

2023-01-18 18:51 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        cancelPurchaseJobsAndResetScope()
Are you down to one `Job` being launched and the `coroutineScope` being used in one place?  Can you just hold onto a `Job?` instead of creating another CoroutineScope?  You can call `cancel()` on it when you're done and create a new one when needed.

2023-01-18 18:51 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        private var attempts = 0
Why is this on the companion object?

2023-01-18 18:51 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +        slowInternetConnectionTimer = coroutineScope.launch(dispatchers.io) {
This should be launched at the same time as the `fetchPurchases` call because you're timing that -- not when this class was first initialized.

2023-01-18 18:51 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/SharedComposables.kt
> +                CircularProgressIndicator(
1. It's a small thing, but Hwi wanted this to show up only after 300 milliseconds.
2. Also a small thing, but you could use a `Crossfade` composable that's dependent on the `enabled` flag as its `targetState` so that you could show the button fading as it goes from being disabled to enabled.

2023-01-18 21:57 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +        private var attempts = 0
moved it into the class, you're right only constants should be in here

2023-01-18 22:04 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/SharedComposables.kt
> +                CircularProgressIndicator(
Added this to a list of Polish action items, will punt on this issue for the next PR

2023-01-18 22:24 UTC, dan-alcantara-neeva approved these changes

2023-01-18 23:47 UTC, merged

2023-01-19 16:04 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +        slowInternetConnectionTimer = coroutineScope.launch(dispatchers.io) {
I think I asked you to move this offline; we want this to start when the job does and not when the class is initialized.

2023-01-31 15:09 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +        slowInternetConnectionTimer = coroutineScope.launch(dispatchers.io) {
Fixed this in #1235