Add ObfuscatedUserIDFlow Checks
neevaco/neeva-android pull request #1215
Opened 2023-01-21 23:42 UTC by Kokobe

Since the `InitializeGooglePlaySubscriptionMutation` (which generates the `obfuscatedUserID`) is live on M1, we can add more checks needed before making a purchase:

* Fixes #1197  by adding a check for it in the buy() function
* Fixes #1198 by wrapping the `ObfuscatedUserID` Flow in a wrapper class + including new checks in `isPremiumPurchaseAvailableFlow()`

## Checklists

### How was this tested?
- [x] I tested this manually on `debug`
- [x] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [x] I checked that `@Previews` still work in Android Studio

### Manual test cases
Enabled custom neeva domain M1 and then confirmed through the logs that the obfuscatedUserID was not null or empty before performing a `buy()` or `acknowledge`

## Issues addressed
* Fixes #1197 
* Fixes #1198

2023-01-23 07:10 UTC, dan-alcantara-neeva requested changes

2023-01-23 07:10 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            .take(1)
use `first()` instead of `take(1).single()`

2023-01-23 07:10 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +            .take(1)
.first()

2023-01-23 07:10 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +                            val obfuscatedUserID = billingClientController.collectObfuscatedUserID()
This call can block effectively forever if the condition in `collectObfuscatedUserID()` is never satisfied.  That means your queue can get completely jammed on `BillingClientController` on lines 138 or 143, doesn't it?

2023-01-23 07:12 UTC, dan-alcantara-neeva requested changes

2023-01-23 07:12 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +            .filter { it.isSet && !it.id.isNullOrEmpty() }
should `it.isSet && !is.id.isNullOrEmpty()` be a function on `ObfuscatedUserID`?

2023-01-24 05:59 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +                            val obfuscatedUserID = billingClientController.collectObfuscatedUserID()
Ah it definitely could. The only reasons it could get blocked is if Apollo never returns a result for the obfuscatedUserId or the user never signs in. 

I'll make this job launch a coroutine on the io thread so it doesn't block the job queue

2023-01-24 06:21 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +                            val obfuscatedUserID = billingClientController.collectObfuscatedUserID()
I'll add a timeout

2023-01-24 15:06 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +                            val obfuscatedUserID = billingClientController.collectObfuscatedUserID()
The way we built the queue ensure that we do one job at a time. So if one job gets blocked, it will naturally jam the queue as a side effect. Normally I would add a timeout to unblock the job (and therefore the queue), but it doesn't make sense to timeout this acknowledgement job here. 

It needs to be is waiting for the obfuscatedUserId so that we can register/verify this purchase with the back-end (the back-end needs it so it can identify the `purchaseToken` and see that is linked to the right `obfuscatedUserID`). Only then can we acknowledge the purchase. 

The only downside to blocking the queue is if the acknowledge job blocks `fetchPurchases` and `fetchProductDetails` jobs and we can never know if Google Billing is available to the user or not... until the user logs in. This can only happen if the Google Play Billing API calls onPurchasesUpdated() before the `fetchPurchases()`  and `fetchProductDetails()` jobs have been started.

2023-01-24 16:12 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +            .filter { it.isSet && !it.id.isNullOrEmpty() }
That combo isn't being reused anywhere else + I feel like it doesn't need a function name to explain what is happening

Though I did rename this collectObfuscatedUserID to `waitForValidObfuscatedUserID`

2023-01-24 20:15 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +                            val obfuscatedUserID = billingClientController.collectObfuscatedUserID()
Add a version of your comment to the code where the code can get blocked to show that you've thought about it and why you're making this tradeoff.

2023-01-25 00:57 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +                            val obfuscatedUserID = billingClientController.collectObfuscatedUserID()
Adding coroutine to wait for obfuscatedUserID to be null -> add job to queue to not block it.

2023-01-25 01:05 UTC, dan-alcantara-neeva approved these changes
LGTM, assuming you test this on the release build because this is still behind a flag.

2023-01-25 17:43 UTC, merged