Refactor billing ids to the new ones on Play Console
neevaco/neeva-android pull request #1217
Opened 2023-01-22 02:01 UTC by Kokobe

General description of what your PR does, written in a way that someone six
months from now could understand what you were doing when tracking down a bug
or attempting to add new functionality

* More details about the changes
* Even more details about the changes
* Yet more details about the changes

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2023-01-23 06:39 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/BillingSubscriptionPlanConstants.kt
> +    // Used in this project
Use regions or don't, don't mix and match

2023-01-23 07:02 UTC, dan-alcantara-neeva requested changes

2023-01-23 07:02 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +    ): ProductDetails? =
Use braces and return if you're going to put the equals sign on this line and put the rest of it on the next.  Otherwise, use `): ProductDetails? = suspendCoroutine { continuation ->` on the line same line so the `{}` line up like a normal function block

2023-01-23 07:02 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +                val annualProductDetails = collectProductDetails(it, ANNUAL_PREMIUM_SUB_ID)
Your first `collectProductDetails` call will cancel the `slowInternetConnection` timeout, which means that the second one can keep going without a timeout.

2023-01-24 17:01 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/BillingSubscriptionPlanConstants.kt
> +            ?.flatten()
<img width="917" alt="Screen Shot 2023-01-25 at 12 59 32 AM" src="https://user-images.githubusercontent.com/20916043/214358134-bab17899-890b-4f05-bfe5-44f69d8cbe5b.png">

`mapNotNull` essentially gives me a `List` of `Lists` of `SubscriptionOfferDetails` (`[ [ subscriptionOfferDetails1 ], [ subscriptionOfferDetails2] ]`)

Flatten allows me to combine all of those tiny lists into 1 list

2023-01-24 20:19 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +            assumeFailureToFetch()
The way this works, you're effectively just calling the callback.  If `queryProductDetailsAsync` eventually finishes, it will call the continuation after without check if it timed out.  Are you guarding against this?

2023-01-25 01:29 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +                val annualProductDetails = collectProductDetails(it, ANNUAL_PREMIUM_SUB_ID)
If the timer runs out, we should actually cancel job because it can lead to unexpected behavior. 
For example: 
* if buy() relies on collectProductDetails and the timeout happened 
* the UI moves on and the user does something else
* but the BillingClientController retries the buy() job 
* Suddenly the billing flow will pop up unexpectedly. 

There are several checks built in to make this highly unlikely:
1. BillingFlow can only launch in the WelcomeFlowActivity
2. The buy() happen if ProductDetails is valid
3. The UI that holds the buy() button can only be opened if ProductDetails is valid

I will add extra robustness to make sure a timeout will cancel a job

2023-01-26 20:20 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            val offers = getSubscriptionOfferDetails(productDetailsWrapper.productDetailsList)
Eh, keep the newline where it was?  Then `offers` is defined right next to where it's used.

2023-01-27 00:45 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientJobCreator.kt
> +                        // Start a race condition between the timeout job and the fetch job.
TODO add a kdoc at the top of the class + 
* How class works
* how cancelling works 
* how it should be used!

Also add more to this comment about how whoever returns first from FetchContinuation works

2023-01-27 01:58 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +                continuation.resume(productDetailsList.find { it.productId == productId })
I don't know if it'll still be relevant, but make sure you're using `safeResumeContinuation` everywhere.

2023-01-27 11:02 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> -                "sku=$SUB_PRODUCT_ID&" +
Originally I thought that we couldn't figure out which product ID the user has, so sending them to the Play Store with just the neeva app package name was actually good enough at showing them the right page. 

Now I see that we can do that so I'll add it back in

2023-01-27 13:15 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> +                    removeJobFromActiveJobSet(uniqueJobName = billingClientJob.uniqueJobName)
Added job cancellation

2023-01-27 23:46 UTC, dan-alcantara-neeva approved these changes
Couple of quibbles, but I don't think it's worth blocking submission on.  lgtm % comments.

2023-01-27 23:46 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        var uriString = "https://play.google.com/store/account/subscriptions?" +
Should probably just use a Uri.Builder() to avoid having to set up the query parameters yourself.

2023-01-27 23:46 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/AcknowledgePurchaseManager.kt
> +                        fetchContinuation.safeResumeContinuation(
Make the `if` statement return a boolean called `success`, then call outside of the block.  That way you defend against a situation where you add more conditions and forget to make the call, which would result in your job looking like it got stuck.

```
val success = if (billingResult.responseCode...) {
    true
} else {
    Timber.e(...)
    false
}

fetchContinuation.safeResumeContinuation(
    BillingClientJobResult(success = success)
)
```

2023-01-27 23:46 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientJobCreator.kt
> +        const val SLOW_CONNECTION_WAIT_TIME = 1000L * 60
`TimeUnit.MINUTES.toMillis(1)`.  Then you know what the unit is and don't have to hard code the 60.

2023-01-27 23:46 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +                continuation.safeResumeContinuation(productDetails)
Similarly to the other comment: pull the required `safeResumeContinuation` call out

2023-01-27 23:46 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt
> +                fetchContinuation.safeResumeContinuation(
Unlike the other places, this one has enough logic that it probably makes more sense to keep the `safeResumeContinuation` call here because there's other stuff happening.

2023-01-28 09:24 UTC, merged