Make learn-more-about-premium button wait for subscription info before doing app nav
neevaco/neeva-android pull request #1218
Opened 2023-01-23 02:01 UTC by Kokobe

The "Learn more about Premium" button in the `ProfilePane` was not always opening up the Billing `PlansScreen` because there was a race condition between when the `onClick` was set and when we decide if they can purchase premium (and therefore open the PLANS screen).

Solves this by adding a job, but on slow wifi it will look as if the button doesn't do anything immediately. This is okay because we want to show them the native Billing screen if possible over the neeva website one. 
* I could add a timeout of 10 seconds to just show them the neeva website plans instead of our Billing Screen (but I don't think that's the most optimal for getting subscriptions because there is extra friction in subscribing from entering your credit card information into the neeva website). 

## Checklists

### Pointers to help with review
* https://www.figma.com/file/dylvDPB69JG9U1rzZ3HQ52/Android-Premium?node-id=524%3A5193&t=LkA1OpxkWfXzAgDk-0

### How was this tested?
- [x] I tested this manually on `debug`
- [x] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [x] I checked that `@Previews` still work in Android Studio

### Manual test cases
Happy Path: "Learn more about Premium" button sends you to the PlansScreen if the user can purchase premium.

Happy Path: "Learn more about Premium" button sends you to the website if the user cannot purchase premium.

Opened the app with slow Wifi and spammed the "Learn more about Premium" button 
* Expects only 1 app nav redirection (if any)

### Screenshots and screen recordings
Happy Path: "Learn more about Premium" button sends you to the PlansScreen if the user can purchase premium.

Happy Path: "Learn more about Premium" button sends you to the website if the user cannot purchase premium.

Opened the app with slow Wifi and spammed the "Learn more about Premium" button 
* Expects only 1 app nav redirection (if any)

2023-01-25 21:57 UTC, dan-alcantara-neeva requested changes
1. Make sure your labels are attached to the correct videos.  I think a couple are switched

2. The behavior here is a little weird... being able to spam click a button and make it look like it's supposed to do something just looks broken.  This is "fine" for now, but can we disable it if the button isn't ready?

2023-01-25 21:57 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
>              .take(1)
.first()

2023-01-25 21:57 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/SettingsController.kt
> +                learnMoreAboutPremiumJob = coroutineScope.launch(dispatchers.io) {
1. You keep launching jobs here; shouldn't you cancel them when you start a new one?
2. Do you ever cancel this job?  If not, then the user can get kicked over to another screen when they're not expecting it, or trigger any number of jobs that fire simultaneously because you spam clicked the button.

2023-01-25 21:57 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/SettingsController.kt
> +                    coroutineScope.launch(dispatchers.main) {
Why are you launching another job instead of just switching to a new context using `withContext`?

2023-01-27 16:28 UTC, Kokobe commented on app/src/main/java/com/neeva/app/settings/SettingsController.kt
> +                    coroutineScope.launch(dispatchers.main) {
Hmmm not sure... but will change it!

2023-01-27 16:28 UTC, Kokobe commented on app/src/main/java/com/neeva/app/settings/SettingsController.kt
> +                learnMoreAboutPremiumJob = coroutineScope.launch(dispatchers.io) {
I'll cancel the job

2023-01-27 23:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/settings/sharedcomposables/SettingsRow.kt
> +            val isBillingAvailable = subscriptionManager.isBillingAvailableFlow
replace the `=` with `by` so that you don't have to type `.value`

2023-01-27 23:47 UTC, dan-alcantara-neeva approved these changes

2023-01-28 13:44 UTC, merged