Parse response for Google Native Sign In
neevaco/neeva-android pull request #1220
Opened 2023-01-23 12:33 UTC by Kokobe

General description of what your PR does, written in a way that someone six
months from now could understand what you were doing when tracking down a bug
or attempting to add new functionality

* More details about the changes
* Even more details about the changes
* Yet more details about the changes

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2023-01-23 19:44 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/LaunchLoginFlow.kt
> +        firstRunModel.handleLoginActivityResult(context, activityResult, params) {
braces on the same line if it's empty

2023-01-23 19:46 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/MainActivity.kt
>              // If the intent was a neeva login intent, sanitize it. We are done processing it.
sanitize it -> remove the data because we're done processing it

2023-01-23 19:46 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +                .take(1)
`.take(1).single()` -> `.first()`

2023-01-23 19:55 UTC, dan-alcantara-neeva requested changes

2023-01-23 19:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +                    .firstOrNull { it.name == neevaConstants.loginCookieKey }?.value
?.value on newline

2023-01-23 19:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +                    onFailure()
This will call `onFailure()` twice: once in the try or the catch, then again here.  Did you run this to check?

2023-01-24 00:39 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/login/LaunchLoginFlow.kt
> +        firstRunModel.handleLoginActivityResult(context, activityResult, params) {
The follow-up PR is meant to populate whatever is in these braces (aka the navigation logic once you have a success from Google Native Sign In). 

Currently empty braces is just saying onSuccess(), we don't do anything

2023-01-24 01:22 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +                    onFailure()
Just tested now, you are correct. Fixed it!

2023-01-24 01:42 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/LaunchLoginFlow.kt
> +        firstRunModel.handleLoginActivityResult(context, activityResult, params) {
Add a comment saying that we don't do anything in the case of success?

2023-01-24 01:43 UTC, dan-alcantara-neeva approved these changes

2023-01-24 05:50 UTC, merged