Kobe/add google native sign in response and loading
neevaco/neeva-android pull request #1221
Opened 2023-01-23 12:58 UTC by Kokobe

General description of what your PR does, written in a way that someone six
months from now could understand what you were doing when tracking down a bug
or attempting to add new functionality

* More details about the changes
* Even more details about the changes
* Yet more details about the changes

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2023-01-23 20:47 UTC, dan-alcantara-neeva requested changes
I'm worried that the current state of the login flow is too fragile and confusing.  Can you take a step back and write up how this is all supposed to work, including:

* How your activity/screen to return to/screen to return to after failure mechanisms work
* Describing the different login states that a user can be in
* Links between the different states the user can be in and how they transition between them
* Whatever else someone two months from now would need to understand how your code fits into everything?

2023-01-23 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +            .take(1)
`.take(1).single()` -> `.first()`, here and everywhere else

2023-01-23 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/LoadingScreen.kt
> +            Spacer(Modifier.size(249.dp))
Any time you're hard-coding a number like `249.dp`, I need to understand why you chose it and whether you should be centering the content & spinner, instead.  A hard-coded number will never work correctly across multiple screen sizes.

2023-01-23 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/LoadingScreen.kt
> +@PortraitPreviews
You need to use @PortraitPreviewsDark.

2023-01-23 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
>                  Spacer(Modifier.height(Dimensions.PADDING_LARGE))
Should one of these spacers live inside of the `?.let` block?  Otherwise, you introduce an extra big space that unbalances the content.

2023-01-23 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                            fontSize = 18.sp,
If you're overriding the font size and font weight, what from the `titleMedium` are you actually using?  Can you ask if there's an equivalent font you should be using, instead?

2023-01-23 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                tag != BillingSubscriptionPlanTags.MONTHLY_PREMIUM_PLAN &&
Define this condition somewhere and reuse it over and over again to avoid it getting out of sync with the other places you use the same check.

2023-01-23 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +            val browserIntent = activity.intent.apply {
Can't `intent` be null?

2023-01-23 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/LaunchLoginFlow.kt
> +            welcomeFlowNavModel.navigateToScreenAfterLoginWhenReady()
Move the `showLoadingScreen` call into `navigateToScrenAfterLoginWhenReady` call.  The way the function is named implies that it needs to do something while it's getting ready, which would be showing the loading screen.

2023-01-23 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/PreviewContainer.kt
> -
Put this back.

2023-01-23 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +        activityReference.get()?.let { activity ->
1. Why are you using an activity reference?  ViewModels should generally have no idea what Activity it's associated with because it's supposed to outlive the activity.  Can't you just use app context and pass the intent in?

2. Re-add `WelcomeFlowActivity#finishWelcomeFlow`, then make that call `WelcomeFlowNavModel.finishWelcomeFlow()` and `finishAndRemoveTask()`.  A `ViewModel` should generally avoid ever storing references to Views or Activities or anything that could be recreated in case the Activity dies.  It also means that you're violating the encapsulation between the View and Model.

2023-01-23 20:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                LaunchedEffect(navHost) {
Make this a disposable effect.

```
DisposableEffect(navHost) {
    welcomeFlowNavModel.setNavHost(navHost)
    onDispose { welcomeFlowNavModel.setNavHost(null) }
}
```

Avoids holding onto dead classes.  Should be doing this in `NeevaActivity` too, honestly...

2023-01-24 02:15 UTC, Kokobe commented
> I'm worried that the current state of the login flow is too fragile and confusing. Can you take a step back and write up how this is all supposed to work, including:
> 

> * Describing the different login states that a user can be in
> * Links between the different states the user can be in and how they transition between them
> * Whatever else someone two months from now would need to understand how your code fits into everything?

The follow-up PR #1223 clarifies what the final state of the login flow will look like.
Important points: 
* Any login will get redirected to the `LoadingScreen` in the `WelcomeFlowActivity`. 
* Any login failure will get redirected to the `SignInScreen` in the `WelcomeFlowActivity`
* All `activityToReturnTo` will be used for is returning the user to the correct activity after finishing the WelcomeFlow. 
* The enum `Purpose` defines the flow behavior + which starting screen in the WelcomeFlow

### As for the current state in this PR:
> * How your activity/screen to return to/screen to return to after failure mechanisms work

Any screen

2023-01-24 02:40 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/login/LoadingScreen.kt
> +            Spacer(Modifier.size(249.dp))
Since we made the `WelcomeFlowContainer` scrollable, it is actually impossible to vertically center the content in there. In other terms: the content is allowed to grow as large as it wants, which makes the height of the container unknown and therefore we don't know the center (unless we recompose and do some screen sizing calculations after the content has been placed down). 

But the designs aren't centered anways:
https://user-images.githubusercontent.com/20916043/214201477-e43b7ddf-5a51-4334-bb72-62ec60117a17.mov

2023-01-24 02:41 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/login/LoadingScreen.kt
> +            Spacer(Modifier.size(249.dp))
Should I create a separate `WelcomeFlowContainerNoScrollable` just for the `LoadingScreen`? I can do that as a follow-up PR

2023-01-24 02:43 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/login/LoadingScreen.kt
> +@PortraitPreviews
Sure! What is the difference? I remember there are certain colors that don't render correctly within `MaterialTheme3`, but I forget what the cases are

2023-01-24 02:46 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
>                  Spacer(Modifier.height(Dimensions.PADDING_LARGE))
Makes sense! Thanks for catching that

2023-01-24 02:49 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowContainer.kt
> +                            fontSize = 18.sp,
I actually confirmed with @hwiatneeva about a month ago that this was the header text font we wanted! 
TitleMedium is too bold

<img width="247" alt="Screen Shot 2023-01-24 at 10 49 43 AM" src="https://user-images.githubusercontent.com/20916043/214202523-2f59fce0-cb15-4161-9ff8-9d3bd8c7e683.png">

2023-01-24 02:52 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +            val browserIntent = activity.intent.apply {
`Activity.java` says no

<img width="391" alt="Screen Shot 2023-01-24 at 10 52 18 AM" src="https://user-images.githubusercontent.com/20916043/214202786-1b41bd70-72ed-4082-a3aa-a0885b44c08c.png">

2023-01-24 02:56 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/login/LaunchLoginFlow.kt
> +            welcomeFlowNavModel.navigateToScreenAfterLoginWhenReady()
done + `navigateToScreenAfterLoginWhenReady` renamed to `navigateToLoginResultScreenWhenReady`

2023-01-24 03:02 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +        activityReference.get()?.let { activity ->
1. It's a `WeakReference` not an actual activity reference, but I do see that I should rename it to `activityWeakReference`... This shouldn't have any memory-leak ramifications though right? The Garbage collector won't count these references as actual references to the Activity, so it can safely be garbage collected

Also I need this activityReference so I can call `finishAndRemoveTask()` which is an Activity-only method. 


2. Fair point. Okay I'll do that

2023-01-24 03:22 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +                LaunchedEffect(navHost) {
https://github.com/neevaco/neeva-android/issues/1227

2023-01-24 18:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +            val browserIntent = activity.intent.apply {
That's not what that says.  Java automatically assumes nullable fields -- Kotlin requires you to say they're nullable or not.

2023-01-24 18:33 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/LoadingScreen.kt
> +@PortraitPreviews
Check the annotation definitions.  The Dark versions tell Compose to use a dark theme system environment, which sets various things to dark.

2023-01-24 18:37 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/LoadingScreen.kt
> +            Spacer(Modifier.size(249.dp))
1. Did you ask UX?  It looks like it was eyeballed to be centered on the screen.
2. You can do it as a follow up.  You can try swapping out the entire scrollable container with a loading Composable so that you can place it based on the whole container.

2023-01-24 18:38 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +        activityReference.get()?.let { activity ->
WeakReference makes it memory-leak safe, but it's still bad encapsulation to store the Activity if you can avoid it.

2023-01-24 19:49 UTC, dan-alcantara-neeva commented
> 

I was asking for a doc with an explanation for why you're doing what you're doing the way you did it (in English), plus a flow chart showing the different ways you can send the user around -- not a PR comment, a PR description, and a pointer to undocumented individual functions in a Model.

2023-01-24 19:59 UTC, dan-alcantara-neeva requested changes

2023-01-24 19:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                tag = tag.lowercase()
If you're always going to require that the tag is lowercase, move the `lowercase()` call to the `retrieveEligibleOffers` function.  Otherwise, you can get into a situation where you forget to do it at one callsite.

2023-01-24 19:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +            onGoogleSignInSuccess(it)
Why are you calling `onGoogleSignInSuccess` here if it can still fail and call `onGoogleSignInFailure` if the cookie doesn't get extracted?

2023-01-24 19:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +        queueFetchNeevaInfo()
In a comment, explain why you're still fetching neeva info if the browser login cookie failed to be updated.

2023-01-24 19:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +                    destinationToReturnWhenFinished.value?.let {
Why don't you unset this value?

2023-01-25 17:33 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +            onGoogleSignInSuccess(it)
This is what happens when I don't immediately call onGoogleSignInSuccess(it)  -- which moves it to the loading screen  -- after getting the loginUri from GoogleSignIn

https://user-images.githubusercontent.com/20916043/214638465-e8678320-897b-4617-a6dc-b64e3f365020.mp4

2023-01-25 17:36 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +            onGoogleSignInSuccess(it)
In areas with super slow network connection, it can look like a successful native google sign in didn't actually do anything. I'll differentiate the process of extracting the cookie vs. getting the native google sign in uri  by renaming the lambdas

2023-01-25 17:45 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +        queueFetchNeevaInfo()
In this case, we don't care about the browser cookie jar failing to update because:
1. It will fail to update the cookie jar probably because the browser isn't alive yet.
2. it eventually will update when the browser comes to life. 

The comment I wrote though is:
`Fetch the user's Neeva information so we can see if they are allowed to buy premium.`

2023-01-25 17:48 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +                    destinationToReturnWhenFinished.value?.let {
???

2023-01-25 18:28 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +                    destinationToReturnWhenFinished.value?.let {
Offline convo: `destinationToReturnToWhenFinished` needed to be reset in finishWelcomeFlow() because if we reopened the WelcomeFlowActivity and it was still alive somehow, it would retain the old value of `destinationToReturnToWhenFinished`

2023-01-25 18:30 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +        queueFetchNeevaInfo()
Would prefer you put that context in the code

2023-01-25 18:31 UTC, dan-alcantara-neeva approved these changes
LGTM % last comment about comment

2023-01-26 04:57 UTC, merged