Rework Login for SingleTabActivity
neevaco/neeva-android pull request #1223
Opened 2023-01-23 16:32 UTC by Kokobe

## Login Flow Rework details (how things work now)

### Single Tab Activity (STA)
* STA launched and user signs in on it
* [Neeva.com](http://neeva.com/) sends an intent to open the Neeva App
* MainActivity catches intent with login uri coming from [Neeva.com](http://neeva.com/) and starts logging the user in with cookie from the intent. NeevaUser.fetch() is currently in progress.
* MainActivity sends user to WelcomeFlowActivity Loading Screen
* Once the NeevaUser.fetch() has finished, we have enough information to determine which screen and activity to send them to.
* Automatically redirect the user to the correct screen and activity from the LoadingScreen

### Native Google Sign In 
* User signs in from Native Google Sign In in WelcomeFlowActivity
    * On success: navigates them to the Loading Screen 
    * On failure (uri is not returned by native google sign in): 
        * If user cancelled -> dismiss the Native Google Sign in and don't do anything
        * If Google API error -> open SingleTabActivity for Google
* On successful Native Google Sign-in, we are given a URI with the cookie in it. Parse the cookie
    * This requires opening the URI using HttpURLConnection
    * and using a CookieManager to get the cookie
    * If this fails -> show an error that something went wrong and open SingleTabActivity for Google
* Once the cookie is parsed, the NeevaUser.fetch() is in progress and move the user to the Loading Screen to wait
* Automatically redirect the user to the correct screen and activity from the LoadingScreen

## Checklists

### Pointers to help with review
* Last 2 PRs on LoadingScreen + Google Native Sign In:
  * https://github.com/neevaco/neeva-android/pull/1220
  * https://github.com/neevaco/neeva-android/pull/1221

### How was this tested?
- [x] I tested this manually on `debug`
- [x] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [x] I checked that `@Previews` still work in Android Studio

### Manual test cases
SingleTabActivity Sign Up Failed returns you to Sign In screen
SingleTabActivity Sign Up from Settings
SingleTabActivity Sign Up from Spaces
SingleTabActivity Sign In from FirstRun

### Screenshots and screen recordings
SingleTabActivity Login Failure -> Brings you back to Sign-In + shows popup message

https://user-images.githubusercontent.com/20916043/213868026-c33c95c7-0441-4a0d-9374-bdfce13b0d01.mp4

SingleTabActivity Sign Up from Settings (default browser is Neeva)

https://user-images.githubusercontent.com/20916043/213868214-768a5b30-98ee-4c1f-bc0b-a3d5e8ccb180.mp4

SingleTabActivity Sign Up from Settings (default browser is not Neeva)

https://user-images.githubusercontent.com/20916043/213868263-b07792eb-8a0c-47e5-81d0-5a232539cacb.mp4

SingleTabActivity Sign Up from Spaces

https://user-images.githubusercontent.com/20916043/213868322-11d2bf1b-0f38-48eb-ad5c-30d830e4c109.mp4

SingleTabActivity Sign In from FirstRun (Neeva is the default browser already)

https://user-images.githubusercontent.com/20916043/213868352-db14e3b4-8de2-4700-8385-48a8db460691.mp4

2023-01-23 20:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                    if (collectIsBillingAvailable() && collectIsPremiumPurchaseAvailable()) {
1. Can this get stuck if nothing is ever collected from the flow?
2. Can the user end up on a completely different screen and have this trigger much later?

2023-01-23 20:55 UTC, dan-alcantara-neeva reviewed
Punting on this review until the other PRs in the chain are approved.

2023-01-24 04:40 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                    if (collectIsBillingAvailable() && collectIsPremiumPurchaseAvailable()) {
1. 
For `collectIsBillingAvailable`:
See `ATTEMPTS_TO_ASSUME_FAILURE` in `BillingClientController`.
If it fails to fetch billing info or purchase info after 4 attempts, it won't get stuck. There's also a timeout that will assume failure for if those fetchPurchases or fetchProductDetails calls take too long. 

`collectIsPremiumPurchaseAvailable` is blocked on the NeevaUserInfo (see `isBillingAvailableFlow` in `SubscriptionManager`). This can be stuck if the queueOnSignIn() isn't accurate and the neeva user info is always null. 

This one should not get stuck (because if it does, we have bigger problems) but also if it is stuck, we are literally unable to make a premium purchase. We don't have to worry about there being multiple jobs of `QUEUE_BUY_ON_SIGN_IN_JOB_NAME` getting stuck and using up the heap space because of the de-duping in `queueOnSignIn`

2023-01-24 04:43 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +                    if (collectIsBillingAvailable() && collectIsPremiumPurchaseAvailable()) {
2. note that `queueBuyPremiumOnSignInIfSelected` uses an `activityReference`. The only usage of it right now is in `getOnSelectSubscriptionPlan()` in `WelcomeFlowNavModel`. 

So it will only navigate the user if the `WelcomeFlowActivity` is still alive (the user can see it). If you look at `onBillingFlowFinished`, everything in there checks either if WelcomeFlowActivity's `navHost` is still alive or if the activityReference is not null

2023-01-30 23:30 UTC, dan-alcantara-neeva requested changes
Still reviewing, but I don't think you properly rebase this since the last time.

2023-01-30 23:30 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/ui/PreviewContainer.kt
> -
Man, you really want to get rid of this line.  Was this a bad rebase after I asked you to keep it last time?

2023-01-30 23:30 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        return offerDetails.filter { it.offerTags.contains(tag?.lowercase()) }
Why'd you allow null here?  Is it a valid tag to send along?  Should you just exit early?

2023-01-30 23:30 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> -
I think I asked you to keep this line and remove the newline on 261 in a previous PR.

2023-01-31 01:11 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +        val browserIntent = activityIntent.apply {
You're again not null checking here

2023-01-31 01:43 UTC, Kokobe commented on app/src/main/java/com/neeva/app/ui/PreviewContainer.kt
> -
Ah sorry I actually just didn't rebase. Doing it now

2023-01-31 01:45 UTC, dan-alcantara-neeva requested changes
Sending comments before you rebase

2023-01-31 01:45 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +        private const val USER_CANCELLED_NATIVE_SIGN_IN = 12501
Use https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInStatusCodes instead of hard-coding 12501

2023-01-31 01:45 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt
> +        welcomeFlowNavModel.processIntent(intent, this@WelcomeFlowActivity)
I still don't like that you're passing Activities around into the Model, but you might as well be consistent and use `WeakReference`s

2023-01-31 02:34 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> +        return offerDetails.filter { it.offerTags.contains(tag?.lowercase()) }
Good point

2023-01-31 02:38 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt
> -
After rebase, I've now organized it so that each `return` code block that is separated by new lines has all their dependencies in 1 block

2023-01-31 02:38 UTC, Kokobe commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +        val browserIntent = activityIntent.apply {
Ah result of not rebasing, I checked now and it has the null check

2023-01-31 02:39 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +        private const val USER_CANCELLED_NATIVE_SIGN_IN = 12501
Ah deleting this, it is vestigial

2023-01-31 04:04 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +        savedInstanceState?.let {
Early exit if `savedInstanceState` is null?

2023-01-31 04:07 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +            Purpose
This seems like it should be a method on a companion object of the `Purpose` class

2023-01-31 04:08 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +            .find {
Should be `firstOrNull` like above, but you should refactor out your function

2023-01-31 04:09 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/login/WelcomeFlowNavModel.kt
> +            else -> Destinations.SIGN_IN
Also be consistent about braces here

2023-01-31 04:11 UTC, dan-alcantara-neeva commented
Approving @Kokobe, but you need to do a little bit of refactoring and make a common method to look at the `Purpose`

2023-02-01 01:37 UTC, merged