Native Google Login Tests
neevaco/neeva-android pull request #1255
Opened 2023-02-04 16:12 UTC by Kokobe

Added a NativeGoogleSignInWrapper so I can mock out the functions to enable instrumentation tests on it. 

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2023-02-08 00:15 UTC, dan-alcantara-neeva commented on app/src/androidTest/assets/html/set_cookie.html
> +        document.cookie="httpd~login=loginSessionKey; expires=Thu, 18 Dec 3000 12:00:00 UTC;";
Maybe it doesn't like the year 3000... did you try something less far ahead in the future?

2023-02-08 00:38 UTC, dan-alcantara-neeva requested changes
Partial review

2023-02-08 00:38 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/ModuleOverrides.kt
> +        return object : NativeGoogleSignInWrapper(
Given how large this is, would it make more sense to create an explicit class for it, like the `TestAuthenticatedApolloWrapper`?

2023-02-08 00:38 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/ModuleOverrides.kt
> +                    TestingCases.URI_WEBSITE_SET_COOKIE_SUCCESS ->
You're on two lines; use braces.

2023-02-08 00:38 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/PresetSharedPreferencesRule.kt
> +                when {
Why are you using a when?  These are two different flags and you should be using two separate ifs

2023-02-08 00:38 UTC, dan-alcantara-neeva commented on testCommon/src/main/java/com/neeva/testcommon/WebpageServingRule.kt
> +                                "HTTP/1.1 302 OK\r\n" +
302 is not OK; 302 is a different code than 200 OK

2023-02-08 00:38 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/firstrun/FirstRunModelTest.kt
> -    @Test
Is this case the broken one?  Instead of straight up deleting it, comment it out to disable it so you can try to fix it later.

2023-02-08 00:38 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/nativelogin/NativeGoogleSignInWrapper.kt
> +
Two headers

2023-02-08 00:38 UTC, dan-alcantara-neeva commented on app/src/main/AndroidManifest.xml
> +        <!-- Intended for Google Native Sign In instrumentation-testing-only use. -->
You should almost never put a test-only Activity in the main manifest.  Can you try moving the Activity to the androidTest package and add it to the androidTest's `AndroidManifest.xml` file?

2023-02-08 00:38 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/nativelogin/MockNativeGoogleSignInActivity.kt
> +class MockNativeGoogleSignInActivity : AppCompatActivity() {
Try to put this in the `androidTest` package, instead.

2023-02-08 00:38 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
> +class FirstRunModel @Inject internal constructor(
This should just be injected in `NeevaModule` like all of the other ones.

2023-02-08 01:29 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/nativelogin/NativeGoogleSignInWrapper.kt
> +     * [ActivityResult].
Can you describe what each of these parameters is in the kdoc?  I was trying to understand what `FirstRunModel` was doing because it's passing in a ton of code into 5 lambdas, which is a weird thing to do.  Is there a specific reason you went this route?  There's practically no code in here because everything is passed in from elsewhere.

2023-02-08 15:14 UTC, Kokobe commented on app/src/test/java/com/neeva/app/firstrun/FirstRunModelTest.kt
> -    @Test
Ah meant to write in a comment, I don't need to test this anymore because the instrumentation tests cover it now

2023-02-14 05:27 UTC, dan-alcantara-neeva requested changes

2023-02-14 05:27 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/firstrun/NativeGoogleSignInTest.kt
> +                    // Simulate Login Intent sent form Neeva back-end
sent from

2023-02-14 05:27 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/firstrun/NativeGoogleSignInTest.kt
> +    private fun performLogin(testingCase: NativeGoogleSignInWrapper.TestingCases): Boolean {
Instead of having 1 function that runs 4 tests and early exits for some of them, you should make reusable functions for the common parts of the tests and keep the different parts in the actual tests themselves.  Splitting the tests like this makes it much more difficult to understand how the test is set up and runs, which then makes it harder to understand if your test is doing what you expect it to.

2023-02-14 05:27 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/login/TestNativeGoogleSignInWrapper.kt
> +        return when (testingCase) {
Same comment as before: instead of breaking apart and burying important details about the test in a helper class, this code should be in the test itself.  Consider:
1. Setting a lambda on this class that does what each test expects
2. Make this function perform that lambda
3. Set the lambda from the test itself

That way that the code is set up in the same place that it starts from.

2023-02-15 18:13 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/nativelogin/MockNativeGoogleSignInActivity.kt
> +class MockNativeGoogleSignInActivity : AppCompatActivity() {
Couldn't get this to work, will get your help later

2023-02-15 18:16 UTC, Kokobe commented on app/src/androidTest/java/com/neeva/app/PresetSharedPreferencesRule.kt
> +                if (useCustomTabsForLogin == true) {
Ah great catch

2023-02-15 18:19 UTC, Kokobe commented on app/src/main/java/com/neeva/app/firstrun/FirstRunModel.kt
>          } else if (useCustomTabs) {
Ah will clean-up the old, unused login paths in a follow-up PR

2023-02-17 18:20 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/firstrun/NativeGoogleSignInTest.kt
> +        testFinishWelcomeFlowAfterLogin()
testFinishWelcomeFlowAfterSuccessfulLogin

2023-02-17 18:42 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/nativelogin/NativeGoogleSignInWrapper.kt
> +                    Log.e("KOBE", "cookies = $cookies")
Remove

2023-02-17 18:43 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaConstants.kt
> +            return URL(urlString).host
`Uri.parse(urlString).host`?  We usually use Uri

2023-02-17 18:45 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/firstrun/nativelogin/NativeGoogleSignInWrapper.kt
> +                        .filter { it.domain == hostNameWithoutPort(neevaConstants.appURL) }
Just inline the function here; there's only one use case

2023-02-18 00:46 UTC, merged