Acknowledge purchases test draft
neevaco/neeva-android pull request #1260
Opened 2023-02-14 00:09 UTC by Kokobe

General description of what your PR does, written in a way that someone six
months from now could understand what you were doing when tracking down a bug
or attempting to add new functionality

* More details about the changes
* Even more details about the changes
* Yet more details about the changes

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2023-02-15 22:52 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt
> -            if (isBillingClientReadyToBeUsed) {
After writing tests and reading https://developer.android.com/google/play/billing/errors I realized that we don't need to check if the BillingClient Is Ready To Be Used. We only truly know that by looking at the `BillingResult` when performing a job.

2023-02-16 23:11 UTC, Kokobe commented on app/src/test/java/com/neeva/app/billing/AcknowledgePurchaseManagerTest.kt
> +//        every { acknowledgePurchaseManager.startTimeout(any()) } answers { }
Just pass a parameter to disable timeout in BillingClientController

2023-02-17 20:53 UTC, dan-alcantara-neeva reviewed
Guess these didn't get sent

2023-02-17 22:13 UTC, dan-alcantara-neeva approved these changes
Approving, but we have to figure out why these tests aren't working well.

2023-02-17 22:14 UTC, dan-alcantara-neeva requested changes
Still looks flaky...

2023-02-21 19:45 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/AcknowledgePurchaseManager.kt
> +        const val jobName = "acknowledgePurchase"
JOB_NAME

2023-02-21 19:46 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/AcknowledgePurchaseManager.kt
> +        fun generateAcknowledgePurchaseJobName(purchaseToken: String): String {
Remove if you're not using it

2023-02-21 19:47 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +                }
newlines between clauses

2023-02-21 19:48 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +                // If not a success and there are no retry codes, return one of the billing results
Why, and why this annual one instead of the manual one?

2023-02-21 19:50 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +                // If not a success and there are no retry codes, return one of the billing results
Codify what was said offline as a comment here.  It's not clear how the above clauses translate into "no retry code"

2023-02-21 19:50 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt
> +        const val jobName = "fetchProductDetails"
JOB_NAME, here and everywhere else

2023-02-21 19:51 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/ObfuscatedUserIDManager.kt
> +            if (!allowTimeouts) return@launch
newline after this just so the early exit stands out

2023-02-21 20:01 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/billing/ObfuscatedUserIDTest.kt
> +        coroutineScopeRule.scope.advanceUntilIdle()
Is this supposed to do something?  There's no call, but you're waiting for a coroutineScope to go idle

2023-02-21 20:04 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/billing/SubscriptionManagerTest.kt
> +            on { createBillingClientJob() } doReturn BillingClientJob(
Do you want this to be `doReturn` or `answer`?  `doReturn` will compute the value once when the mock is created and always return that thing.  `answer` will compute the value of the lambda when the function is called, so you can end up with a new thing each time.  As it is, your current PR will always return the same `BillingClientJob` whenever `createBillingClientJob` is called.  Is that the behavior you're expecting?

2023-02-21 21:56 UTC, Kokobe commented on app/src/test/java/com/neeva/app/billing/SubscriptionManagerTest.kt
> +            on { createBillingClientJob() } doReturn BillingClientJob(
Ah actually this is the behavior I'm expecting. It's okay to return the same `BillingClientJob`, because I am just using this as an identifier (using the BillingClientJob `uniqueJobName`) for this class.

2023-02-21 22:50 UTC, dan-alcantara-neeva approved these changes

2023-02-22 03:57 UTC, merged