Kobe/add billing enabled tests
neevaco/neeva-android pull request #1312
Opened 2023-03-14 22:24 UTC by Kokobe

General description of what your PR does, written in a way that someone six
months from now could understand what you were doing when tracking down a bug
or attempting to add new functionality

* More details about the changes
* Even more details about the changes
* Yet more details about the changes

## Checklists

### Pointers to help with review
* Figma link (if this is a UI change)
* Link to where the change is discussed (e.g. meeting notes, design docs)

### How was this tested?
- [ ] I tested this manually on `debug`
- [ ] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [ ] I checked that `@Previews` still work in Android Studio

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Composables, add images of `@Preview`s you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2023-03-15 19:29 UTC, dan-alcantara-neeva reviewed
Feels like you're still heavily mixing your classes and wrappers, which ends up making everything more complicated instead of simple.  The point of the wrappers is to abstract away a bunch of stuff, but now you're importing both versions of the same data structure in several files.  Is that intentional?

2023-03-15 19:29 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/billing/TestBillingClientWrapper.kt
> +    override fun terminateBillingConnection() {}
newline

2023-03-15 19:29 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/welcomeflow/PlansScreenData.kt
> +        subscriptionOfferDetails: List<com.neeva.app.billing.billingclient.productdetails.SubscriptionOfferDetails>,
Are you mixing your classes in this file?

2023-03-15 19:29 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/purchases/FetchPurchasesManager.kt
> +        billingClientWrapper: BillingClientWrapper,
You can probably just keep calling these things `billingClient` and `purchase` if the interfaces is supposed to be abstracted

2023-03-15 21:52 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/purchases/FetchPurchasesManager.kt
> +        billingClientWrapper: BillingClientWrapper,
Could I do this in a follow-up PR?

2023-03-15 21:54 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/purchases/FetchPurchasesManager.kt
> +        billingClientWrapper: BillingClientWrapper,
Why, though?  You'd basically be reverting a bunch of changes you made in the PR where you made the changes to begin with?

2023-03-15 21:55 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/ComposeTestUtils.kt
> +/** Wait for a Composable to appear with the given tag, scroll to it, and flaky click on it. */
flaky click -> try to click

2023-03-15 22:28 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/purchases/FetchPurchasesManager.kt
> +        billingClientWrapper: BillingClientWrapper,
That's fair, just didn't want this PR to be too large

2023-03-15 23:21 UTC, dan-alcantara-neeva requested changes

2023-03-15 23:21 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/BillingSubscriptionPlanConstants.kt
> +    fun filterPurchasesWithSupportedIDs(
Was this formatting change necessary?

2023-03-15 23:21 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/AcknowledgePurchaseManager.kt
> +                acknowledgeResult.responseCode ==
These lines look really weird now... can you
```
import com.android.billingclient.api.BillingClient.BillingResponseCode
import com.android.billingclient.api.Purchase.PurchaseState
```

then replace these with `BillingResponseCode.OK` and `PurchaseState.PURCHASED`?

2023-03-15 23:21 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/AcknowledgePurchaseManager.kt
> +    internal fun queueAcknowledgePurchaseJobs(
undo?

2023-03-15 23:21 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/BillingClientWrapper.kt
> +        val TAG: String = BillingClient::class.java.name
This is messed up now, I think

2023-03-15 23:21 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/purchases/FetchPurchasesManager.kt
> +            com.android.billingclient.api.BillingClient.BillingResponseCode.OK &&
`import BillingClient.BillingResponseCode` and fix the formatting

2023-03-15 23:21 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/billing/TestBillingClientWrapper.kt
> +import com.neeva.app.billing.billingclient.purchases.Purchase
newline

2023-03-15 23:21 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/billing/TestBillingClientWrapper.kt
> +        val productDetails = if (doProductDetailsExist) {
To make this more generic, maybe make it so that you can set what `ProductDetails` get returned instead of having them hard coded here.  Having the data over here makes it harder to understand what the test is doing because the test is separated from the data that controls it.

2023-03-15 23:21 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/billing/TestBillingClientWrapper.kt
> +        val purchases = if (doPurchasesExist) {
Same comment here.

2023-03-15 23:21 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/firstrun/FirstRunStartupTest.kt
> +                // Postpone looking for the expected condition until the end of this test.
Any reason why you're postponing this check?  The whole point of the flaky click functionality is to make sure the thing was clicked instead of having it fail.  Maybe add a check to see if the checkbox has the right state?

2023-03-15 23:47 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/BillingSubscriptionPlanConstants.kt
> +    fun filterPurchasesWithSupportedIDs(
Yeah it doesn't fit all on 1 line

2023-03-15 23:49 UTC, Kokobe commented on app/src/main/java/com/neeva/app/billing/billingclient/AcknowledgePurchaseManager.kt
> +                acknowledgeResult.responseCode ==
I can't do the second import (import com.android.billingclient.api.Purchase.PurchaseState) because it gets confused on whether I'm talking about the neeva `Purchase` data class wrapper or the google `Purchase` class

2023-03-15 23:50 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/BillingSubscriptionPlanConstants.kt
> +    fun filterPurchasesWithSupportedIDs(
Nothing changed in the function definition, though?

```
fun filterPurchasesWithSupportedIDs(purchases: List<Purchase>): List<Purchase> {
```

looks the same

2023-03-15 23:51 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/billing/billingclient/AcknowledgePurchaseManager.kt
> +                acknowledgeResult.responseCode ==
Does your internal `Purchase` class have its own internal `PurchaseState` class?

2023-03-16 00:07 UTC, Kokobe commented on app/src/androidTest/java/com/neeva/app/firstrun/FirstRunStartupTest.kt
> +                // Postpone looking for the expected condition until the end of this test.
There's no need for this to be a flaky click, I just want it to try to click on it -- like how normal `performClick`s work. Deleting this "Postpone" comment!

2023-03-16 00:14 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/firstrun/FirstRunStartupTest.kt
> +                // Postpone looking for the expected condition until the end of this test.
Take the default parameter back out; there seems to be a fundamental misunderstanding of what that expected condition is for.

Compose sometimes fails to deliver a click.  You need to make the expected condition actually check that the click did something.  In this case, you want to at least make sure that the checkbox was toggled correctly.  If you want until the end of the test and check a related condition, then you've basically thrown away all of the flaky clicking protection by not checking if the box was ever checked to begin with.

2023-03-16 00:54 UTC, dan-alcantara-neeva commented on app/src/androidTest/java/com/neeva/app/billing/TestBillingClientWrapper.kt
> +object MockBillingClientData {
Put these in FirstRunStartupTest where they're used.

2023-03-16 00:55 UTC, dan-alcantara-neeva approved these changes
lgtm % comments

2023-03-16 02:44 UTC, merged