Share Space: Add Invite Someone Support
neevaco/neeva-android pull request #922
Opened 2022-08-26 00:52 UTC by Kokobe

Adds Invite Someone textfields behind a feature flag. 
- Reorganizes `ShareSpaceUI` code into `ShareSpaceSheet`, `InviteUserUI`, `ShareSpaceLinkUI`.
- Rename `OnboardingTextField` to `ClearFocusOnDismissTextField`
- Incorporates new designs to `InviteUserUI`. 
- Adds new spaces.graphql and adds `AddSpaceSoloACLsMutation` mutation functionality.

## Checklists

### Pointers to help with review
* [Project Proposal](https://paper.dropbox.com/doc/Project-Proposal-Invite-User-to-Space--BoTIEQTpdtJzx4nBppaYQB6GAg-tnjXvk1hYuEZNujCsYR6u)
* [Figma](https://www.figma.com/file/D3pbLY6ZP5YtCjTYqsGOKO/Android-Design-System?node-id=2070%3A33760)
* Link to where the change is discussed: https://app.clickup.com/36034046/v/l/12bnfy-14420?pr=54170898

### How was this tested?
- [x] I tested this manually
- [x] I added automated tests
- [x] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes

### Manual test cases

### Screenshots and screen recordings

Pressing `ShareLink` Buttons will automatically change the Space to `public`. 

https://user-images.githubusercontent.com/20916043/191618037-64e555c6-69d4-4909-8f15-5ceab9823c0e.mp4

<img width="1303" alt="Screen Shot 2022-09-21 at 3 09 38 PM" src="https://user-images.githubusercontent.com/20916043/191619445-4e5ea3c4-c24f-4ea8-a79a-ab952c8922b8.png">

<img width="1290" alt="Screen Shot 2022-09-21 at 3 09 43 PM" src="https://user-images.githubusercontent.com/20916043/191619454-8cbdc62b-aa04-455a-aaa2-0e887fe30bdc.png">

2022-09-21 20:37 UTC, dan-alcantara-neeva commented
What does this look like if the font is 2x the normal size?

2022-09-21 20:40 UTC, Kokobe commented
> What does this look like if the font is 2x the normal size?

<img width="479" alt="Screen Shot 2022-09-21 at 1 39 48 PM" src="https://user-images.githubusercontent.com/20916043/191605993-a95bee57-85d8-40d8-b5b7-48ec3d022661.png">

Are you talking about the textfields or just all of the Text in the screenshot in general?

2022-09-21 20:43 UTC, dan-alcantara-neeva requested changes
Initial comments

2022-09-21 20:43 UTC, dan-alcantara-neeva commented on app/src/main/graphql/com/neeva/app/spaces.graphql
> +  addSpaceSoloACLs(input: $input) {
Indentation is off here

2022-09-21 20:43 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/appnav/AppNavModelImpl.kt
> +import ShareSpaceSheet
Is this import actually necessary?

2022-09-21 20:43 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/spaces/share/ShareSpaceLinkUI.kt
>  fun SocialShareRow(
What happens to the buttons if the screen is small and the font is big?

2022-09-21 20:43 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/spaces/share/InviteUserUI.kt
> +        SpaceACLLevel.View -> "Can view"
Are you hard-coding user-visible strings?  You should be putting these and all the other ones in the `strings.xml`.

2022-09-21 20:43 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/spaces/share/InviteUserUI.kt
> +            label = { Text(text = "Permissions") },
strings.xml

2022-09-21 20:59 UTC, dan-alcantara-neeva commented
> > What does this look like if the font is 2x the normal size?
> 
> <img alt="Screen Shot 2022-09-21 at 1 39 48 PM" width="479" src="https://user-images.githubusercontent.com/20916043/191605993-a95bee57-85d8-40d8-b5b7-48ec3d022661.png">
> 
> Are you talking about the textfields or just all of the Text in the screenshot in general?

Everything in that screenshot.  Want to see what the social buttons do.

2022-09-21 21:00 UTC, Kokobe commented
Oh I misread your comment. I'll add those to the description and re-request review

2022-09-21 22:21 UTC, Kokobe commented on app/src/main/java/com/neeva/app/appnav/AppNavModelImpl.kt
> +import ShareSpaceSheet
Yeah, I'm having trouble making this import say its from com.neeva.app.spaces.share.ShareSpaceSheet

2022-09-21 22:37 UTC, Kokobe commented on app/src/main/java/com/neeva/app/spaces/share/ShareSpaceLinkUI.kt
>  fun SocialShareRow(
Checking with @Ria-yu , I can make it wrap around like what you did with `CookieCutterPopover`

2022-09-22 18:02 UTC, dan-alcantara-neeva commented on app/src/main/res/values/strings.xml
> +    <string name="share_space_confirmation_message">Invitation sent.</string>
Do we normally put periods for popups?  Can you check?

2022-09-22 18:02 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/spaces/share/ShareSpaceLinkUI.kt
> +            onClickSocialShareButton = { params.onTogglePublic(true) },
Name the argument in `onTogglePublic`

2022-09-22 18:03 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/appnav/AppNavModelImpl.kt
> +import ShareSpaceSheet
Eh... I don't understand why your import is the only one in the entire repo that doesn't behave right.  Can you look into this, or say what you've tried?

2022-09-22 18:04 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +    <string name="share_space_confirmation_message">Invitation sent.</string>
It's inconsistent, Spaces does not use periods. But Settings and HistoryUI does. Good catch! Will ask design and update this thread. And also file an issue about this

2022-09-22 21:36 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +    <string name="share_space_confirmation_message">Invitation sent.</string>
From @yozuysal on Slack:
```
Periods

Avoid using periods in solitary sentences in these elements:

Labels
Hover text
Bulleted lists
Dialog body text
Periods should be used on:

Multiple sentences
Any sentence followed by a link
```

https://material.io/archive/guidelines/style/writing.html#writing-capitalization-punctuation

2022-09-22 21:37 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +    <string name="share_space_confirmation_message">Invitation sent.</string>
Going to do a quick refactor in this PR. Will make it 1 clean commit

2022-09-22 22:12 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/appnav/AppNavModelImpl.kt
> +import ShareSpaceSheet
@Kokobe

2022-09-22 22:13 UTC, Kokobe commented on app/src/main/java/com/neeva/app/appnav/AppNavModelImpl.kt
> +import ShareSpaceSheet
I found out the problem: I forgot to add the package at the top of ShareSpaceSheet

2022-09-22 22:24 UTC, dan-alcantara-neeva approved these changes

2022-09-23 22:16 UTC, merged