Add Download Callbacks and Snackbar Popups
neevaco/neeva-android pull request #976
Opened 2022-09-14 18:29 UTC by Kokobe

Uses `weblayer` to add a callback that listens for download events (`onStarted`, `onCompleted`, `onFailed`). 

* Displays a popup notification for each respective download event. 
* For `onCompleted`, it adds an action button to the popup notification that will open the file in the Downloads app 
* Created an injectable `ActivityStarter` as a general way to safely start an activity. 
## Checklists

### Pointers to help with review
* [Clickup task: Notify user using popup when download complete](https://app.clickup.com/t/3hqfnry)
* Discussion: #874 

### How was this tested?
- [x] I tested this manually
- [x] I added automated tests
- [x] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes

### Manual test cases
See below! (Tested and confirmed on API 29 as well)

### Screenshots and screen recordings

#### `onCompleted`: Downloading an image and immediately viewing it:

https://user-images.githubusercontent.com/20916043/190792529-ea575b29-2316-4c56-8b02-b59df17a9480.mov

#### `onFailed`: Downloading an image and it failed (tested by turning on Airplane Mode)
* If the image was already downloaded, `onCompleted` will still run

https://user-images.githubusercontent.com/20916043/190792684-a2113fc9-c8d9-4060-b51d-79e1a9ed7f4f.mov

## Issues addressed
* #874 
* Fixes #875

2022-09-20 00:19 UTC, dan-alcantara-neeva requested changes

2022-09-20 00:19 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/browsing/BaseBrowserWrapper.kt
> +        setUpDownloads(browser)
I think this can fire repeatedly, meaning that you will end up setting that download callback over and over again.  Is there a reason you moved it out of the other place?

2022-09-20 00:19 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +    ): Boolean { return false }
Put `return false` on its own line, or just make this line be `) = false`

2022-09-20 00:19 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +        // Storing as separate variables so onActionPerformed lambda does not store Download object
Lambdas will hold onto everything that's in scope where they're created, so this will hold onto `download` unless `download` is passed along from Chromium as a `WeakReference`.  What are you seeing that encouraged you to cache the values locally?

2022-09-20 00:19 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +    private fun safeStartActivityForIntent(intent: Intent) {
Should just add a new utility function for this instead of duplicating/forking the existing copy.

2022-09-20 00:19 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +        private val TAG = DownloadCallbackImpl::class.simpleName
Just use `DownloadCallbackImpl` so that Proguard doesn't munge the name in logs for release builds.

2022-09-20 00:19 UTC, dan-alcantara-neeva commented on app/src/main/res/values/strings.xml
> +    <string name="download_started">Download started for: %1$s</string>
Does iOS show popup notifications?  Do they have existing strings?

2022-09-20 17:05 UTC, Kokobe commented on app/src/main/java/com/neeva/app/browsing/BaseBrowserWrapper.kt
> +        setUpDownloads(browser)
Originally I actually had that Download Callback setup in `registerBrowserCallbacks()`. But now I see that the implementations of `BaseBrowserWrapper` actually check if they were already registered or not. 

Moving it back to registerBrowserCallbacks!

2022-09-20 17:14 UTC, Kokobe commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +        // Storing as separate variables so onActionPerformed lambda does not store Download object
So when I didn't use local variables and accessed them directly in the lambda like this:

```
onActionPerformed = {
                val openFileIntent = Intent()
                    .setAction(Intent.ACTION_VIEW)
                    .setDataAndType(Uri.fromFile(download.location), download.mimeType)
                    .setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                safeStartActivityForIntent(openFileIntent)
            }
```
I get this error:
```
 E  FATAL EXCEPTION: main
                                                                                                    Process: com.neeva.app.debug, PID: 28169
                                                                                                    java.lang.IllegalStateException: Using Download after native destroyed
                                                                                                    	at org.chromium.weblayer_private.DownloadImpl.throwIfNativeDestroyed(DownloadImpl.java:332)
                                                                                                    	at org.chromium.weblayer_private.DownloadImpl.getLocation(DownloadImpl.java:294)
                                                                                                    	at org.chromium.weblayer_private.interfaces.IDownload$Stub.onTransact(IDownload.java:146)
                                                                                                    	at android.os.Binder.transact(Binder.java:667)
                                                                                                    	at org.chromium.weblayer_private.interfaces.IDownload$Stub$Proxy.getLocation(IDownload.java:322)
                                                                                                    	at org.chromium.weblayer.Download.getLocation(Download.java:123)
                                                                                                    	at com.neeva.app.downloads.DownloadCallbackImpl$onDownloadCompleted$1.invoke(DownloadCallbackImpl.kt:72)
                                                                                                    	at com.neeva.app.downloads.DownloadCallbackImpl$onDownloadCompleted$1.invoke(DownloadCallbackImpl.kt:66)
```

2022-09-20 17:16 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +        // Storing as separate variables so onActionPerformed lambda does not store Download object
Ah, so the `Download` itself is fine, but the native `DownloadImpl` got nuked.

2022-09-20 17:18 UTC, Kokobe commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +    private fun safeStartActivityForIntent(intent: Intent) {
Should I make a class with a static function that anybody can call like `ActivityStarter.safeStartActivityForIntent(...)` is how you would call it from anywhere?

2022-09-20 17:20 UTC, Kokobe commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +        // Storing as separate variables so onActionPerformed lambda does not store Download object
Ah yeah cause `Download` has a private variable `IDownload mDownloadImpl` : 

<img width="721" alt="Screen Shot 2022-09-20 at 10 20 03 AM" src="https://user-images.githubusercontent.com/20916043/191323356-e72e73f0-1c7f-4848-b201-412f2f76f67c.png">

2022-09-20 17:23 UTC, Kokobe commented on app/src/main/res/values/strings.xml
> +    <string name="download_started">Download started for: %1$s</string>
iOS does not have popup notifications :( 

I guess iOS users just trust that it happened and will check their Photos or Files themselves.

2022-09-20 17:24 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +    private fun safeStartActivityForIntent(intent: Intent) {
Debating it... Might clean up `AppNavModelImpl` if you make another injectable that allows that.  Also means `ShareSpace` wouldn't need to randomly use `AppNavModel` to do it.  Trying to think of situations where we'd want to generalize it so that you could pass in (say) an Activity context instead of the application context, but we don't have any of those currently.

Give it a shot?

2022-09-20 17:46 UTC, Kokobe commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +    private fun safeStartActivityForIntent(intent: Intent) {
If I made another singleton injectable or used my method above and held an `ApplicationContext`, there wouldn't be any memory leak problems because ApplicationContext only dies when the applciation dies right?

So if I used an Activity Context, rotating the screen can cause my singleton to hold onto a deleted object no? Trying it out now

2022-09-20 18:36 UTC, Kokobe commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +    private fun safeStartActivityForIntent(intent: Intent) {
Also, I remember we had a conversation in person about not having `DownloadCallbackImpl` be an injectable class. (right now it depends on popupModel, appContext, and my new `ActivityStarter` class). 

We said that functionally, it didn't need to be an injectable and for the tests we would have to create mock versions of it too. But now that I'm making `ActivityStarter` injectable, I feel like I should do the same for `DownloadCallbackImpl` too? WDYT?

2022-09-20 18:41 UTC, Kokobe commented
Also, I remember we had a conversation in person about not having DownloadCallbackImpl be an injectable class. (right now it depends on popupModel, appContext, and my new ActivityStarter class).

We said that functionally, it didn't need to be an injectable and for the tests we would have to create mock versions of it too. But now that I'm making ActivityStarter injectable, I feel like I should do the same for DownloadCallbackImpl too? WDYT?

2022-09-20 19:13 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +        // Storing as separate variables so onActionPerformed lambda does not store Download object
Roughly, yes: that's how WebLayer has been set up.  That's why we have to constantly check if the Browser and Tab objects are alive when we use them -- especially when we're doing things asynchronously and the object could have been nuked while we were processing things in the background.

That said, caching the fields is the right thing to do.  We do something similar with the `Tab` when we want to save its ID while something runs in the background.

2022-09-20 19:20 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +    private fun safeStartActivityForIntent(intent: Intent) {
Copying some points from the offline Slack thread:

* `@ApplicationContext` is an annotation for Hilt that says we need it to inject the `Context` that is the `Application`.

* The `Application` lives as long as the process does, which means that it will outlast all of the `Activity`s that we have, which can be killed/restarted when the screen is rotated (among other ways).
  * This is why you can (e.g.) register an `ActivityLifecycleCallback` on the `Application` and be alerted when an `Activity` is created/started/stopped/etc.

* `@ActivityContext` is an annotation that says you want Hilt to inject an `Activity` as a `Context`.  You can't inject it into  a `@Singleton` because `Singleton` survives as long as the `Application` does. 

* The `Context` roughly represents the environment that runs around your code, which you use to access resources and make various system calls.  You ideally want to be using the closest context you can:
  * If you theme your `Application` differently from your `Activity`, you want to make sure that you pull the correct resources/colors/strings.
  * There are times when you don't want to be using the `Activity` `Context` because it can be killed.  If you have (say) an asynchronous process that should outlast the Activity, you want to use the `Application` `Context` instead.

2022-09-20 19:23 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +    private fun safeStartActivityForIntent(intent: Intent) {
Answer to this StackOverflow question is super old, but it's roughly still relevant:
https://stackoverflow.com/questions/4128589/difference-between-activity-context-and-application-context

2022-09-20 19:27 UTC, dan-alcantara-neeva commented
> Also, I remember we had a conversation in person about not having `DownloadCallbackImpl` be an injectable class. (right now it depends on `popupModel`, `appContext`, and my new `ActivityStarter` class).
> 
> We said that functionally, it didn't need to be an injectable and for the tests we would have to create mock versions of it too. But now that I'm making `ActivityStarter` injectable, I feel like I should do the same for `DownloadCallbackImpl` too? WDYT?

Still don't see a huge benefit for it, but if you're going to have the option between injecting a `DownloadCallbackImpl` and a `ActivityStarter` into the `BaseBrowserWrapper` classes, you might as well do the `DownloadCallbackImpl` to avoid piping this new field into a `DownloadCallbackImpl` you make on the fly.

Either way, you're going to have to mock _something_ for the tests.

2022-09-20 19:37 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/downloads/DownloadCallbackImpl.kt
> +    private fun safeStartActivityForIntent(intent: Intent) {
Should also toss on:
Another reason you'd normally want to use an `Activity` as the `Context` for launching another app is that you have the option of putting the new `Activity` on the same Android task stack (so they appear on top of our Activity in Android's recent apps list).  When you use `FLAG_ACTIVITY_NEW_TASK`, you tell Android to avoid doing that.  I'm mostly OK with that because it's hard to think of situations where we'd want another app to cover up their browser -- generally we're the ones sending the user to other apps.

2022-09-21 17:57 UTC, dan-alcantara-neeva reviewed
You planning on adding tests for this?

2022-09-21 19:17 UTC, Kokobe commented
> You planning on adding tests for this?

Not sure which kind of tests I should add @dan-alcantara-neeva. Instrumentation tests wouldn't be able to connect to the internet so the only Download callback that would work is the started or failure case. 

I can write tests to make sure that the popup is being shown when each download callback is being called. Is that useful?

2022-09-21 20:12 UTC, Kokobe commented
Making a test similar to `TabCallbacksTest` for DownloadCallback

2022-09-21 20:28 UTC, dan-alcantara-neeva commented
> Making a test similar to `TabCallbacksTest` for DownloadCallback

Yeah, was expecting tests for the `DownloadCallbackImpl`, just to make sure that things were firing as expected.

2022-09-22 17:57 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/browsing/DownloadCallbackTest.kt
> +class DownloadCallbackTest : BaseTest() {
This is a `DownloadCallbackImplTest` because you're testing the `DownloadCallbackImpl`.

2022-09-22 17:59 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/browsing/DownloadCallbackTest.kt
> +            any()
Might be worth checking that the Intent is doing what you want it to?

2022-09-22 17:59 UTC, dan-alcantara-neeva reviewed
Worth adding a check to see that the Intent has the right data, but overall looking good.

2022-09-22 22:48 UTC, merged