Add bloom filter binary download and test
neevaco/neeva-android pull request #977
Opened 2022-09-14 20:15 UTC by yasminyin96

* Add downloading pipeline([flowchart](https://mermaid.live/edit#pako:eNqNU01v2kAQ_SujPQPyZww-FDXYfCRWDqGVqtg5rOyhrGJ7Le86hAL_vYttCCBo45N35r03b95qNyTmCRKX_C5psYQfXpSD-r6HMwE_nwN4pylLhq_Q7X6DbX3Ywn3o8VWecppAvCwxfhNVBguW4mtLbtA5l9AyXsK55EXbvq_bo82UCvA_Yiwk47kY7pruqCE_oVzx8g3wALgQaWFHI__BPfFThBcGjfnGewv1aqh_w5ffCAX_GuZfGzZWaaGAlMc03acksazDUhgm5LCljhvqGsUWJuFo7wzYApiEjEplVECOq0vH40PQW5h-3snJjBY3ORH_Fc7pOx5ANE9AfC4w-aLgtMbNzqM6JDX74tXMrqX1cHX3i70fTvZ5PO6D5939EmfzHut6cON-g4Z1FLtpO7hm-0aqpEMyLDPKEvXCNnt-ROQSM4yIq34TXNAqlRGJ8p2C0kry-TqPiSvLCjukKhIq0WNUvc3svOgnTPKSuAuaClUsaP7C-RGjjsTdkA_i6nbP0CzDMPuW3betu8GgQ9bE7ep9p2dZpjkYaH1Tu7N1Z9chf2oJvWfomm2ZlmNrmmM4jrX7C8YYU48)): 

1. download checksum file using `OkHttpClient`
2. download reddit filter binary file(`reddit.bin`) using `OkHttpClient`
3. use `WorkManager` to limit the download task

> Example of checksum file:
{
	"sha": "cdc5da74cb17d4fca031bb16ef1961e9775037aed9025d604d3c6d6dd3ae571b",
	"md5": "837d7499739d451b7944a230e07acddc",
        "hash": "fe7351f",
	"canon": "5aa27ef"
} 

* Add loading pipeline([flowchart](https://mermaid.live/edit#pako:eNqNVd9vmzAQ_lcs9wWkJAosv-Bh07Y00qRuqpp107bswYUjYXEwM0Yro_nfZ2MIUMhSPxBz99333XFnJ8ce8wG7eMtJvEOfl5sIybUWhAs0HL5G73fg7W8Y8cHXroZBAZ4-sSekXm_DGGgYQRHaD_0GicYqLg3pRNaibykH4mcKEUbbBmPbUTOvBYt_qMfP_4NVxoWWMlaJnAx1AtfR7xTSVt2VqRa9k-yrkEJyDqXUSoNR_iKf_Ymo0hIk2ZuFYoNHM-nnyVyAVvmSya3YAXpHGTsg6RLAUSARCB7DRLw56rhVo1IWN22nJhi3nHmQnKEz293_Qmjo51-JRhd6sQ6XZSapp3ZBSmmmEnjW_SK2J58egEpuySIo22V8JHyv1aQyLSbHbHXMKEhUZ8MAEXR_d4PCBIVRpyizM5L5h57StUb1FTXQuE_gHF9nfg09xbSct7j0mc_aaahdTxMDLg2JYJxswewZKZU0ac8PgtJXZd0z9721einnEAmaoQdQubZrPx2IsqJf7AEJhrRs92PooERksoh6aKsla6Pu1UyuIBh4jDLuXgXFasbVZ7AdFwQqsonsXhsvU2iRX1QAv4u8XAOLX6ZQXQaXkY0T0YPEA3wAfiChL6_xXMVtsGzQATbYlVsfApJSscGb6CihJBVsnUUedgVPYYDT2CcCliGRfwCHtvHaD-UgYjcgNJHGmETfZcsrjHzFbo4fsTt5NR_Z46k1dhbzxWRmO7MBzrA7tC1rZE8mzng2X4wdy1lMjwP8t6CwRtbUWtiWM59PplPLmtjHf-loHeM)): 

1. load the Bloom Filter files
2. run query

* Update `canonical_url_v3.yaml`: add 2 test urls

* Update `Checksum`: add `hash` to check the hash versioning and `canon` to check the canonicalization versioning

* Add `testRedditFilter` unit test

* Add `BloomFilterDownloaderTest`: use OkHttp's `MockWebServer` to mock out the network responses to check the downloading pipeline

## Checklists

### Pointers to help with review

* [Filter and checksum URL](https://paper.dropbox.com/doc/Cheatsheet-Data--BpcI0bIUPQDpzTCXpiaNzRMhAg-lo1Qu3SeK9yUD7vipb60i)
* [NeevaScope Android Bloom Filter download management](https://paper.dropbox.com/doc/NeevaScope-Android-Bloom-Filter-download-management--Bp8WCQ_jBOQXF~7c46A0pkv_Ag-N67DRXpthzq5U9e8Y8W3r)

### How was this tested?
- [X] I tested this manually
- [X] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes

2022-09-19 23:32 UTC, dan-alcantara-neeva requested changes

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        private val TAG = BloomFilterManager::class.simpleName
Use "BloomFilterManager".  Stops it from getting munged by Proguard when we build a release build

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +    data class CheckSum(
`Checksum`.  It's one word (not two), so there's no camelcasing.

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        // file:///data/user/0/com.neeva.app.debug/cache/bloom_filter/reddit.bin
What's the comment for?

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +    data class BloomFilterConfiguration(
Add a `kdoc` to explain why this data class exists.  Looks like you're going to have one configuration for each type of bloom filter, with the only one currently being the one for Reddit?

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +    val bloomfilter = BloomFilter()
`val bloomFilter`
Bloom Filter is two words

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +    suspend fun getFilterBinaryFile(name: String): File {
Could you just inline the `getBloomFilterDirectory` function?

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +            load()
So this is always going to fail until it finishes loading?

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        if (
`filterUrl` and `checksumUrl` are constants, right?  Should you use `assert` instead?  That way if a developer accidentally changes the URLs to something wrong it'll crash instead of logging a failure.

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +                OkHttpClient().newCall(checksumRequest).execute().body?.let {
1. Don't keep creating `OkHttpClient`s: make one and cache it.  Is it OK to use an `OkHttpClient` that has the user's login tokens (if they're logged in)?  If so, then I can make a global one because I'm currently mucking with a bunch of these for the preview tokens.
2. `execute()` returns something that needs to be closed when you're done with it.  You can use the `use` function to make sure it gets closed correctly: `newCall(checksumRequest).execute().use {`

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +                    try {
You're already in a try block; you don't need to put another try.

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +                    val checksum = try {
You're already in a try block; you don't need to nest them.  If you want to know which call in your function failed, split them apart.

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +            val checksumRequest = Request.Builder().url(reddit.checksumUrl).build()
The way you've set this up, the app will keep trying to download the large Bloom Filter file over and over again until you successfully parse them.  If the backend is broken and changes its file format, or if we get output that we don't expect, or if the download gets interrupted, etc... you will be forcing the user to try downloading a large file over and over again.

We should be making an attempt to download these files at most once a day or so.  We should also make sure that the user is on an unmetered network connection to avoid destroying their mobile data allowances.  Can you sync with @EdwardJTL and @darinwf to see what behavior would be acceptable?

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +    private fun getCheckSumFromFile(digest: MessageDigest, fileUrl: Uri): String {
`getChecksumFromFile`

2022-09-19 23:32 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/neevascope/BloomFilterTest.kt
> +            // Backend upper case these percent encodings
Are these known errors in our implementation or in the BIN file produced by the backend?

2022-09-19 23:37 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        // file:///data/user/0/com.neeva.app.debug/cache/bloom_filter/reddit.bin
Oh, I forgot to remove this comment. I will remove this line.

2022-09-20 00:45 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +            val checksumRequest = Request.Builder().url(reddit.checksumUrl).build()
The file should be only downloaded through wifi and avoids cellular. I saw there is `ConnectivityManager` used in `NeevaUser` and `.isNetworkTypeWifi` which can check the network type, but it seems to be deprecated. I'm not sure how to disable the cellular.

The file should be only downloaded when users first browse the website and then the file will be saved locally. 
But when I quit the app and restart it, it will download the file again.

2022-09-20 16:52 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +            val checksumRequest = Request.Builder().url(reddit.checksumUrl).build()
Any time you're dealing with network connectivity, you need to keep the user's data plan in mind -- especially when you're downloading files (how big is the bloom filter file, anyway?  is it compressed?  should it be?).  The last thing you want to do is burn through their entire data plan because of a coding error or oversight.  Forcing the user to potentially download files over and over again when the app starts up is one of these situations.

1. You shouldn't disable cellular; you should avoid downloading anything if they're on cellular.  Sync with @Kokobe about how he did it.

2. There are many reasons your pipeline can fail and force you to redownload the files unnecessarily.  Off the top of my head:
  * If the backend mistakenly serves a checksum file that doesn't match the bloom filter file, you will keep downloading the bloom filter file because the checksums won't match.
  * If some network error prevents you from completely downloading the file (say the network gets cut off), you will keep trying until you succeed because you only check to see if there is a bloom filter file set up on line 62.
  * If there is an error processing the bloom filter file while you try to save it on line 114 (say because the user has no more storage on their device), you will try to download the file again.

To move forward, you should:
1. Look into what the non-deprecated methods for checking for **unmetered** connections are (ask @Kokobe).  Even wi-fi connections can be metered and can result in the user getting charged.
2. Sync with @EdwardJTL about how iOS handles their bloom filter downloading pipeline.  If they're not limiting the number of times these two files are being downloaded, they should be.
3. Make a flowchart that shows how everything can go and what should be done in those situations.  See either [this flowchart](https://paper.dropbox.com/doc/createOrSwitchToTab-behavior--BlQpTLcJ7qbCfDW0k96cRqjmAg-qvXWgOhIhtrLKkr62NFOS) or [this flowchart](https://mermaid.live/edit#pako:eNp9k91O4zAQhV9lZC4ACbiucgGCpqUtCGn5UaVNuDDOmFo4nsh2qo2avjtO0yZlKUSylBx9czJzbK-YoAxZxN4tLxbwHKcGwnOdpOwBcclfHNoLiV4sTk5T9grn55dwczJ14BdoETh01DN9oLk6betvGrCu0NUwXE24A-f5m0aYq7G6Wu8zhmqIkweCxmNqJIEnEBq5fW2xYW81Sq4L0prmodcCLYQlyeauq_1Toq2-1DX24yQmc-xb147dYqPNSLebJkf_BBZekXG7Hm83JnMlFQzJGBReLZWverKGyW_ubX1Hh9S4B-XAkIfvrhY195jVME2GP7uFrPpGa5it2lDgEV0RFIRFM4q1ZLsxZn2Gd4etZ11a94lD3-9G6ZR5hyXXKoP_frQtdb4KOxuDVFpHR0KIfXl8WJ4clqdbWQ4G-_LdYfl-Kw_kRmZnLEebc5WF47xqlJSFU5pjyqLwmqHkpfYpS806oGWRhaxHmfJkWSS5dnjGeOnpqTKCRd6WuINixcPtyDuq4OYv0e57_QmxORPr).
4. Put this into a doc so that we can make sure that we've covered all of our bases.

2022-09-20 17:06 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +            val checksumRequest = Request.Builder().url(reddit.checksumUrl).build()
Got it, thank you so much.

2022-09-20 21:40 UTC, EdwardJTL commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +            val checksumRequest = Request.Builder().url(reddit.checksumUrl).build()
on iOS, we download the binary file with a url session with these restrictions
```
// Disable downloading over cellular and restricted networks
        let config = URLSessionConfiguration.default
        config.allowsCellularAccess = false
        config.allowsExpensiveNetworkAccess = false
        config.allowsConstrainedNetworkAccess = false
        config.waitsForConnectivity = true
        return URLSession(configuration: config, delegate: nil, delegateQueue: downloadQueue)
```

2022-09-20 21:43 UTC, EdwardJTL commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +            val checksumRequest = Request.Builder().url(reddit.checksumUrl).build()
we save the bin file to disk, and only download if there's no valid bin file in the file system.
a description of the code flow is here: https://paper.dropbox.com/doc/NeevaScope-Backlinks-Launch-Doc--Bpjj9doRh~EB20xQ9ikKnFBZAg-k00a4k8TN5luw1M58gduj
no flow chart sorry :(

2022-09-20 21:43 UTC, Kokobe commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +            val checksumRequest = Request.Builder().url(reddit.checksumUrl).build()
Reposting from our slack convo: 
A non-deprecated way to check for unmetered connections is: https://developer.android.com/training/monitoring-device-state/connectivity-status-type

2022-09-20 21:44 UTC, EdwardJTL commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        @Json(name = "md5") val md5: String
we are also now checking backend tool versions. see
https://github.com/neevaco/neeva-ios/pull/4372

you can just hard code these values on the client side

2022-09-27 23:45 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +class BloomFilter {
Move this out to its own class

2022-09-28 00:59 UTC, dan-alcantara-neeva requested changes
Taking a first pass.  We really should finish the doc before you write code out, though.

2022-09-28 00:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterDownloadWorker.kt
> +            // If match, don't update the existing local filter fil
local filter **file**

2022-09-28 00:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterDownloadWorker.kt
> +            const val hasher = "fe7351f"
`const val` names should be all caps.  Should also specify what these actually mean with comments.

2022-09-28 00:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        file.mkdir()
1. Should you check if the directory exists before you try to create it?
2. You're not checking for any exceptions that get fired.  You need to add `try` and `catch` blocks and decide how to gracefully fail.  Probably put that in the design doc.

2022-09-28 00:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +    private fun load() {
Make this a suspend function so that it is explicitly telling the caller that it needs to be used inside of a `coroutineScope`

2022-09-28 00:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +            else -> {
1. Explicitly list out the other `WorkInfo.State` possibilities in a when loop instead of relying on `else`.  Otherwise it's hard to know why you're just funneling everything into re-enqueueing it.

2. If you're doing a periodic work request, why would you need to re-enqueue it here on line 100?

2022-09-28 00:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        if (!reddit.localUri.toFile().exists()) { return }
If you're putting the return on the same line, you can skip the braces.

2022-09-28 00:59 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        loading = true
1. This needs to be put right next to where you check for whether `loading == true`.  Otherwise, any early exits you included on line 97 and 104 will cause the variable to never be set.

2. This shouldn't be put inside of the `coroutineScope`.  The `IO` `Dispatcher` can run multiple coroutines in parallel, meaning that you can get into a race condition where you're checking a stale value of `load`.  Instead make sure it's checked and set before you even try to `launch` the coroutine (so if `loading == false`, launch the coroutine on line 82).

3. This shouldn't be a `loading` field: it should be a `loadAttempted` field so that the app doesn't try to load the file again until the next time it starts.  Otherwise, if you have a screwed up Bloom Filter file, you'll end up trying to load it every time you want to check the Bloom Filter (so on every page load).

2022-10-03 19:18 UTC, dan-alcantara-neeva requested changes

2022-10-03 19:18 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterDownloadWorker.kt
> +                return@withContext
No need for this else clause; there's no further code after this so it'll return anyway.

2022-10-03 19:18 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterDownloadWorker.kt
> +    private fun updateDigest(digest: MessageDigest, data: InputStream): MessageDigest {
Can you inline this function into `getChecksumFromFile`?

2022-10-03 19:18 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterDownloadWorker.kt
> +        var read = data.read(byteArray, 0, size)
What's `var read` here?  The number of bytes read?  Can you rename this to `numBytesRead` so that it doesn't get conflated with `data.read`?

2022-10-03 19:18 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +        if (!file.exists()) { file.mkdir() }
Don't need the `{` and `}`

2022-10-03 19:40 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterManager.kt
> +             * Note that PeriodicWorkRequests will never enter this state (they will simply go back to ENQUEUED and be eligible to run again)
1. `this` State means the State of the `WorkRequest`. Yes, it's the comment for `isFinished` in `WorkInfo.java`
2. Yes, it passed. I will break the line at 100 chars

2022-10-03 23:26 UTC, yasminyin96 commented on app/src/main/java/com/neeva/app/neevascope/BloomFilter.kt
> +        filter?.let {
I tried to make the set private `private var _filter: Filter? = null` `val filter: Filter? get() = _filter`
but it always shows an error "Smart cast to 'BloomFilter.Filter' is impossible, because 'filter' is a property that has open or custom getter" and needs to add non-null assesrted `!!` when I use `filter` here.

2022-10-04 19:37 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilter.kt
> +    val filter: Filter? get() = _filter
You should be able to just do something like
```
var filter: Filter? private set
```

2022-10-04 19:42 UTC, dan-alcantara-neeva requested changes

2022-10-04 19:42 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterDownloadWorker.kt
> +            return Hex.bytesToStringLowercase(digestBytes)
Can you specify which Exceptions you're trying to catch here?  It's good to narrow it down to show that you are expecting specific things to go wrong.  If a crash is logged that we're not expecting, then we know something else is going wrong and we need to revisit our assumptions.

2022-10-04 19:42 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilterDownloadWorker.kt
>          val jsonAdapter = moshi.adapter(Checksum::class.java)
Can't this `adapter` function also throw an exception?  Should live inside the `try` with the other things.

2022-10-04 19:44 UTC, dan-alcantara-neeva requested changes

2022-10-04 19:44 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/neevascope/BloomFilter.kt
> +        val numBits = (filter!!.dataByteArray.size * 8).toUInt()
The !! you're using now is because you can change `filter`.  If you're going to get stuck using `!!`, you should just go back to using the `let` like you had it before.

2022-10-05 17:59 UTC, dan-alcantara-neeva reviewed
PR seems to do what it needs to...  @Kokobe reminded me that you need to write tests for the pipeline, though.  Would help to make sure that you're testing each of the codepaths correctly.  You'll want to look into OkHttp's `MockWebServer` to mock out the network responses:

`https://github.com/square/okhttp/tree/master/mockwebserver`

2022-10-10 21:28 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/neevascope/BloomFilterDownloaderTest.kt
> +        val dispatcher = object : Dispatcher() {
Huh, neat.  Didn't know you could do it this way

2022-10-10 21:29 UTC, dan-alcantara-neeva commented on app/src/test/java/com/neeva/app/neevascope/BloomFilterDownloaderTest.kt
> +    @Test
Can you add a test that has a checksum file that doesn't match the bloom filter file?

2022-10-10 22:25 UTC, dan-alcantara-neeva approved these changes
Seems good to go...  Could you wait until tomorrow morning until landing this?  Want to cut a new release tonight and want to avoid putting this in in case we missed something.

2022-10-10 22:28 UTC, yasminyin96 commented
> Seems good to go... Could you wait until tomorrow morning until landing this? Want to cut a new release tonight and want to avoid putting this in in case we missed something.

Sure.

2022-10-11 17:29 UTC, merged