Fetch play install referrer
neevaco/neeva-android pull request #991
Opened 2022-09-22 05:51 UTC by chung-lai

* Add the install referrer library to gradle
* initiate connection to play api for requesting install referrer for tracking
* only fetch this information once per user

## Checklists

### How was this tested?
- [ ] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes

**Test case**

* Load on a device and make sure the referrer url is filled

2022-09-22 20:55 UTC, dan-alcantara-neeva requested changes

2022-09-22 20:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +        lifecycleScope.launchWhenResumed {
Given that this is a `launchWhenResumed` call, it will only fire once when the `lifecycleScope` has hit the `resumed` state.  However, because you're putting this call in `onStart`, you're effectively making the app reschedule this check every single time the app is brought to the foreground.  You should stick it with the other calls in `onCreate`.

2022-09-22 20:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +    private fun requestInstallReferrer() {
This is a lot of code to be sticking in the Activity.  Can you put it in the `NeevaActivityViewModel`?

2022-09-22 20:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                            e.printStackTrace()
Use the Log class instead of a naked `printStackTrace` call.

`Log.e(TAG, "message", e)`

2022-09-22 20:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                SharedPrefFolder.App.RequestedInstallReferrer.set(
Should this value be set if you fail to perform the request?  Because the request is fired asynchronously, you're setting the SharedPreference before it has a chance to complete.

2022-09-22 20:55 UTC, dan-alcantara-neeva commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                // Try to restart the connection on the next request to
Is this a comment copied from somewhere?  Don't know if you ever try to make another request because you gate it with a `SharedPreference` check.

2022-09-22 21:30 UTC, chung-lai commented on app/src/main/java/com/neeva/app/NeevaActivity.kt
> +                SharedPrefFolder.App.RequestedInstallReferrer.set(
From looking at the response, I would be ok to do this once per user to start with. If we notice it fails frequently (which we have logging) and will look into whether we want to retry

2022-09-22 22:15 UTC, dan-alcantara-neeva approved these changes

2022-09-26 21:44 UTC, dan-alcantara-neeva commented
Squashing and merging based on offline chat with @chung-lai

2022-09-26 22:31 UTC, merged